import type { SectionSeed } from './build'

/** Track C — Java & Backend Engineering */
export const TRACK_C_SECTIONS: SectionSeed[] = [
  {
    id: 'C1',
    track: 'C',
    title: 'Core Java',
    order: 1,
    defaultKind: 'theory',
    defaultDepth: 'deep',
    topics: [
      { id: 'c1-oop', title: 'OOP', priority: 'tier1', months: [1, 2], tags: ['java'] },
      { id: 'c1-classes', title: 'Classes/Interfaces', priority: 'tier1', months: [1, 2], tags: ['java'] },
      { id: 'c1-interfaces', title: 'Interfaces', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'c1-classes', months: [1, 2], tags: ['java'] },
      { id: 'c1-abstract-classes', title: 'Abstract Classes', priority: 'tier1', months: [1, 2], tags: ['java'] },
      { id: 'c1-encapsulation', title: 'Encapsulation', priority: 'tier1', months: [1, 2], tags: ['java'] },
      { id: 'c1-inheritance', title: 'Inheritance', priority: 'tier1', months: [1, 2], tags: ['java'] },
      { id: 'c1-polymorphism', title: 'Polymorphism', priority: 'tier1', months: [1, 2], tags: ['java'] },
      { id: 'c1-records', title: 'Records', priority: 'tier1', months: [1, 2], tags: ['java'] },
      { id: 'c1-enums', title: 'Enums', priority: 'tier1', months: [1, 2], tags: ['java'] },
      { id: 'c1-immutability', title: 'Immutability', priority: 'tier1', months: [1, 2], tags: ['java'] },
      { id: 'c1-exceptions', title: 'Exceptions', priority: 'tier1', months: [1, 2], tags: ['java'] },
      { id: 'c1-generics', title: 'Generics', priority: 'tier1', months: [1, 2], tags: ['java'] },
      { id: 'c1-annotations', title: 'Annotations', priority: 'tier1', months: [1, 2], tags: ['java'] },
      { id: 'c1-list-set-map', title: 'List / Set / Map', priority: 'tier1', months: [1, 2], tags: ['java', 'collections'] },
      { id: 'c1-arraylist', title: 'ArrayList', priority: 'tier1', months: [1, 2], tags: ['java', 'collections'], related: ['a1-arraylist'] },
      { id: 'c1-hashmap-internals', title: 'HashMap Internals', priority: 'tier1', months: [1, 2], tags: ['java', 'collections'], depth: 'deep', related: ['a1-hashmap'] },
      { id: 'c1-hashset', title: 'HashSet', priority: 'tier1', months: [1, 2], tags: ['java', 'collections'] },
      { id: 'c1-treemap', title: 'TreeMap', priority: 'tier1', months: [1, 2], tags: ['java', 'collections'] },
      { id: 'c1-priorityqueue', title: 'PriorityQueue', priority: 'tier1', months: [1, 2], tags: ['java', 'collections'] },
      { id: 'c1-concurrenthashmap', title: 'ConcurrentHashMap', priority: 'tier1', months: [1, 2], tags: ['java', 'concurrency'], related: ['c3-concurrent-collections'] },
      { id: 'c1-equals', title: 'equals() / hashCode()', priority: 'tier1', months: [1, 2], tags: ['java'] },
      { id: 'c1-hashcode', title: 'hashCode()', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'c1-equals', months: [1, 2], tags: ['java'], related: ['c1-equals', 'c1-hashmap-internals'] },
      { id: 'c1-lambdas', title: 'Lambdas', priority: 'tier1', months: [1, 2], tags: ['java'] },
      { id: 'c1-functional-interfaces', title: 'Functional Interfaces', priority: 'tier1', months: [1, 2], tags: ['java'] },
      { id: 'c1-streams', title: 'Streams', priority: 'tier1', months: [1, 2], tags: ['java'] },
      { id: 'c1-optional', title: 'Optional', priority: 'tier1', months: [1, 2], tags: ['java'] },
      { id: 'c1-method-references', title: 'Method References', priority: 'tier2', months: [2, 3], tags: ['java'] },
    ],
  },
  {
    id: 'C2',
    track: 'C',
    title: 'JVM',
    order: 2,
    defaultKind: 'theory',
    defaultDepth: 'deep',
    topics: [
      { id: 'c2-jvm-jdk-jre', title: 'JVM / JDK / JRE', priority: 'tier1', months: [1, 2], tags: ['jvm'] },
      { id: 'c2-bytecode', title: 'Bytecode', priority: 'tier1', months: [1, 2], tags: ['jvm'] },
      { id: 'c2-stack-vs-heap', title: 'Stack vs Heap', priority: 'tier1', months: [1, 2], tags: ['jvm'] },
      { id: 'c2-object-allocation', title: 'Object Allocation', priority: 'tier1', months: [1, 2], tags: ['jvm'] },
      { id: 'c2-garbage-collection', title: 'Garbage Collection', priority: 'tier1', months: [1, 2], tags: ['jvm'], depth: 'deep' },
      { id: 'c2-gc-algorithms', title: 'GC Algorithms/Concepts', priority: 'tier1', months: [1, 2], tags: ['jvm'], prereqs: ['c2-garbage-collection'] },
      { id: 'c2-class-loading', title: 'Class Loading', priority: 'tier2', months: [3, 4], tags: ['jvm'] },
      { id: 'c2-jit', title: 'JIT Compilation', priority: 'tier2', months: [3, 4], tags: ['jvm'] },
      { id: 'c2-profiling', title: 'JVM Profiling', priority: 'tier2', months: [5, 6], tags: ['jvm'] },
      { id: 'c2-memory-leaks', title: 'Memory Leaks', priority: 'tier2', months: [5, 6], tags: ['jvm'] },
      { id: 'c2-heap-dumps', title: 'Heap Dumps/Thread Dumps', priority: 'tier2', months: [5, 6], tags: ['jvm'] },
      { id: 'c2-thread-dumps', title: 'Thread Dumps', priority: 'tier2', curriculumLevel: 'nested-concept', parentTopicId: 'c2-heap-dumps', months: [5, 6], tags: ['jvm'], related: ['c3-deadlocks'] },
    ],
  },
  {
    id: 'C3',
    track: 'C',
    title: 'Java Concurrency',
    order: 3,
    defaultKind: 'theory',
    defaultDepth: 'deep',
    topics: [
      { id: 'c3-processes-vs-threads', title: 'Processes vs Threads', priority: 'tier1', months: [1, 2], tags: ['concurrency'] },
      { id: 'c3-thread-lifecycle', title: 'Thread Lifecycle', priority: 'tier1', months: [1, 2], tags: ['concurrency'] },
      { id: 'c3-race-conditions', title: 'Race Conditions', priority: 'tier1', months: [1, 2], tags: ['concurrency'] },
      { id: 'c3-synchronization', title: 'Synchronization', priority: 'tier1', months: [1, 2], tags: ['concurrency'] },
      { id: 'c3-synchronized', title: 'synchronized', priority: 'tier1', months: [1, 2], tags: ['concurrency'] },
      { id: 'c3-locks', title: 'Locks', priority: 'tier1', months: [1, 2], tags: ['concurrency'] },
      { id: 'c3-atomics', title: 'Atomic Classes', priority: 'tier1', months: [1, 2], tags: ['concurrency'] },
      { id: 'c3-volatile', title: 'volatile', priority: 'tier1', months: [1, 2], tags: ['concurrency'] },
      { id: 'c3-jmm', title: 'Java Memory Model', priority: 'tier1', months: [1, 2], tags: ['concurrency'], depth: 'deep' },
      { id: 'c3-thread-pools', title: 'Thread Pools', priority: 'tier1', months: [1, 2], tags: ['concurrency'] },
      { id: 'c3-executors', title: 'Executors', priority: 'tier1', months: [1, 2], tags: ['concurrency'] },
      { id: 'c3-futures', title: 'Futures', priority: 'tier1', months: [1, 2], tags: ['concurrency'] },
      { id: 'c3-completablefuture', title: 'CompletableFuture', priority: 'tier1', months: [1, 2], tags: ['concurrency'] },
      { id: 'c3-concurrent-collections', title: 'Concurrent Collections', priority: 'tier1', months: [1, 2], tags: ['concurrency'] },
      { id: 'c3-deadlocks', title: 'Deadlocks', priority: 'tier1', months: [1, 2], tags: ['concurrency'] },
      { id: 'c3-starvation', title: 'Starvation', priority: 'tier1', months: [1, 2], tags: ['concurrency'] },
      { id: 'c3-producer-consumer', title: 'Producer-Consumer', priority: 'tier1', months: [1, 2], tags: ['concurrency'] },
      { id: 'c3-virtual-threads', title: 'Virtual Threads', priority: 'tier2', months: [5, 6], tags: ['concurrency'] },
      { id: 'c3-forkjoin', title: 'ForkJoinPool', priority: 'tier2', months: [5, 6], tags: ['concurrency'] },
    ],
  },
  {
    id: 'C4',
    track: 'C',
    title: 'Networking & Web',
    order: 4,
    defaultKind: 'theory',
    defaultDepth: 'deep',
    topics: [
      { id: 'c4-tcp-ip', title: 'TCP/IP Concepts', priority: 'tier1', months: [1, 2], tags: ['networking'] },
      { id: 'c4-dns', title: 'DNS', priority: 'tier1', months: [1, 2], tags: ['networking'] },
      { id: 'c4-http', title: 'HTTP/HTTPS', priority: 'tier1', months: [1, 2], tags: ['networking', 'http'], depth: 'deep' },
      { id: 'c4-https', title: 'HTTPS', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'c4-http', months: [1, 2], tags: ['networking', 'http'] },
      { id: 'c4-http-methods', title: 'HTTP Methods', priority: 'tier1', months: [1, 2], tags: ['http'] },
      { id: 'c4-headers', title: 'Headers', priority: 'tier1', months: [1, 2], tags: ['http'] },
      { id: 'c4-status-codes', title: 'Status Codes', priority: 'tier1', months: [1, 2], tags: ['http'] },
      { id: 'c4-keep-alive', title: 'Keep-Alive', priority: 'tier1', months: [1, 2], tags: ['http'] },
      { id: 'c4-tls', title: 'TLS Basics', priority: 'tier1', months: [1, 2], tags: ['networking', 'security'] },
      { id: 'c4-rest', title: 'REST', priority: 'tier1', months: [1, 2], tags: ['api'], related: ['d6-rest'] },
      { id: 'c4-json', title: 'JSON', priority: 'tier1', months: [1, 2], tags: ['api'] },
      { id: 'c4-cookies', title: 'Cookies', priority: 'tier1', months: [1, 2], tags: ['http'], related: ['b3-cookies'] },
      { id: 'c4-sessions', title: 'Sessions', priority: 'tier1', months: [1, 2], tags: ['http'] },
      { id: 'c4-cors', title: 'CORS', priority: 'tier1', months: [1, 2], tags: ['http', 'security'], related: ['b3-cors'] },
      { id: 'c4-reverse-proxies', title: 'Reverse Proxies', priority: 'tier1', months: [2, 3], tags: ['networking'] },
      { id: 'c4-load-balancers', title: 'Load Balancers', priority: 'tier1', months: [2, 3], tags: ['networking'], related: ['d4-load-balancing'] },
      { id: 'c4-http2', title: 'HTTP/2', priority: 'tier2', months: [4, 5], tags: ['http'] },
      { id: 'c4-http3', title: 'HTTP/3', priority: 'tier2', months: [4, 5], tags: ['http'] },
      { id: 'c4-grpc', title: 'gRPC', priority: 'tier2', months: [5, 6], tags: ['api'], related: ['d6-grpc'] },
    ],
  },
  {
    id: 'C5',
    track: 'C',
    title: 'Spring Core',
    order: 5,
    defaultKind: 'theory',
    defaultDepth: 'deep',
    topics: [
      { id: 'c5-ioc', title: 'IoC', priority: 'tier1', months: [3, 4], tags: ['spring'] },
      { id: 'c5-di', title: 'Dependency Injection', priority: 'tier1', months: [3, 4], tags: ['spring'] },
      { id: 'c5-beans', title: 'Beans', priority: 'tier1', months: [3, 4], tags: ['spring'] },
      { id: 'c5-bean-lifecycle', title: 'Bean Lifecycle', priority: 'tier1', months: [3, 4], tags: ['spring'] },
      { id: 'c5-applicationcontext', title: 'ApplicationContext', priority: 'tier1', months: [3, 4], tags: ['spring'] },
      { id: 'c5-component-scanning', title: 'Component Scanning', priority: 'tier1', months: [3, 4], tags: ['spring'] },
      { id: 'c5-configuration', title: 'Configuration', priority: 'tier1', months: [3, 4], tags: ['spring'] },
      { id: 'c5-profiles', title: 'Profiles', priority: 'tier1', months: [3, 4], tags: ['spring'] },
      { id: 'c5-constructor-injection', title: 'Constructor Injection', priority: 'tier1', months: [3, 4], tags: ['spring'] },
      { id: 'c5-aop', title: 'AOP', priority: 'tier2', months: [4, 5], tags: ['spring'] },
      { id: 'c5-proxies', title: 'Spring Proxies', priority: 'tier2', months: [4, 5], tags: ['spring'] },
    ],
  },
  {
    id: 'C6',
    track: 'C',
    title: 'Spring Boot',
    order: 6,
    defaultKind: 'theory',
    defaultDepth: 'deep',
    topics: [
      { id: 'c6-project-structure', title: 'Project Structure', priority: 'tier1', months: [3, 4], tags: ['spring-boot'] },
      { id: 'c6-auto-configuration', title: 'Auto-configuration', priority: 'tier1', months: [3, 4], tags: ['spring-boot'], depth: 'deep' },
      { id: 'c6-properties', title: 'Configuration/Properties', priority: 'tier1', months: [3, 4], tags: ['spring-boot'] },
      { id: 'c6-rest-controllers', title: 'REST Controllers', priority: 'tier1', months: [3, 4], tags: ['spring-boot'] },
      { id: 'c6-request-lifecycle', title: 'Request/Response Lifecycle', priority: 'tier1', months: [3, 4], tags: ['spring-boot'] },
      { id: 'c6-dtos', title: 'DTOs', priority: 'tier1', months: [3, 4], tags: ['spring-boot'] },
      { id: 'c6-validation', title: 'Validation', priority: 'tier1', months: [3, 4], tags: ['spring-boot'] },
      { id: 'c6-exception-handling', title: 'Global Exception Handling', priority: 'tier1', months: [3, 4], tags: ['spring-boot'] },
      { id: 'c6-filters', title: 'Filters/Interceptors', priority: 'tier1', months: [3, 4], tags: ['spring-boot'] },
      { id: 'c6-interceptors', title: 'Interceptors', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'c6-filters', months: [3, 4], tags: ['spring-boot'] },
      { id: 'c6-logging', title: 'Logging', priority: 'tier1', months: [3, 4], tags: ['spring-boot'] },
      { id: 'c6-api-versioning', title: 'API Versioning', priority: 'tier1', months: [3, 4], tags: ['spring-boot'] },
      { id: 'c6-pagination', title: 'Pagination', priority: 'tier1', months: [3, 4], tags: ['spring-boot'] },
      { id: 'c6-actuator', title: 'Actuator', priority: 'tier1', months: [3, 4], tags: ['spring-boot'] },
      { id: 'c6-testing', title: 'Spring Boot Testing', priority: 'tier1', months: [3, 4], tags: ['spring-boot', 'testing'] },
    ],
  },
  {
    id: 'C7',
    track: 'C',
    title: 'SQL & PostgreSQL',
    order: 7,
    defaultKind: 'theory',
    defaultDepth: 'deep',
    topics: [
      { id: 'c7-crud', title: 'SELECT / INSERT / UPDATE / DELETE', priority: 'tier1', months: [3, 4], tags: ['sql', 'postgresql'] },
      { id: 'c7-joins', title: 'Joins', priority: 'tier1', months: [3, 4], tags: ['sql'] },
      { id: 'c7-aggregations', title: 'Aggregations', priority: 'tier1', months: [3, 4], tags: ['sql'] },
      { id: 'c7-subqueries', title: 'Subqueries', priority: 'tier1', months: [3, 4], tags: ['sql'] },
      { id: 'c7-ctes', title: 'CTEs', priority: 'tier1', months: [3, 4], tags: ['sql'] },
      { id: 'c7-window-functions', title: 'Window Functions', priority: 'tier1', months: [3, 4], tags: ['sql'] },
      { id: 'c7-transactions', title: 'Transactions', priority: 'tier1', months: [3, 4], tags: ['sql', 'postgresql'], related: ['c7-isolation-levels'] },
      { id: 'c7-acid', title: 'ACID', priority: 'tier1', months: [3, 4], tags: ['postgresql'], related: ['c7-transactions'] },
      {
        id: 'c7-isolation-levels',
        title: 'PostgreSQL Isolation Levels',
        priority: 'tier1',
        months: [3, 4],
        tags: ['postgresql', 'transactions', 'mvcc', 'concurrency'],
        prereqs: ['c7-transactions', 'c7-acid'],
        related: ['c7-mvcc', 'c7-locks', 'c8-optimistic-locking', 'd10-ticket-booking'],
        next: ['c7-locks'],
        capstone: 'Prevents inconsistent concurrent ticket reservations and double-booking under load.',
        contentReady: true,
        depth: 'deep',
      },
      { id: 'c7-locks', title: 'Locks', priority: 'tier1', months: [3, 4], tags: ['postgresql'], prereqs: ['c7-isolation-levels'] },
      { id: 'c7-deadlocks', title: 'Deadlocks', priority: 'tier1', months: [3, 4], tags: ['postgresql'], related: ['c3-deadlocks'] },
      { id: 'c7-mvcc', title: 'MVCC', priority: 'tier1', months: [3, 4], tags: ['postgresql'], depth: 'deep', related: ['c7-isolation-levels'] },
      { id: 'c7-indexes', title: 'Indexes', priority: 'tier1', months: [3, 4], tags: ['postgresql'] },
      { id: 'c7-btrees', title: 'B/B+ Trees Conceptually', priority: 'tier1', months: [3, 4], tags: ['postgresql'], related: ['c7-indexes'] },
      { id: 'c7-composite-indexes', title: 'Composite Indexes', priority: 'tier1', months: [3, 4], tags: ['postgresql'] },
      { id: 'c7-query-plans', title: 'Query Plans', priority: 'tier1', months: [3, 4], tags: ['postgresql'] },
      { id: 'c7-explain', title: 'EXPLAIN', priority: 'tier1', months: [3, 4], tags: ['postgresql'], prereqs: ['c7-query-plans'] },
      { id: 'c7-query-optimization', title: 'Query Optimization', priority: 'tier1', months: [3, 4], tags: ['postgresql'] },
      { id: 'c7-connection-pooling', title: 'Connection Pooling', priority: 'tier1', months: [3, 4], tags: ['postgresql'] },
      { id: 'c7-schema-design', title: 'Schema Design', priority: 'tier1', months: [3, 4], tags: ['postgresql'] },
      { id: 'c7-normalization', title: 'Normalization/Denormalization', priority: 'tier1', months: [3, 4], tags: ['postgresql'] },
      { id: 'c7-denormalization', title: 'Denormalization', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'c7-normalization', months: [3, 4], tags: ['postgresql'] },
      { id: 'c7-replication', title: 'Replication', priority: 'tier2', months: [5, 6], tags: ['postgresql'], related: ['d4-replication'] },
      { id: 'c7-partitioning', title: 'Partitioning', priority: 'tier2', months: [5, 6], tags: ['postgresql'], related: ['d4-partitioning'] },
    ],
  },
  {
    id: 'C8',
    track: 'C',
    title: 'JPA / Hibernate',
    order: 8,
    defaultKind: 'theory',
    defaultDepth: 'deep',
    topics: [
      { id: 'c8-entities', title: 'Entities', priority: 'tier1', months: [3, 4], tags: ['jpa'] },
      { id: 'c8-relationships', title: 'Relationships', priority: 'tier1', months: [3, 4], tags: ['jpa'] },
      { id: 'c8-repositories', title: 'Repositories', priority: 'tier1', months: [3, 4], tags: ['jpa'] },
      { id: 'c8-persistence-context', title: 'Persistence Context', priority: 'tier1', months: [3, 4], tags: ['jpa'], depth: 'deep' },
      { id: 'c8-entity-lifecycle', title: 'Entity Lifecycle', priority: 'tier1', months: [3, 4], tags: ['jpa'] },
      { id: 'c8-lazy-loading', title: 'Lazy/Eager Loading', priority: 'tier1', months: [3, 4], tags: ['jpa'] },
      { id: 'c8-eager-loading', title: 'Eager Loading', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'c8-lazy-loading', months: [3, 4], tags: ['jpa'] },
      { id: 'c8-nplus1', title: 'N+1 Problem', priority: 'tier1', months: [3, 4], tags: ['jpa'] },
      { id: 'c8-transactions', title: 'JPA Transactions', priority: 'tier1', months: [3, 4], tags: ['jpa'], related: ['c7-transactions'] },
      { id: 'c8-dirty-checking', title: 'Dirty Checking', priority: 'tier1', months: [3, 4], tags: ['jpa'] },
      { id: 'c8-fetch-joins', title: 'Fetch Joins', priority: 'tier1', months: [3, 4], tags: ['jpa'] },
      { id: 'c8-optimistic-locking', title: 'Optimistic/Pessimistic Locking', priority: 'tier1', months: [3, 4], tags: ['jpa'], related: ['c7-isolation-levels'], capstone: 'Versioned seat/inventory updates under concurrent booking attempts.' },
      { id: 'c8-pessimistic-locking', title: 'Pessimistic Locking', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'c8-optimistic-locking', months: [3, 4], tags: ['jpa'], related: ['c7-locks'] },
      { id: 'c8-orm-abuse', title: 'Avoiding ORM Abuse', priority: 'tier1', months: [3, 4], tags: ['jpa'] },
    ],
  },
  {
    id: 'C9',
    track: 'C',
    title: 'Security',
    order: 9,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'c9-authentication', title: 'Authentication vs Authorization', priority: 'tier1', months: [4, 5], tags: ['security'] },
      { id: 'c9-spring-security', title: 'Spring Security', priority: 'tier1', months: [4, 5], tags: ['security', 'spring'] },
      { id: 'c9-sessions', title: 'Sessions (Security)', priority: 'tier1', months: [4, 5], tags: ['security'] },
      { id: 'c9-jwt', title: 'JWT', priority: 'tier1', months: [4, 5], tags: ['security'] },
      { id: 'c9-oauth2', title: 'OAuth 2.0 Concepts', priority: 'tier1', months: [4, 5], tags: ['security'] },
      { id: 'c9-oidc', title: 'OpenID Connect Concepts', priority: 'tier1', months: [4, 5], tags: ['security'] },
      { id: 'c9-rbac', title: 'RBAC', priority: 'tier1', months: [4, 5], tags: ['security'] },
      { id: 'c9-password-hashing', title: 'Password Hashing', priority: 'tier1', months: [4, 5], tags: ['security'] },
      { id: 'c9-csrf', title: 'CSRF', priority: 'tier1', months: [4, 5], tags: ['security'] },
      { id: 'c9-xss', title: 'XSS', priority: 'tier1', months: [4, 5], tags: ['security'] },
      { id: 'c9-sql-injection', title: 'SQL Injection', priority: 'tier1', months: [4, 5], tags: ['security'] },
      { id: 'c9-cors-security', title: 'CORS (Security)', priority: 'tier1', months: [4, 5], tags: ['security'], related: ['c4-cors'] },
      { id: 'c9-secrets', title: 'Secrets Management', priority: 'tier1', months: [4, 5], tags: ['security'] },
      { id: 'c9-owasp', title: 'OWASP Basics', priority: 'tier1', months: [4, 5], tags: ['security'] },
    ],
  },
  {
    id: 'C10',
    track: 'C',
    title: 'Redis',
    order: 10,
    defaultKind: 'theory',
    defaultDepth: 'deep',
    topics: [
      { id: 'c10-data-structures', title: 'Redis Data Structures', priority: 'tier1', months: [5, 6], tags: ['redis'] },
      { id: 'c10-cache-aside', title: 'Cache-Aside', priority: 'tier1', months: [5, 6], tags: ['redis', 'caching'] },
      { id: 'c10-ttl', title: 'TTL', priority: 'tier1', months: [5, 6], tags: ['redis'] },
      { id: 'c10-invalidation', title: 'Cache Invalidation', priority: 'tier1', months: [5, 6], tags: ['redis', 'caching'], related: ['d7-cache-invalidation'] },
      { id: 'c10-distributed-caching', title: 'Distributed Caching', priority: 'tier1', months: [5, 6], tags: ['redis'], related: ['d5-caching'] },
      { id: 'c10-rate-limiting', title: 'Rate Limiting with Redis', priority: 'tier1', months: [5, 6], tags: ['redis'], related: ['d10-rate-limiter'], capstone: 'Relevant to inventory/cache/rate-limiting decisions for flash sales.' },
      { id: 'c10-when-not-to-cache', title: 'When Not to Cache', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'c10-cache-aside', months: [5, 6], tags: ['redis'] },
      { id: 'c10-distributed-locks', title: 'Distributed Locks', priority: 'tier2', months: [5, 6], tags: ['redis'] },
      { id: 'c10-pubsub', title: 'Pub/Sub', priority: 'tier2', months: [5, 6], tags: ['redis'] },
      { id: 'c10-persistence', title: 'Redis Persistence', priority: 'tier2', months: [5, 6], tags: ['redis'] },
      { id: 'c10-replication', title: 'Redis Replication', priority: 'tier2', months: [5, 6], tags: ['redis'] },
    ],
  },
  {
    id: 'C11',
    track: 'C',
    title: 'Kafka & Event-Driven Systems',
    order: 11,
    defaultKind: 'theory',
    defaultDepth: 'deep',
    topics: [
      { id: 'c11-eda', title: 'Event-Driven Architecture', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-topics', title: 'Topics', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-partitions', title: 'Partitions', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-producers', title: 'Producers', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-consumers', title: 'Consumers', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-consumer-groups', title: 'Consumer Groups', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-offsets', title: 'Offsets', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-ordering', title: 'Ordering Guarantees', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-at-most-once', title: 'At-Most/At-Least/Exactly-Once Concepts', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-at-least-once', title: 'At-Least-Once', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'c11-at-most-once', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-exactly-once', title: 'Exactly-Once Concepts', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'c11-at-most-once', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-idempotent-consumers', title: 'Idempotent Consumers', priority: 'tier1', months: [5, 6], tags: ['kafka'], related: ['c12-idempotency'], capstone: 'Relevant to duplicate payment/order events.' },
      { id: 'c11-retries', title: 'Retries', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-dlq', title: 'Dead-Letter Queues', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-schema-evolution', title: 'Schema Evolution', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-internals', title: 'Kafka Internals', priority: 'tier2', months: [6, 7], tags: ['kafka'] },
      { id: 'c11-rebalancing', title: 'Consumer Rebalancing', priority: 'tier2', months: [6, 7], tags: ['kafka'] },
      { id: 'c11-outbox', title: 'Outbox Pattern', priority: 'tier2', months: [6, 7], tags: ['kafka'], related: ['d4-distributed-transactions'] },
      { id: 'c11-saga', title: 'Saga Pattern', priority: 'tier2', months: [6, 7], tags: ['kafka'], related: ['d4-saga'] },
    ],
  },
  {
    id: 'C12',
    track: 'C',
    title: 'Backend Reliability',
    order: 12,
    defaultKind: 'theory',
    defaultDepth: 'deep',
    topics: [
      { id: 'c12-timeouts', title: 'Timeouts', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
      { id: 'c12-retries', title: 'Retries', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
      { id: 'c12-exponential-backoff', title: 'Exponential Backoff', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
      { id: 'c12-idempotency', title: 'Idempotency', priority: 'tier1', months: [5, 6], tags: ['reliability'], related: ['c11-idempotent-consumers', 'd4-idempotency'], capstone: 'Critical for payment and booking retries without double charges.' },
      { id: 'c12-rate-limiting', title: 'Rate Limiting', priority: 'tier1', months: [5, 6], tags: ['reliability'], related: ['d10-rate-limiter'] },
      { id: 'c12-circuit-breakers', title: 'Circuit Breakers', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
      { id: 'c12-graceful-degradation', title: 'Graceful Degradation', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
      { id: 'c12-health-checks', title: 'Health Checks', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
      { id: 'c12-bulkheads', title: 'Bulkheads', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
      { id: 'c12-backpressure', title: 'Backpressure', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
      { id: 'c12-eventual-consistency', title: 'Eventual Consistency', priority: 'tier1', months: [5, 6], tags: ['reliability'], related: ['d4-eventual-consistency'] },
      { id: 'c12-failure-recovery', title: 'Failure Recovery', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
    ],
  },
  {
    id: 'C13',
    track: 'C',
    title: 'Testing',
    order: 13,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'c13-unit-testing', title: 'Unit Testing', priority: 'tier1', months: [3, 4], tags: ['testing'] },
      { id: 'c13-junit', title: 'JUnit', priority: 'tier1', months: [3, 4], tags: ['testing'] },
      { id: 'c13-mockito', title: 'Mockito', priority: 'tier1', months: [3, 4], tags: ['testing'] },
      { id: 'c13-integration-testing', title: 'Integration Testing', priority: 'tier1', months: [3, 4], tags: ['testing'] },
      { id: 'c13-api-testing', title: 'API Testing', priority: 'tier1', months: [3, 4], tags: ['testing'] },
      { id: 'c13-database-testing', title: 'Database Testing', priority: 'tier1', months: [3, 4], tags: ['testing'] },
      { id: 'c13-testcontainers', title: 'Testcontainers', priority: 'tier2', months: [5, 6], tags: ['testing'] },
      { id: 'c13-contract-testing', title: 'Contract Testing', priority: 'tier2', months: [5, 6], tags: ['testing'] },
      { id: 'c13-load-testing', title: 'Load Testing', priority: 'tier2', months: [7, 8], tags: ['testing'] },
    ],
  },
  {
    id: 'C14',
    track: 'C',
    title: 'Docker / DevOps',
    order: 14,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'c14-linux', title: 'Linux Fundamentals', priority: 'tier1', months: [7, 8], tags: ['devops'] },
      { id: 'c14-processes', title: 'Processes', priority: 'tier1', months: [7, 8], tags: ['devops'] },
      { id: 'c14-permissions', title: 'Files/Permissions', priority: 'tier1', months: [7, 8], tags: ['devops'] },
      { id: 'c14-env-vars', title: 'Environment Variables', priority: 'tier1', months: [7, 8], tags: ['devops'] },
      { id: 'c14-docker-images', title: 'Docker Images', priority: 'tier1', months: [7, 8], tags: ['docker'] },
      { id: 'c14-containers', title: 'Containers', priority: 'tier1', months: [7, 8], tags: ['docker'] },
      { id: 'c14-dockerfile', title: 'Dockerfile', priority: 'tier1', months: [7, 8], tags: ['docker'] },
      { id: 'c14-compose', title: 'Docker Compose', priority: 'tier1', months: [7, 8], tags: ['docker'] },
      { id: 'c14-networking', title: 'Docker Networking', priority: 'tier1', months: [7, 8], tags: ['docker'] },
      { id: 'c14-volumes', title: 'Volumes', priority: 'tier1', months: [7, 8], tags: ['docker'] },
      { id: 'c14-multi-stage', title: 'Multi-stage Builds', priority: 'tier1', months: [7, 8], tags: ['docker'] },
      { id: 'c14-cicd', title: 'CI/CD Concepts', priority: 'tier1', months: [7, 8], tags: ['devops'] },
      { id: 'c14-github-actions', title: 'GitHub Actions / Jenkins', priority: 'tier2', months: [7, 8], tags: ['devops'] },
      { id: 'c14-kubernetes', title: 'Kubernetes', priority: 'tier3', months: [10, 12], tags: ['devops'] },
    ],
  },
  {
    id: 'C15',
    track: 'C',
    title: 'AWS / Cloud',
    order: 15,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'c15-ec2', title: 'EC2', priority: 'tier1', months: [7, 8], tags: ['aws'] },
      { id: 'c15-s3', title: 'S3', priority: 'tier1', months: [7, 8], tags: ['aws'] },
      { id: 'c15-rds', title: 'RDS', priority: 'tier1', months: [7, 8], tags: ['aws'] },
      { id: 'c15-vpc', title: 'VPC Fundamentals', priority: 'tier1', months: [7, 8], tags: ['aws'] },
      { id: 'c15-iam', title: 'IAM', priority: 'tier1', months: [7, 8], tags: ['aws'] },
      { id: 'c15-load-balancers', title: 'Load Balancers (AWS)', priority: 'tier1', months: [7, 8], tags: ['aws'] },
      { id: 'c15-auto-scaling', title: 'Auto Scaling', priority: 'tier1', months: [7, 8], tags: ['aws'] },
      { id: 'c15-cloudwatch', title: 'CloudWatch', priority: 'tier1', months: [7, 8], tags: ['aws'] },
      { id: 'c15-ecs', title: 'ECS', priority: 'tier2', months: [8, 9], tags: ['aws'] },
      { id: 'c15-lambda', title: 'Lambda', priority: 'tier2', months: [8, 9], tags: ['aws'] },
      { id: 'c15-sqs', title: 'SQS', priority: 'tier2', months: [8, 9], tags: ['aws'] },
      { id: 'c15-sns', title: 'SNS', priority: 'tier2', months: [8, 9], tags: ['aws'] },
      { id: 'c15-route53', title: 'Route 53', priority: 'tier2', months: [8, 9], tags: ['aws'] },
      { id: 'c15-cloudfront', title: 'CloudFront', priority: 'tier2', months: [8, 9], tags: ['aws'] },
      { id: 'c15-secrets-manager', title: 'Secrets Manager', priority: 'tier2', months: [8, 9], tags: ['aws'] },
      { id: 'c15-eks', title: 'EKS', priority: 'tier3', months: [10, 12], tags: ['aws'] },
    ],
  },
  {
    id: 'C16',
    track: 'C',
    title: 'Observability',
    order: 16,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'c16-structured-logging', title: 'Structured Logging', priority: 'tier1', months: [7, 8], tags: ['observability'] },
      { id: 'c16-metrics', title: 'Metrics', priority: 'tier1', months: [7, 8], tags: ['observability'] },
      { id: 'c16-tracing', title: 'Distributed Tracing', priority: 'tier1', months: [7, 8], tags: ['observability'] },
      { id: 'c16-correlation-ids', title: 'Correlation IDs', priority: 'tier1', months: [7, 8], tags: ['observability'] },
      { id: 'c16-health-metrics', title: 'Health Metrics', priority: 'tier1', months: [7, 8], tags: ['observability'] },
      { id: 'c16-latency-percentiles', title: 'Latency Percentiles', priority: 'tier1', months: [7, 8], tags: ['observability'] },
      { id: 'c16-error-rates', title: 'Error Rates', priority: 'tier1', months: [7, 8], tags: ['observability'] },
      { id: 'c16-throughput', title: 'Throughput', priority: 'tier1', months: [7, 8], tags: ['observability'] },
      { id: 'c16-otel', title: 'OpenTelemetry Concepts', priority: 'tier1', months: [7, 8], tags: ['observability'] },
      { id: 'c16-prometheus', title: 'Prometheus', priority: 'tier2', months: [8, 9], tags: ['observability'] },
      { id: 'c16-grafana', title: 'Grafana', priority: 'tier2', months: [8, 9], tags: ['observability'] },
    ],
  },
]
