import type { Priority } from '@/domain/types'
import type { SectionSeed, TopicSeed } from './build'

const REACT = ['react'] as const
const M56 = [5, 6]
const M78 = [7, 8]
const M910 = [9, 10]

function item(
  id: string,
  title: string,
  priority: Priority = 'tier1',
  extra: Partial<TopicSeed> = {},
): TopicSeed {
  const { tags, executionPriority, ...rest } = extra
  return {
    id,
    title,
    priority,
    months: priority === 'tier1' ? M56 : priority === 'tier2' ? M78 : M910,
    tags: [...REACT, ...(tags ?? [])],
    executionPriority:
      executionPriority ?? (priority === 'tier1' ? 'p0' : priority === 'tier2' ? 'p1' : 'later'),
    ...rest,
  }
}

function nest(
  parent: string,
  id: string,
  title: string,
  priority: Priority = 'tier1',
  extra: Partial<TopicSeed> = {},
): TopicSeed {
  return item(id, title, priority, {
    ...extra,
    curriculumLevel: 'nested-concept',
    parentTopicId: parent,
  })
}

function section(id: string, title: string, order: number, topics: TopicSeed[]): SectionSeed {
  return {
    id,
    track: 'B',
    title,
    order,
    defaultKind: 'theory',
    defaultDepth: 'deep',
    topics,
  }
}

/** B4.1–B4.24 — React beginner → modern production/interview depth. */
export const TRACK_B_REACT_SECTIONS: SectionSeed[] = [
  section('B4.1', 'React Foundations', 116, [
    item('b4-component-model', 'React Component Model'),
    nest('b4-component-model', 'b4-what-is-react', 'What React Is & Problems It Solves'),
    nest('b4-component-model', 'b4-declarative-vs-imperative', 'Declarative vs Imperative UI'),
    nest('b4-component-model', 'b4-component-architecture', 'Component-Based Architecture'),
    nest('b4-component-model', 'b4-one-way-data-flow', 'One-Way Data Flow'),
    item('b4-react-dom', 'React vs ReactDOM'),
    nest('b4-react-dom', 'b4-react-root', 'createRoot & Application Root'),
    nest('b4-react-dom', 'b4-react-app-structure', 'React Application Structure'),
    item('b4-component-types', 'Function & Class Components'),
    nest('b4-component-types', 'b4-function-components', 'Function Components'),
    nest('b4-component-types', 'b4-class-components-foundations', 'Class Components — Legacy Understanding', 'tier2'),
    nest('b4-component-types', 'b4-function-vs-class', 'Function vs Class Components'),
    item('b4-react-values', 'React Node, Element & Component'),
    nest('b4-react-values', 'b4-react-node', 'React Node'),
    nest('b4-react-values', 'b4-react-element', 'React Element'),
    nest('b4-react-values', 'b4-react-component', 'React Component'),
    item('b4-jsx', 'JSX'),
    nest('b4-jsx', 'b4-jsx-expressions', 'JSX Expressions'),
    nest('b4-jsx', 'b4-jsx-attributes', 'JSX Attributes'),
    nest('b4-jsx', 'b4-jsx-children', 'JSX Children'),
    nest('b4-jsx', 'b4-jsx-vs-html', 'JSX vs HTML'),
    nest('b4-jsx', 'b4-jsx-transformation', 'JSX Transformation & Automatic Runtime'),
    nest('b4-jsx', 'b4-create-element', 'createElement'),
    item('b4-fragments', 'Fragments'),
    nest('b4-fragments', 'b4-react-fragment', 'React.Fragment & Keyed Fragments'),
    item('b4-composition', 'Component Composition'),
    nest('b4-composition', 'b4-children-prop', 'children'),
    nest('b4-composition', 'b4-components-as-props', 'Passing Components as Props'),
  ]),

  section('B4.2', 'Props, State & Data Flow', 117, [
    item('b4-props', 'Props'),
    nest('b4-props', 'b4-props-destructuring', 'Props Destructuring'),
    nest('b4-props', 'b4-prop-default-values', 'Default Prop Values'),
    nest('b4-props', 'b4-props-immutability', 'Props Immutability'),
    item('b4-state', 'State'),
    nest('b4-state', 'b4-props-vs-state', 'Props vs State'),
    nest('b4-state', 'b4-initial-state', 'Initial State'),
    nest('b4-state', 'b4-updating-state', 'Updating State'),
    nest('b4-state', 'b4-functional-state-updates', 'Functional / Updater State Updates'),
    nest('b4-state', 'b4-state-update-batching', 'State Update Batching'),
    nest('b4-state', 'b4-scheduled-state-updates', 'Scheduled State Updates'),
    nest('b4-state', 'b4-state-snapshots', 'State as a Snapshot'),
    item('b4-state-immutability', 'State Immutability'),
    nest('b4-state-immutability', 'b4-update-state-objects', 'Updating Objects in State'),
    nest('b4-state-immutability', 'b4-update-state-arrays', 'Updating Arrays in State'),
    item('b4-derived-state', 'Derived & Redundant State'),
    nest('b4-derived-state', 'b4-computed-state', 'Computed State'),
    nest('b4-derived-state', 'b4-avoid-redundant-state', 'Avoiding Redundant State'),
    item('b4-state-placement', 'State Placement & Ownership'),
    nest('b4-state-placement', 'b4-lifting-state', 'Lifting State Up'),
    nest('b4-state-placement', 'b4-sharing-state', 'Sharing State Between Components'),
    nest('b4-state-placement', 'b4-state-colocation', 'State Colocation'),
    nest('b4-state-placement', 'b4-single-source-truth', 'Single Source of Truth'),
    nest('b4-state-placement', 'b4-prop-drilling', 'Prop Drilling'),
    item('b4-component-communication', 'Component Communication'),
    nest('b4-component-communication', 'b4-parent-child-data', 'Parent → Child via Props'),
    nest('b4-component-communication', 'b4-child-parent-callbacks', 'Child → Parent via Callbacks'),
    nest('b4-component-communication', 'b4-sibling-communication', 'Sibling Communication'),
    item('b4-controlled', 'Controlled Components'),
    nest('b4-controlled', 'b4-uncontrolled', 'Uncontrolled Components'),
    item('b4-state-identity', 'Preserving & Resetting State'),
    nest('b4-state-identity', 'b4-preserving-state', 'Preserving State'),
    nest('b4-state-identity', 'b4-resetting-state', 'Resetting State'),
    nest('b4-state-identity', 'b4-keys-state-reset', 'How Keys Affect Component State'),
  ]),

  section('B4.3', 'Rendering & Reconciliation', 118, [
    item('b4-rendering-lifecycle', 'Rendering Lifecycle'),
    nest('b4-rendering-lifecycle', 'b4-render-vs-rerender', 'Render vs Re-render'),
    nest('b4-rendering-lifecycle', 'b4-render-triggers', 'What Causes a Component to Render'),
    nest('b4-rendering-lifecycle', 'b4-parent-child-rendering', 'Parent / Child Rendering Behavior'),
    nest('b4-rendering-lifecycle', 'b4-render-phase', 'Render Phase'),
    nest('b4-rendering-lifecycle', 'b4-commit-phase', 'Commit Phase'),
    item('b4-reconciliation', 'Reconciliation'),
    nest('b4-reconciliation', 'b4-diffing', 'Diffing Heuristics'),
    item('b4-virtual-dom', 'Virtual DOM'),
    nest('b4-virtual-dom', 'b4-virtual-dom-limitations', 'Virtual DOM Limitations'),
    item('b4-fiber', 'React Fiber'),
    nest('b4-fiber', 'b4-fiber-tree', 'Fiber Tree Concepts'),
    nest('b4-fiber', 'b4-fiber-work-loop', 'Fiber Work Loop'),
    item('b4-keys', 'Keys & Component Identity'),
    nest('b4-keys', 'b4-stable-keys', 'Stable Keys'),
    nest('b4-keys', 'b4-index-key-danger', 'Why Array-Index Keys Are Dangerous'),
    nest('b4-keys', 'b4-component-identity', 'Component Identity'),
    item('b4-rendering-patterns', 'Rendering Patterns'),
    nest('b4-rendering-patterns', 'b4-conditional-rendering', 'Conditional Rendering'),
    nest('b4-rendering-patterns', 'b4-rendering-lists', 'Rendering Lists'),
    nest('b4-rendering-patterns', 'b4-nested-lists', 'Nested Lists'),
    nest('b4-rendering-patterns', 'b4-rendering-null', 'Rendering null'),
    item('b4-pure-rendering', 'Pure Rendering'),
    nest('b4-pure-rendering', 'b4-render-side-effects', 'Side Effects During Render'),
    item('b4-strict-mode', 'Strict Mode'),
    nest('b4-strict-mode', 'b4-strict-mode-double-run', 'Development Double Render / Effect Cycle'),
    item('b4-modern-rendering', 'Modern React Rendering Model'),
  ]),

  section('B4.4', 'Events', 119, [
    item('b4-react-events', 'React Event Handling'),
    nest('b4-react-events', 'b4-event-handlers', 'Event Handlers'),
    nest('b4-react-events', 'b4-passing-handlers', 'Passing Handlers as Props'),
    item('b4-synthetic-events', 'Synthetic Events'),
    nest('b4-synthetic-events', 'b4-native-vs-synthetic-events', 'Native vs Synthetic Events'),
    item('b4-event-propagation', 'Event Propagation'),
    nest('b4-event-propagation', 'b4-event-bubbling', 'Event Bubbling'),
    nest('b4-event-propagation', 'b4-event-capturing', 'Event Capturing'),
    nest('b4-event-propagation', 'b4-prevent-default', 'preventDefault'),
    nest('b4-event-propagation', 'b4-stop-propagation', 'stopPropagation'),
    nest('b4-event-propagation', 'b4-portal-events', 'Events Through Portals'),
  ]),

  section('B4.5', 'Forms', 120, [
    item('b4-forms', 'Forms in React'),
    nest('b4-forms', 'b4-controlled-forms', 'Controlled Forms'),
    nest('b4-forms', 'b4-uncontrolled-forms', 'Uncontrolled Forms'),
    item('b4-form-controls', 'Form Controls'),
    nest('b4-form-controls', 'b4-text-inputs', 'Text Inputs'),
    nest('b4-form-controls', 'b4-textareas', 'Textareas'),
    nest('b4-form-controls', 'b4-selects', 'Selects'),
    nest('b4-form-controls', 'b4-checkboxes', 'Checkboxes'),
    nest('b4-form-controls', 'b4-radio-buttons', 'Radio Buttons'),
    nest('b4-form-controls', 'b4-multiple-inputs', 'Multiple Inputs'),
    item('b4-form-submission', 'Form Submission'),
    nest('b4-form-submission', 'b4-form-validation', 'Form Validation Concepts'),
    nest('b4-form-submission', 'b4-form-async-states', 'Pending / Error / Success States'),
    item('b4-form-state-architecture', 'Form State Architecture'),
    nest('b4-form-state-architecture', 'b4-form-libraries', 'Form Libraries — Concepts', 'tier2'),
  ]),

  section('B4.6', 'Hooks Fundamentals', 121, [
    item('b4-hooks-model', 'Hooks Mental Model'),
    nest('b4-hooks-model', 'b4-why-hooks', 'Why Hooks Exist'),
    nest('b4-hooks-model', 'b4-rules-of-hooks', 'Rules of Hooks'),
    nest('b4-hooks-model', 'b4-hook-call-order', 'Hook Call Ordering'),
    item('b4-usestate', 'useState'),
    nest('b4-usestate', 'b4-lazy-state-initialization', 'Lazy State Initialization'),
    nest('b4-usestate', 'b4-usestate-functional-updates', 'Functional State Updates'),
    item('b4-useeffect', 'useEffect'),
    nest('b4-useeffect', 'b4-effect-lifecycle', 'Effect Lifecycle'),
    nest('b4-useeffect', 'b4-effect-dependencies', 'Dependency Arrays', 'tier1', {
      prereqs: ['b4-useeffect'],
    }),
    nest('b4-useeffect', 'b4-effect-cleanup', 'Effect Cleanup'),
    nest('b4-useeffect', 'b4-stale-closures', 'Stale Closures'),
    nest('b4-useeffect', 'b4-infinite-effect-loops', 'Infinite Effect Loops'),
    nest('b4-useeffect', 'b4-effect-race-conditions', 'Race Conditions in Effects'),
    nest('b4-useeffect', 'b4-when-effects-needed', 'When Effects Are Needed'),
    nest('b4-useeffect', 'b4-when-not-effects', 'When Not to Use Effects'),
    nest('b4-useeffect', 'b4-events-vs-effects', 'Separating Events from Effects'),
    item('b4-useref', 'useRef'),
    nest('b4-useref', 'b4-ref-vs-state', 'Ref vs State'),
    nest('b4-useref', 'b4-dom-refs-hook', 'DOM Refs'),
    nest('b4-useref', 'b4-mutable-ref-values', 'Mutable Values with Refs'),
    item('b4-usecontext', 'useContext'),
    item('b4-usereducer', 'useReducer'),
    nest('b4-usereducer', 'b4-reducer-patterns', 'Reducer Patterns'),
    item('b4-usememo', 'useMemo'),
    item('b4-usecallback', 'useCallback'),
    item('b4-uselayouteffect', 'useLayoutEffect'),
    item('b4-useimperativehandle', 'useImperativeHandle'),
    item('b4-useid', 'useId'),
    item('b4-usedebugvalue', 'useDebugValue', 'tier2'),
    item('b4-custom-hooks', 'Custom Hooks'),
    nest('b4-custom-hooks', 'b4-designing-custom-hooks', 'Designing Good Custom Hooks'),
    nest('b4-custom-hooks', 'b4-hook-composition', 'Hook Composition'),
  ]),

  section('B4.7', 'Context', 122, [
    item('b4-context-api', 'Context API'),
    nest('b4-context-api', 'b4-create-context', 'createContext'),
    nest('b4-context-api', 'b4-context-provider', 'Context Provider'),
    nest('b4-context-api', 'b4-consuming-context', 'Consuming Context'),
    nest('b4-context-api', 'b4-context-vs-props', 'Context vs Props'),
    nest('b4-context-api', 'b4-context-vs-state-management', 'Context vs State Management'),
    item('b4-context-performance', 'Context Performance'),
    nest('b4-context-performance', 'b4-context-rerenders', 'Context Re-render Behavior'),
    nest('b4-context-performance', 'b4-splitting-contexts', 'Splitting Contexts'),
    nest('b4-context-performance', 'b4-memo-context-values', 'Memoizing Context Values'),
    nest('b4-context-performance', 'b4-context-pitfalls', 'Context Pitfalls'),
  ]),

  section('B4.8', 'Refs & Imperative React', 123, [
    item('b4-refs', 'Refs'),
    nest('b4-refs', 'b4-ref-lifecycle', 'Ref Lifecycle'),
    nest('b4-refs', 'b4-callback-refs', 'Callback Refs'),
    nest('b4-refs', 'b4-create-ref', 'createRef', 'tier2'),
    nest('b4-refs', 'b4-useref-vs-createref', 'useRef vs createRef'),
    item('b4-ref-forwarding', 'Ref Forwarding'),
    nest('b4-ref-forwarding', 'b4-forwardref', 'forwardRef — Legacy / Pre-React-19', 'tier2'),
    nest('b4-ref-forwarding', 'b4-ref-as-prop', 'React 19 ref as a Prop'),
    item('b4-imperative-apis', 'Imperative Component APIs'),
    nest('b4-imperative-apis', 'b4-appropriate-imperative-apis', 'When Imperative APIs Are Appropriate'),
    nest('b4-imperative-apis', 'b4-measuring-dom', 'Measuring DOM Nodes'),
    nest('b4-imperative-apis', 'b4-focus-management', 'Focus Management'),
  ]),

  section('B4.9', 'Portals & Advanced Component Patterns', 124, [
    item('b4-portals', 'React Portals'),
    nest('b4-portals', 'b4-portal-event-propagation', 'Portal Event Propagation'),
    item('b4-higher-order-components', 'Higher-Order Components', 'tier2'),
    item('b4-render-props', 'Render Props', 'tier2'),
    item('b4-compound-components', 'Compound Components'),
    item('b4-headless-components', 'Headless Components'),
    item('b4-component-patterns', 'Reusable Component Patterns'),
    nest('b4-component-patterns', 'b4-controlled-component-pattern', 'Controlled Component Pattern'),
    nest('b4-component-patterns', 'b4-provider-pattern', 'Provider Pattern'),
    nest('b4-component-patterns', 'b4-container-presentational', 'Container / Presentational Pattern', 'tier2'),
    nest('b4-component-patterns', 'b4-composition-over-inheritance', 'Composition over Inheritance'),
    nest('b4-component-patterns', 'b4-reusable-api-design', 'Reusable Component API Design'),
  ]),

  section('B4.10', 'Error Handling', 125, [
    item('b4-error-boundaries', 'Error Boundaries'),
    nest('b4-error-boundaries', 'b4-error-boundary-catches', 'What Error Boundaries Catch'),
    nest('b4-error-boundaries', 'b4-error-boundary-misses', 'What Error Boundaries Do Not Catch'),
    nest('b4-error-boundaries', 'b4-error-fallback-ui', 'Error Fallback UI'),
    nest('b4-error-boundaries', 'b4-error-recovery', 'Error Recovery'),
    nest('b4-error-boundaries', 'b4-error-reporting', 'Error Reporting & Logging'),
    item('b4-async-error-handling', 'Async & Event-Handler Error Handling'),
    nest('b4-async-error-handling', 'b4-suspense-errors', 'Errors with Suspense'),
  ]),

  section('B4.11', 'Suspense & Async UI', 126, [
    item('b4-suspense', 'Suspense'),
    nest('b4-suspense', 'b4-suspense-boundaries', 'Suspense Boundaries'),
    nest('b4-suspense', 'b4-suspense-fallback', 'Fallback UI'),
    nest('b4-suspense', 'b4-nested-suspense', 'Nested Suspense'),
    nest('b4-suspense', 'b4-suspense-lazy', 'Suspense + Lazy Loading'),
    nest('b4-suspense', 'b4-suspense-data', 'Suspense + Data'),
    item('b4-async-ui-states', 'Async UI States'),
    nest('b4-async-ui-states', 'b4-loading-states', 'Loading States'),
    nest('b4-async-ui-states', 'b4-error-states', 'Error States'),
    nest('b4-async-ui-states', 'b4-streaming-concepts', 'Streaming Concepts'),
    nest('b4-async-ui-states', 'b4-async-rendering-model', 'Async Rendering Mental Model'),
  ]),

  section('B4.12', 'Performance Engineering', 127, [
    item('b4-performance-model', 'React Performance Mental Model'),
    nest('b4-performance-model', 'b4-why-rerenders', 'Why Components Re-render'),
    nest('b4-performance-model', 'b4-unnecessary-renders', 'Detecting Unnecessary Renders'),
    item('b4-react-devtools', 'React DevTools'),
    item('b4-profiler', 'React Profiler'),
    nest('b4-profiler', 'b4-profiling-render-performance', 'Profiling Render Performance'),
    item('b4-memoization-perf', 'Memoization for Performance'),
    nest('b4-memoization-perf', 'b4-react-memo', 'React.memo'),
    nest('b4-memoization-perf', 'b4-shallow-comparison', 'Shallow Comparison'),
    nest('b4-memoization-perf', 'b4-referential-equality', 'Referential Equality'),
    nest('b4-memoization-perf', 'b4-when-memoization-helps', 'When Memoization Helps'),
    nest('b4-memoization-perf', 'b4-when-not-memoize', 'When Memoization Hurts'),
    item('b4-virtualization', 'List Virtualization'),
    nest('b4-virtualization', 'b4-pagination-rendering', 'Pagination'),
    nest('b4-virtualization', 'b4-infinite-scrolling-rendering', 'Infinite Scrolling'),
    item('b4-code-splitting', 'Code Splitting'),
    nest('b4-code-splitting', 'b4-lazy-loading', 'React.lazy & Lazy Loading'),
    nest('b4-code-splitting', 'b4-dynamic-imports', 'Dynamic Imports'),
    nest('b4-code-splitting', 'b4-bundle-splitting', 'Bundle Splitting'),
    item('b4-bundle-optimization', 'Bundle-Size Optimization'),
    nest('b4-bundle-optimization', 'b4-resource-optimization', 'Image & Resource Optimization Concepts'),
    item('b4-network-waterfalls', 'Network Waterfalls'),
    nest('b4-network-waterfalls', 'b4-avoid-request-waterfalls', 'Avoiding Request Waterfalls'),
    item('b4-performance-measurement', 'Performance Measurement'),
    item('b4-react-compiler-performance', 'React Compiler & Automatic Memoization'),
  ]),

  section('B4.13', 'Concurrent React', 128, [
    item('b4-concurrent-rendering', 'Concurrent Rendering'),
    nest('b4-concurrent-rendering', 'b4-interruptible-rendering', 'Interruptible Rendering'),
    nest('b4-concurrent-rendering', 'b4-update-priorities', 'Update Priorities'),
    nest('b4-concurrent-rendering', 'b4-urgent-vs-nonurgent', 'Urgent vs Non-Urgent Updates'),
    item('b4-transitions', 'Transitions'),
    nest('b4-transitions', 'b4-start-transition', 'startTransition'),
    nest('b4-transitions', 'b4-use-transition', 'useTransition'),
    nest('b4-transitions', 'b4-transition-pending', 'Pending Transition State'),
    item('b4-use-deferred-value', 'useDeferredValue'),
    nest('b4-use-deferred-value', 'b4-transition-vs-deferred', 'useTransition vs useDeferredValue'),
    item('b4-concurrent-suspense', 'Suspense with Concurrent Rendering'),
  ]),

  section('B4.14', 'Data Fetching & Server State', 129, [
    item('b4-data-fetching', 'Data-Fetching Patterns'),
    nest('b4-data-fetching', 'b4-fetching-in-effects', 'Fetching in Effects'),
    nest('b4-data-fetching', 'b4-effect-fetching-pitfalls', 'Effect-Based Fetching Pitfalls'),
    nest('b4-data-fetching', 'b4-data-loading-error-states', 'Loading / Error / Data States'),
    nest('b4-data-fetching', 'b4-request-cancellation', 'Request Cancellation'),
    nest('b4-data-fetching', 'b4-request-race-conditions', 'Request Race Conditions'),
    item('b4-server-cache', 'Server Cache'),
    nest('b4-server-cache', 'b4-request-deduplication', 'Request Deduplication'),
    nest('b4-server-cache', 'b4-data-caching', 'Caching'),
    nest('b4-server-cache', 'b4-stale-data', 'Stale Data'),
    nest('b4-server-cache', 'b4-revalidation', 'Revalidation'),
    nest('b4-server-cache', 'b4-optimistic-updates', 'Optimistic Updates'),
    nest('b4-server-cache', 'b4-infinite-queries', 'Infinite Queries'),
    item('b4-server-vs-client-state', 'Server vs Client State'),
    item('b4-query-libraries', 'Server-State Libraries'),
    nest('b4-query-libraries', 'b4-tanstack-query', 'TanStack Query Concepts'),
    nest('b4-query-libraries', 'b4-swr', 'SWR Concepts', 'tier2'),
    nest('b4-query-libraries', 'b4-fetching-architecture', 'Choosing a Fetching Architecture'),
  ]),

  section('B4.15', 'State Management', 130, [
    item('b4-state-kinds', 'Kinds of Application State'),
    nest('b4-state-kinds', 'b4-local-state', 'Local State'),
    nest('b4-state-kinds', 'b4-lifted-state', 'Lifted State'),
    nest('b4-state-kinds', 'b4-shared-state', 'Shared State'),
    nest('b4-state-kinds', 'b4-global-state', 'Global State'),
    nest('b4-state-kinds', 'b4-url-state', 'URL State'),
    nest('b4-state-kinds', 'b4-form-state', 'Form State'),
    item('b4-state-management-tradeoffs', 'State-Management Trade-offs'),
    nest('b4-state-management-tradeoffs', 'b4-context-reducer', 'Context + Reducer'),
    nest('b4-state-management-tradeoffs', 'b4-context-redux-zustand', 'Context vs Redux vs Zustand'),
    nest('b4-state-management-tradeoffs', 'b4-avoid-global-state', 'Avoiding Unnecessary Global State'),
    item('b4-redux', 'Redux Fundamentals'),
    nest('b4-redux', 'b4-redux-architecture', 'Redux Architecture'),
    nest('b4-redux', 'b4-redux-actions', 'Actions'),
    nest('b4-redux', 'b4-redux-reducers', 'Reducers'),
    nest('b4-redux', 'b4-redux-store', 'Store & Dispatch'),
    nest('b4-redux', 'b4-redux-selectors', 'Selectors'),
    item('b4-redux-toolkit', 'Redux Toolkit'),
    nest('b4-redux-toolkit', 'b4-redux-slices', 'Slices'),
    nest('b4-redux-toolkit', 'b4-configure-store', 'configureStore'),
    nest('b4-redux-toolkit', 'b4-use-selector', 'useSelector'),
    nest('b4-redux-toolkit', 'b4-use-dispatch', 'useDispatch'),
    nest('b4-redux-toolkit', 'b4-create-async-thunk', 'createAsyncThunk', 'tier2'),
    nest('b4-redux-toolkit', 'b4-redux-middleware', 'Middleware Concepts', 'tier2'),
    nest('b4-redux-toolkit', 'b4-redux-devtools', 'Redux DevTools'),
    item('b4-zustand', 'Zustand Concepts', 'tier2'),
  ]),

  section('B4.16', 'React Router', 131, [
    item('b4-react-router', 'React Router'),
    nest('b4-react-router', 'b4-spa-routing', 'SPA Routing'),
    nest('b4-react-router', 'b4-client-vs-server-routing', 'Client vs Server Routing'),
    item('b4-router-types', 'Router Types'),
    nest('b4-router-types', 'b4-browser-router', 'BrowserRouter'),
    nest('b4-router-types', 'b4-hash-router', 'HashRouter', 'tier2'),
    nest('b4-router-types', 'b4-memory-router', 'MemoryRouter', 'tier2'),
    item('b4-route-configuration', 'Routes & Route Configuration'),
    nest('b4-route-configuration', 'b4-routes-component', 'Routes'),
    nest('b4-route-configuration', 'b4-route-component', 'Route'),
    nest('b4-route-configuration', 'b4-nested-routes', 'Nested Routes & Outlet'),
    nest('b4-route-configuration', 'b4-dynamic-routes', 'Dynamic Routes'),
    nest('b4-route-configuration', 'b4-catch-all-route', '404 / Catch-All Routes'),
    item('b4-router-navigation', 'Router Navigation'),
    nest('b4-router-navigation', 'b4-link', 'Link'),
    nest('b4-router-navigation', 'b4-nav-link', 'NavLink'),
    nest('b4-router-navigation', 'b4-use-navigate', 'useNavigate'),
    nest('b4-router-navigation', 'b4-use-location', 'useLocation'),
    nest('b4-router-navigation', 'b4-programmatic-navigation', 'Programmatic Navigation & Redirects'),
    item('b4-router-params', 'Route & Search Parameters'),
    nest('b4-router-params', 'b4-use-params', 'useParams'),
    nest('b4-router-params', 'b4-use-search-params', 'useSearchParams'),
    item('b4-protected-routes', 'Protected Routes'),
    nest('b4-protected-routes', 'b4-auth-routing', 'Authentication & Authorization Routing'),
    item('b4-route-lazy-loading', 'Route-Level Lazy Loading'),
    item('b4-route-architecture', 'Route Architecture'),
  ]),

  section('B4.17', 'React 19 & Modern React', 132, [
    item('b4-react-19', 'React 19 Overview'),
    item('b4-actions', 'Actions'),
    nest('b4-actions', 'b4-async-actions', 'Async Actions'),
    nest('b4-actions', 'b4-use-action-state', 'useActionState'),
    nest('b4-actions', 'b4-use-optimistic', 'useOptimistic'),
    nest('b4-actions', 'b4-use-hook', 'use'),
    nest('b4-actions', 'b4-use-form-status', 'useFormStatus'),
    item('b4-form-actions', 'Function-Based Form Actions'),
    nest('b4-form-actions', 'b4-form-action-prop', 'form action'),
    nest('b4-form-actions', 'b4-formaction-prop', 'formAction'),
    nest('b4-form-actions', 'b4-optimistic-ui', 'Optimistic UI'),
    item('b4-react-19-platform', 'React 19 Platform Changes'),
    nest('b4-react-19-platform', 'b4-document-metadata', 'Document Metadata Support'),
    nest('b4-react-19-platform', 'b4-resource-handling', 'Stylesheet & Resource Handling'),
    item('b4-react-compiler', 'React Compiler'),
    nest('b4-react-compiler', 'b4-automatic-memoization', 'Automatic Memoization'),
    item('b4-modern-react-rules', 'Modern React Rules'),
    nest('b4-modern-react-rules', 'b4-legacy-modern-replacements', 'Legacy APIs vs Modern Replacements'),
  ]),

  section('B4.18', 'Server Rendering & Server Components', 133, [
    item('b4-csr', 'Client-Side Rendering (CSR)'),
    item('b4-ssr', 'Server-Side Rendering (SSR)'),
    item('b4-ssg', 'Static Site Generation (SSG)'),
    item('b4-hydration', 'Hydration'),
    nest('b4-hydration', 'b4-hydration-mismatches', 'Hydration Mismatches'),
    nest('b4-hydration', 'b4-streaming-ssr', 'Streaming SSR'),
    nest('b4-hydration', 'b4-selective-hydration', 'Selective / Progressive Hydration'),
    item('b4-server-components', 'React Server Components'),
    nest('b4-server-components', 'b4-client-components', 'Client Components'),
    nest('b4-server-components', 'b4-server-vs-client-components', 'Server vs Client Components'),
    nest('b4-server-components', 'b4-use-client', "'use client'"),
    nest('b4-server-components', 'b4-server-only-code', 'Server-Only Code'),
    nest('b4-server-components', 'b4-server-actions', 'Server Actions Concepts'),
    nest('b4-server-components', 'b4-rsc-serialization', 'RSC Serialization Boundaries'),
    nest('b4-server-components', 'b4-rsc-data-fetching', 'Data Fetching in Server Components'),
    nest('b4-server-components', 'b4-rsc-suspense-streaming', 'Suspense + Streaming'),
    nest('b4-server-components', 'b4-rsc-bundle-size', 'RSC Bundle-Size Implications'),
  ]),

  section('B4.19', 'Next.js Integration', 134, [
    item('b4-nextjs', 'Next.js Architecture', 'tier2', { tags: ['nextjs'] }),
    nest('b4-nextjs', 'b4-why-react-frameworks', 'Why React Frameworks Exist', 'tier2', { tags: ['nextjs'] }),
    nest('b4-nextjs', 'b4-next-app-router', 'App Router Concepts', 'tier2', { tags: ['nextjs'] }),
    nest('b4-nextjs', 'b4-next-layouts-pages', 'Layouts & Pages', 'tier2', { tags: ['nextjs'] }),
    nest('b4-nextjs', 'b4-next-routing', 'Routing & Dynamic Routes', 'tier2', { tags: ['nextjs'] }),
    nest('b4-nextjs', 'b4-next-loading-errors', 'Loading & Error UI', 'tier2', { tags: ['nextjs'] }),
    nest('b4-nextjs', 'b4-next-data-fetching', 'Data Fetching', 'tier2', { tags: ['nextjs'] }),
    nest('b4-nextjs', 'b4-next-cache-revalidation', 'Caching & Revalidation', 'tier2', { tags: ['nextjs'] }),
    nest('b4-nextjs', 'b4-next-server-actions', 'Server Actions', 'tier2', { tags: ['nextjs'] }),
    nest('b4-nextjs', 'b4-next-rendering-strategies', 'SSR / SSG / ISR Strategies', 'tier2', { tags: ['nextjs'] }),
    nest('b4-nextjs', 'b4-next-middleware', 'Middleware Concepts', 'tier2', { tags: ['nextjs'] }),
    nest('b4-nextjs', 'b4-next-auth', 'Authentication Architecture', 'tier2', { tags: ['nextjs'] }),
    nest('b4-nextjs', 'b4-next-deployment', 'Deployment Concepts', 'tier2', { tags: ['nextjs'] }),
  ]),

  section('B4.20', 'React Testing', 135, [
    item('b4-testing-philosophy', 'React Testing Philosophy'),
    nest('b4-testing-philosophy', 'b4-test-levels', 'Unit vs Integration vs E2E'),
    nest('b4-testing-philosophy', 'b4-avoid-implementation-tests', 'Avoiding Implementation-Detail Tests'),
    item('b4-testing-library', 'React Testing Library'),
    nest('b4-testing-library', 'b4-rendering-tests', 'Rendering Components in Tests'),
    nest('b4-testing-library', 'b4-testing-queries', 'Queries'),
    nest('b4-testing-library', 'b4-query-variants', 'getBy / queryBy / findBy'),
    nest('b4-testing-library', 'b4-role-queries', 'Role-Based Queries'),
    nest('b4-testing-library', 'b4-user-event', 'userEvent'),
    nest('b4-testing-library', 'b4-testing-interactions', 'Testing Interactions & Forms'),
    item('b4-async-testing', 'Testing Async UI'),
    nest('b4-async-testing', 'b4-wait-for', 'waitFor'),
    nest('b4-async-testing', 'b4-test-loading-errors', 'Testing Loading & Error States'),
    nest('b4-async-testing', 'b4-mocking-api', 'Mocking API Requests'),
    nest('b4-async-testing', 'b4-msw', 'MSW Concepts'),
    item('b4-testing-integrations', 'Testing React Integrations'),
    nest('b4-testing-integrations', 'b4-testing-context', 'Testing Context'),
    nest('b4-testing-integrations', 'b4-testing-router', 'Testing Router'),
    nest('b4-testing-integrations', 'b4-testing-redux', 'Testing Redux', 'tier2'),
    item('b4-testing-hooks', 'Testing Custom Hooks'),
    nest('b4-testing-hooks', 'b4-render-hook', 'renderHook'),
    nest('b4-testing-hooks', 'b4-act', 'act'),
    item('b4-snapshot-testing', 'Snapshot Testing & Limitations', 'tier2'),
    item('b4-e2e-testing', 'E2E with Playwright / Cypress', 'tier2'),
  ]),

  section('B4.21', 'Accessibility in React', 136, [
    item('b4-react-accessibility', 'React Accessibility'),
    nest('b4-react-accessibility', 'b4-semantic-components', 'Semantic Components'),
    nest('b4-react-accessibility', 'b4-accessible-forms', 'Accessible Forms & Labels'),
    nest('b4-react-accessibility', 'b4-keyboard-interactions', 'Keyboard Interactions'),
    nest('b4-react-accessibility', 'b4-aria-react', 'ARIA in React'),
    nest('b4-react-accessibility', 'b4-accessible-modals', 'Accessible Modals'),
    nest('b4-react-accessibility', 'b4-accessible-widgets', 'Accessible Custom Widgets'),
    nest('b4-react-accessibility', 'b4-useid-accessibility', 'useId for Accessibility'),
    nest('b4-react-accessibility', 'b4-route-accessibility', 'Route-Change Accessibility'),
    nest('b4-react-accessibility', 'b4-accessibility-testing', 'Accessibility Testing Concepts'),
  ]),

  section('B4.22', 'Internationalization', 137, [
    item('b4-react-i18n', 'Internationalization in React', 'tier2'),
    nest('b4-react-i18n', 'b4-i18n-vs-l10n', 'i18n vs l10n', 'tier2'),
    nest('b4-react-i18n', 'b4-translation-architecture', 'Translation Architecture', 'tier2'),
    nest('b4-react-i18n', 'b4-locale-management', 'Locale Management', 'tier2'),
    nest('b4-react-i18n', 'b4-intl-react', 'Intl with React', 'tier2'),
    nest('b4-react-i18n', 'b4-i18n-libraries', 'react-i18next / react-intl Concepts', 'tier2'),
    nest('b4-react-i18n', 'b4-locale-formatting', 'Numbers, Dates & Currency', 'tier2'),
    nest('b4-react-i18n', 'b4-pluralization', 'Pluralization', 'tier2'),
    nest('b4-react-i18n', 'b4-rtl-layouts', 'RTL Layouts', 'tier2'),
    nest('b4-react-i18n', 'b4-lazy-translations', 'Lazy-Loading Translations', 'tier2'),
  ]),

  section('B4.23', 'Legacy React & Existing Codebases', 138, [
    item('b4-legacy-classes', 'Reading Class Components', 'tier2'),
    nest('b4-legacy-classes', 'b4-this-props', 'this.props', 'tier2'),
    nest('b4-legacy-classes', 'b4-this-state', 'this.state & setState', 'tier2'),
    nest('b4-legacy-classes', 'b4-class-constructor', 'constructor', 'tier2'),
    item('b4-class-lifecycle', 'Class Lifecycle Methods', 'tier2'),
    nest('b4-class-lifecycle', 'b4-component-did-mount', 'componentDidMount', 'tier2'),
    nest('b4-class-lifecycle', 'b4-component-did-update', 'componentDidUpdate', 'tier2'),
    nest('b4-class-lifecycle', 'b4-component-will-unmount', 'componentWillUnmount', 'tier2'),
    nest('b4-class-lifecycle', 'b4-should-component-update', 'shouldComponentUpdate', 'tier2'),
    nest('b4-class-lifecycle', 'b4-pure-component', 'PureComponent', 'tier2'),
    nest('b4-class-lifecycle', 'b4-error-lifecycle', 'Error-Boundary Lifecycle Methods', 'tier2'),
    item('b4-legacy-apis', 'Legacy & Deprecated APIs', 'tier3'),
    nest('b4-legacy-apis', 'b4-legacy-context', 'Legacy Context — Awareness', 'tier3'),
    nest('b4-legacy-apis', 'b4-deprecated-lifecycles', 'Deprecated Lifecycle Methods', 'tier3'),
  ]),

  section('B4.24', 'React Architecture & Production Engineering', 139, [
    item('b4-component-boundaries', 'Component Boundaries'),
    nest('b4-component-boundaries', 'b4-feature-organization', 'Feature-Based Organization'),
    nest('b4-component-boundaries', 'b4-container-ui-separation', 'Container / UI Separation'),
    nest('b4-component-boundaries', 'b4-custom-hook-architecture', 'Custom-Hook Architecture'),
    nest('b4-component-boundaries', 'b4-state-ownership', 'State Ownership'),
    nest('b4-component-boundaries', 'b4-dependency-direction', 'Dependency Direction'),
    item('b4-production-ui-architecture', 'Production UI Architecture'),
    nest('b4-production-ui-architecture', 'b4-api-data-layer', 'API & Data Layer'),
    nest('b4-production-ui-architecture', 'b4-error-architecture', 'Error Architecture'),
    nest('b4-production-ui-architecture', 'b4-loading-architecture', 'Loading-State Architecture'),
    nest('b4-production-ui-architecture', 'b4-auth-integration', 'Authentication & Authorization Integration'),
    nest('b4-production-ui-architecture', 'b4-feature-flags', 'Feature Flags'),
    nest('b4-production-ui-architecture', 'b4-environment-config', 'Configuration & Environments'),
    nest('b4-production-ui-architecture', 'b4-design-system-integration', 'Design-System Integration'),
    item('b4-large-react-apps', 'Large-Scale React Application Structure'),
    nest('b4-large-react-apps', 'b4-performance-budgets', 'Performance Budgets'),
    nest('b4-large-react-apps', 'b4-react-observability', 'Observability & Error Monitoring'),
    nest('b4-large-react-apps', 'b4-analytics-integration', 'Analytics Integration'),
    nest('b4-large-react-apps', 'b4-react-maintainability', 'Maintainability & Refactoring'),
    item('b4-react-antipatterns', 'React Anti-Patterns'),
    nest('b4-react-antipatterns', 'b4-direct-state-mutation', 'Direct State Mutation'),
    nest('b4-react-antipatterns', 'b4-effect-misuse', 'Effect Misuse'),
    nest('b4-react-antipatterns', 'b4-bad-keys', 'Bad Keys'),
    nest('b4-react-antipatterns', 'b4-conditional-hooks', 'Conditional Hooks'),
    nest('b4-react-antipatterns', 'b4-excessive-global-state', 'Excessive Global State'),
  ]),
]
