import type { Priority } from '@/domain/types'
import type { TopicSeed, SectionSeed } from './build'

const BR = ['browser'] as const
const M34 = [3, 4]
const M56 = [5, 6]
const M78 = [7, 8]

function item(
  id: string,
  title: string,
  priority: Priority,
  months: number[],
  extra: Partial<TopicSeed> = {},
): TopicSeed {
  const { tags, executionPriority, ...rest } = extra
  return {
    id,
    title,
    priority,
    months,
    tags: [...BR, ...(tags ?? [])],
    executionPriority:
      executionPriority ?? (priority === 'tier1' ? 'p0' : undefined),
    ...rest,
  }
}

function nest(
  parent: string,
  id: string,
  title: string,
  priority: Priority,
  months: number[],
  extra: Partial<TopicSeed> = {},
): TopicSeed {
  return item(id, title, priority, months, {
    ...extra,
    curriculumLevel: 'nested-concept',
    parentTopicId: parent,
  })
}

function section(
  id: string,
  title: string,
  order: number,
  topics: TopicSeed[],
): SectionSeed {
  return {
    id,
    track: 'B',
    title,
    order,
    defaultKind: 'theory',
    defaultDepth: 'deep',
    topics,
  }
}

/** B3.1–B3.37 — Browser fundamentals, beginner → senior interview depth. */
export const TRACK_B_BROWSER_SECTIONS: SectionSeed[] = [
  section('B3.1', 'Browser Architecture', 79, [
    item('b3-browser-overview', 'Browser Architecture Overview', 'tier1', M34, { tags: ['architecture'] }),
    item('b3-browser-processes', 'Browser Processes', 'tier1', M34, { tags: ['architecture'] }),
    nest('b3-browser-processes', 'b3-browser-process', 'Browser Process', 'tier1', M34, { tags: ['architecture'] }),
    nest('b3-browser-processes', 'b3-renderer-process', 'Renderer Process', 'tier1', M34, { tags: ['architecture'] }),
    nest('b3-browser-processes', 'b3-gpu-process', 'GPU Process', 'tier1', M34, { tags: ['architecture'] }),
    nest('b3-browser-processes', 'b3-network-process', 'Network Process', 'tier1', M34, { tags: ['architecture'] }),
    nest('b3-browser-processes', 'b3-utility-process', 'Utility / Plugin Processes', 'tier2', M56, { tags: ['architecture'] }),
    item('b3-browser-threads', 'Browser Threads', 'tier1', M34, { tags: ['architecture'] }),
    nest('b3-browser-threads', 'b3-main-thread', 'Main Thread', 'tier1', M34, { tags: ['architecture'] }),
    nest('b3-browser-threads', 'b3-compositor-thread', 'Compositor Thread', 'tier1', M34, { tags: ['architecture', 'rendering'] }),
    nest('b3-browser-threads', 'b3-raster-threads', 'Raster Threads', 'tier2', M56, { tags: ['architecture', 'rendering'] }),
    nest('b3-browser-threads', 'b3-worker-threads-browser', 'Worker Threads in the Browser', 'tier2', M56, { tags: ['architecture'] }),
    item('b3-url-navigation', 'URL Navigation Lifecycle', 'tier1', M34, { tags: ['navigation'] }),
    nest('b3-url-navigation', 'b3-dns-resolution', 'DNS Resolution', 'tier1', M34, { tags: ['navigation', 'http'] }),
    nest('b3-url-navigation', 'b3-tcp-tls-handshake', 'TCP & TLS Handshake', 'tier1', M34, { tags: ['navigation', 'http'] }),
    nest('b3-url-navigation', 'b3-http-request-response', 'HTTP Request & Response', 'tier1', M34, { tags: ['navigation', 'http'] }),
    nest('b3-url-navigation', 'b3-document-download', 'Document Download & Parsing Start', 'tier1', M34, { tags: ['navigation'] }),
    item('b3-site-isolation', 'Site Isolation & Process Model', 'tier1', M34, { tags: ['security', 'architecture'] }),
    nest('b3-site-isolation', 'b3-origin-keyed-processes', 'Origin-Keyed Processes', 'tier1', M34, { tags: ['security', 'architecture'] }),
    nest('b3-site-isolation', 'b3-cross-site-iframes', 'Cross-Site iframe Process Boundaries', 'tier2', M56, { tags: ['security', 'architecture'] }),
    item('b3-rendering-engine', 'Rendering Engine (Blink / WebKit)', 'tier1', M34, { tags: ['rendering', 'architecture'] }),
    item('b3-javascript-engine-browser', 'JavaScript Engine in the Browser', 'tier1', M34, { tags: ['architecture'] }),
    item('b3-browser-security-sandbox', 'Browser Security Sandbox', 'tier1', M34, { tags: ['security', 'architecture'] }),
    item('b3-multi-tab-architecture', 'Multi-Tab & Multi-Window Architecture', 'tier2', M56, { tags: ['architecture'] }),
  ]),

  section('B3.2', 'Window, Document & BOM', 80, [
    item('b3-bom', 'Browser Object Model (BOM)', 'tier1', M34),
    item('b3-window-object', 'window Object', 'tier1', M34),
    nest('b3-window-object', 'b3-window-global-scope', 'Global Scope & window', 'tier1', M34),
    nest('b3-window-object', 'b3-window-properties', 'Window Properties & Methods', 'tier1', M34),
    nest('b3-window-object', 'b3-window-open-close', 'window.open / close / focus', 'tier2', M56),
    item('b3-document-object', 'document Object', 'tier1', M34),
    nest('b3-document-object', 'b3-document-properties', 'document Properties', 'tier1', M34),
    nest('b3-document-object', 'b3-document-methods', 'document Methods', 'tier1', M34),
    nest('b3-document-object', 'b3-document-ready-states', 'document.readyState', 'tier1', M34),
    item('b3-globalthis', 'globalThis in the Browser', 'tier1', M34),
    item('b3-navigator', 'navigator Object', 'tier1', M34),
    nest('b3-navigator', 'b3-navigator-user-agent', 'userAgent & Client Hints', 'tier1', M34),
    nest('b3-navigator', 'b3-navigator-language', 'language & languages', 'tier1', M34),
    nest('b3-navigator', 'b3-navigator-online', 'onLine & Connection Info', 'tier2', M56),
    nest('b3-navigator', 'b3-navigator-clipboard', 'clipboard (Overview)', 'tier2', M56),
    item('b3-location', 'location Object', 'tier1', M34, { tags: ['navigation'] }),
    nest('b3-location', 'b3-location-properties', 'href / origin / pathname / search / hash', 'tier1', M34, { tags: ['navigation'] }),
    nest('b3-location', 'b3-location-assign-replace', 'assign / replace / reload', 'tier1', M34, { tags: ['navigation'] }),
    item('b3-history', 'history Object', 'tier1', M34, { tags: ['navigation'] }),
    nest('b3-history', 'b3-history-stack', 'History Stack Model', 'tier1', M34, { tags: ['navigation'] }),
    nest('b3-history', 'b3-history-back-forward', 'back / forward / go', 'tier1', M34, { tags: ['navigation'] }),
    item('b3-history-api', 'History API', 'tier1', M34, { tags: ['navigation'] }),
    nest('b3-history-api', 'b3-pushstate-replacestate', 'pushState / replaceState', 'tier1', M34, { tags: ['navigation'] }),
    nest('b3-history-api', 'b3-popstate-event', 'popstate Event', 'tier1', M34, { tags: ['navigation'] }),
    nest('b3-history-api', 'b3-hashchange-event', 'hashchange Event', 'tier1', M34, { tags: ['navigation'] }),
    item('b3-screen', 'screen Object', 'tier2', M56),
    item('b3-console-browser', 'console in the Browser', 'tier1', M34),
    item('b3-timers-browser', 'setTimeout / setInterval in Browser', 'tier1', M34),
    item('b3-alert-prompt-confirm', 'alert / prompt / confirm', 'tier2', M56),
  ]),

  section('B3.3', 'DOM Fundamentals', 81, [
    item('b3-dom', 'DOM', 'tier1', M34),
    nest('b3-dom', 'b3-dom-elements', 'DOM Elements', 'tier1', M34),
    item('b3-dom-tree-model', 'DOM Tree Model', 'tier1', M34),
    nest('b3-dom-tree-model', 'b3-node-types', 'Node Types (Element, Text, Comment, Document)', 'tier1', M34),
    nest('b3-dom-tree-model', 'b3-parent-child-sibling', 'Parent / Child / Sibling Relationships', 'tier1', M34),
    nest('b3-dom-tree-model', 'b3-document-fragment', 'DocumentFragment', 'tier2', M56),
    item('b3-dom-selecting', 'Selecting Elements', 'tier1', M34),
    nest('b3-dom-selecting', 'b3-queryselector', 'querySelector / querySelectorAll', 'tier1', M34),
    nest('b3-dom-selecting', 'b3-getelementbyid', 'getElementById', 'tier1', M34),
    nest('b3-dom-selecting', 'b3-getelementsbyclassname', 'getElementsByClassName', 'tier1', M34),
    nest('b3-dom-selecting', 'b3-getelementsbytagname', 'getElementsByTagName', 'tier1', M34),
    nest('b3-dom-selecting', 'b3-matches-closest', 'matches / closest', 'tier1', M34),
    item('b3-dom-manipulation', 'DOM Manipulation', 'tier1', M34),
    nest('b3-dom-manipulation', 'b3-createelement', 'createElement / createTextNode', 'tier1', M34),
    nest('b3-dom-manipulation', 'b3-append-prepend', 'append / prepend / appendChild', 'tier1', M34),
    nest('b3-dom-manipulation', 'b3-insertbefore-after', 'insertBefore / insertAdjacentElement', 'tier1', M34),
    nest('b3-dom-manipulation', 'b3-remove-replace', 'remove / replaceChild / replaceWith', 'tier1', M34),
    nest('b3-dom-manipulation', 'b3-clonenode', 'cloneNode', 'tier1', M34),
    item('b3-dom-content', 'DOM Content & Text', 'tier1', M34),
    nest('b3-dom-content', 'b3-textcontent-innertext', 'textContent vs innerText', 'tier1', M34),
    nest('b3-dom-content', 'b3-innerhtml-outerhtml', 'innerHTML / outerHTML', 'tier1', M34),
    nest('b3-dom-content', 'b3-insertadjacenthtml', 'insertAdjacentHTML', 'tier1', M34),
    item('b3-dom-attributes', 'Attributes & Properties', 'tier1', M34),
    nest('b3-dom-attributes', 'b3-getset-attribute', 'getAttribute / setAttribute / removeAttribute', 'tier1', M34),
    nest('b3-dom-attributes', 'b3-attribute-vs-property', 'Attributes vs Properties', 'tier1', M34),
    nest('b3-dom-attributes', 'b3-dataset', 'data-* & dataset', 'tier1', M34),
    nest('b3-dom-attributes', 'b3-classlist', 'classList', 'tier1', M34),
    nest('b3-dom-attributes', 'b3-style-property', 'element.style', 'tier1', M34),
    item('b3-dom-traversal', 'DOM Traversal', 'tier1', M34),
    nest('b3-dom-traversal', 'b3-parentelement-children', 'parentElement / children / childNodes', 'tier1', M34),
    nest('b3-dom-traversal', 'b3-first-last-child', 'firstChild / lastChild / nextSibling / previousSibling', 'tier1', M34),
    nest('b3-dom-traversal', 'b3-traverser-apis', 'TreeWalker / NodeIterator', 'tier2', M56),
    item('b3-dom-live-collections', 'Live vs Static Collections', 'tier1', M34),
    item('b3-dom-shadow-dom-intro', 'Shadow DOM (Overview)', 'tier2', M56),
  ]),

  section('B3.4', 'DOM Events', 82, [
    item('b3-dom-events', 'DOM Events', 'tier1', M34, { tags: ['events'] }),
    nest('b3-dom-events', 'b3-add-event-listener', 'addEventListener', 'tier1', M34, { tags: ['events'] }),
    nest('b3-dom-events', 'b3-remove-event-listener', 'removeEventListener', 'tier1', M34, { tags: ['events'] }),
    nest('b3-dom-events', 'b3-event-listener-options', 'Listener Options (once, passive, capture)', 'tier1', M34, { tags: ['events'] }),
    item('b3-event-object', 'Event Object', 'tier1', M34, { tags: ['events'] }),
    nest('b3-event-object', 'b3-event-target-currenttarget', 'target vs currentTarget', 'tier1', M34, { tags: ['events'] }),
    nest('b3-event-object', 'b3-event-preventdefault', 'preventDefault()', 'tier1', M34, { tags: ['events'] }),
    nest('b3-event-object', 'b3-event-stoppropagation', 'stopPropagation / stopImmediatePropagation', 'tier1', M34, { tags: ['events'] }),
    nest('b3-event-object', 'b3-event-type-phase', 'type / eventPhase / bubbles / cancelable', 'tier1', M34, { tags: ['events'] }),
    item('b3-event-bubbling', 'Event Bubbling & Capturing', 'tier1', M34, { tags: ['events'] }),
    nest('b3-event-bubbling', 'b3-event-capturing', 'Event Capturing', 'tier1', M34, { tags: ['events'] }),
    item('b3-event-delegation', 'Event Delegation', 'tier1', M34, { tags: ['events'] }),
    item('b3-custom-events', 'Custom Events', 'tier2', M56, { tags: ['events'] }),
    nest('b3-custom-events', 'b3-customevent-constructor', 'CustomEvent Constructor', 'tier2', M56, { tags: ['events'] }),
    nest('b3-custom-events', 'b3-dispatch-event', 'dispatchEvent', 'tier2', M56, { tags: ['events'] }),
    item('b3-event-categories', 'Event Categories', 'tier1', M34, { tags: ['events'] }),
    nest('b3-event-categories', 'b3-mouse-events', 'Mouse Events', 'tier1', M34, { tags: ['events'] }),
    nest('b3-event-categories', 'b3-keyboard-events', 'Keyboard Events', 'tier1', M34, { tags: ['events'] }),
    nest('b3-event-categories', 'b3-focus-events', 'Focus Events', 'tier1', M34, { tags: ['events'] }),
    nest('b3-event-categories', 'b3-form-events', 'Form & Input Events', 'tier1', M34, { tags: ['events'] }),
    nest('b3-event-categories', 'b3-touch-events', 'Touch & Pointer Events', 'tier1', M34, { tags: ['events'] }),
    nest('b3-event-categories', 'b3-scroll-events', 'Scroll Events', 'tier1', M34, { tags: ['events'] }),
    nest('b3-event-categories', 'b3-clipboard-events', 'Clipboard Events', 'tier2', M56, { tags: ['events'] }),
    nest('b3-event-categories', 'b3-drag-events', 'Drag Events', 'tier2', M56, { tags: ['events'] }),
    item('b3-inline-handlers', 'Inline Event Handlers', 'tier2', M56, { tags: ['events'] }),
    item('b3-event-timing', 'Event Timing & Order', 'tier1', M34, { tags: ['events'] }),
  ]),

  section('B3.5', 'HTML Parsing & Page Loading', 83, [
    item('b3-html-parsing', 'HTML Parsing', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-html-parsing', 'b3-tokenization', 'Tokenization & Tree Construction', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-html-parsing', 'b3-parser-blocking', 'Parser-Blocking Resources', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-html-parsing', 'b3-preload-scanner', 'Preload Scanner / Speculative Parsing', 'tier2', M56, { tags: ['rendering'] }),
    item('b3-script-loading', 'Script Loading', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-script-loading', 'b3-script-async', 'async Scripts', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-script-loading', 'b3-script-defer', 'defer Scripts', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-script-loading', 'b3-script-module', 'type="module" Scripts', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-script-loading', 'b3-script-dynamic-import', 'Dynamic import() in Browser', 'tier1', M34, { tags: ['rendering'] }),
    item('b3-stylesheet-loading', 'Stylesheet Loading', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-stylesheet-loading', 'b3-render-blocking-css', 'Render-Blocking CSS', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-stylesheet-loading', 'b3-css-media-queries-loading', 'media Attribute & Conditional CSS', 'tier2', M56, { tags: ['rendering'] }),
    item('b3-page-load-events', 'Page Load Lifecycle Events', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-page-load-events', 'b3-domcontentloaded', 'DOMContentLoaded', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-page-load-events', 'b3-load-event', 'load Event', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-page-load-events', 'b3-beforeunload-unload', 'beforeunload / unload', 'tier2', M56, { tags: ['rendering'] }),
    item('b3-resource-priority', 'Resource Load Priority', 'tier2', M56, { tags: ['rendering', 'performance'] }),
    item('b3-first-paint-timing', 'First Paint & First Contentful Paint', 'tier1', M34, { tags: ['rendering', 'performance'] }),
  ]),

  section('B3.6', 'Critical Rendering Path', 84, [
    item('b3-critical-rendering-path', 'Critical Rendering Path', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-critical-rendering-path', 'b3-cssom', 'CSSOM', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-critical-rendering-path', 'b3-render-tree', 'Render Tree', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-critical-rendering-path', 'b3-dom-cssom-merge', 'DOM + CSSOM → Render Tree', 'tier1', M34, { tags: ['rendering'] }),
    item('b3-display-none-visibility', 'display:none vs visibility:hidden', 'tier1', M34, { tags: ['rendering'] }),
    item('b3-blocking-vs-nonblocking', 'Blocking vs Non-Blocking Resources', 'tier1', M34, { tags: ['rendering'] }),
    item('b3-critical-css', 'Critical CSS Extraction', 'tier2', M56, { tags: ['rendering', 'performance'] }),
    item('b3-above-fold-rendering', 'Above-the-Fold Rendering Strategy', 'tier2', M56, { tags: ['rendering', 'performance'] }),
    item('b3-font-loading-render', 'Font Loading & FOIT/FOUT', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-font-loading-render', 'b3-font-display', 'font-display', 'tier1', M34, { tags: ['rendering'] }),
    item('b3-content-visibility', 'content-visibility', 'tier2', M56, { tags: ['rendering', 'performance'] }),
  ]),

  section('B3.7', 'Layout, Reflow, Paint & Compositing', 85, [
    item('b3-layout', 'Layout (Reflow)', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-layout', 'b3-layout-box-model', 'Box Model in Layout', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-layout', 'b3-layout-flow', 'Normal Flow & Positioning Impact', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-layout', 'b3-layout-flex-grid', 'Flexbox & Grid Layout', 'tier1', M34, { tags: ['rendering'] }),
    item('b3-paint', 'Paint', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-paint', 'b3-paint-layers', 'Paint Layers & Recording', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-paint', 'b3-paint-optimization', 'Paint Optimization', 'tier2', M56, { tags: ['rendering', 'performance'] }),
    item('b3-compositing', 'Compositing', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-compositing', 'b3-compositor-layers', 'Compositor Layers', 'tier1', M34, { tags: ['rendering'] }),
    nest('b3-compositing', 'b3-gpu-acceleration', 'GPU Acceleration', 'tier1', M34, { tags: ['rendering', 'performance'] }),
    nest('b3-compositing', 'b3-transform-opacity-compositing', 'transform & opacity Compositing', 'tier1', M34, { tags: ['rendering'] }),
    item('b3-reflow-repaint', 'Reflow & Repaint', 'tier1', M34, { tags: ['rendering', 'performance'] }),
    nest('b3-reflow-repaint', 'b3-reflow-triggers', 'What Triggers Reflow', 'tier1', M34, { tags: ['rendering', 'performance'] }),
    nest('b3-reflow-repaint', 'b3-repaint-triggers', 'What Triggers Repaint', 'tier1', M34, { tags: ['rendering', 'performance'] }),
    item('b3-layout-thrashing', 'Layout Thrashing', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-layout-thrashing', 'b3-read-write-interleaving', 'Read/Write DOM Interleaving', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-layout-thrashing', 'b3-batch-dom-reads-writes', 'Batching DOM Reads & Writes', 'tier1', M34, { tags: ['performance'] }),
    item('b3-will-change', 'will-change', 'tier1', M34, { tags: ['performance', 'rendering'] }),
    item('b3-contain-property', 'contain Property', 'tier2', M56, { tags: ['performance', 'rendering'] }),
    item('b3-layer-promotion', 'Layer Promotion & Demotion', 'tier2', M56, { tags: ['rendering', 'performance'] }),
  ]),

  section('B3.8', 'Browser Event Loop & Rendering', 86, [
    item('b3-browser-event-loop', 'Browser Event Loop', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-browser-event-loop', 'b3-task-queue-microtask', 'Task Queue vs Microtask Queue', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-browser-event-loop', 'b3-render-steps', 'Rendering Steps in the Loop', 'tier1', M34, { tags: ['performance', 'rendering'] }),
    nest('b3-browser-event-loop', 'b3-style-layout-paint-order', 'Style → Layout → Paint → Composite Order', 'tier1', M34, { tags: ['performance', 'rendering'] }),
    item('b3-long-tasks-browser', 'Long Tasks in the Browser', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-long-tasks-browser', 'b3-long-task-api', 'Long Task API / PerformanceLongTaskTiming', 'tier2', M56, { tags: ['performance'] }),
    nest('b3-long-tasks-browser', 'b3-main-thread-blocking', 'Main-Thread Blocking Symptoms', 'tier1', M34, { tags: ['performance'] }),
    item('b3-idle-callback', 'requestIdleCallback', 'tier2', M56, { tags: ['performance'] }),
    item('b3-scheduler-posttask', 'Scheduler.postTask', 'tier2', M56, { tags: ['performance'] }),
    item('b3-input-delay', 'Input Delay & Responsiveness', 'tier1', M34, { tags: ['performance'] }),
    item('b3-frame-budget', 'Frame Budget (16.67ms)', 'tier1', M34, { tags: ['performance'] }),
    item('b3-event-loop-rendering-sync', 'Event Loop vs Rendering Sync Points', 'tier1', M34, { tags: ['performance', 'rendering'] }),
  ]),

  section('B3.9', 'requestAnimationFrame', 87, [
    item('b3-raf', 'requestAnimationFrame', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-raf', 'b3-raf-callback-timing', 'rAF Callback Timing', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-raf', 'b3-cancel-animation-frame', 'cancelAnimationFrame', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-raf', 'b3-raf-vs-settimeout', 'rAF vs setTimeout for Animation', 'tier1', M34, { tags: ['performance'] }),
    item('b3-raf-patterns', 'rAF Animation Patterns', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-raf-patterns', 'b3-raf-game-loop', 'Game Loop Pattern', 'tier2', M56, { tags: ['performance'] }),
    nest('b3-raf-patterns', 'b3-raf-scroll-sync', 'Scroll-Synced Animation', 'tier2', M56, { tags: ['performance'] }),
    item('b3-raf-measure-layout', 'Measuring Layout in rAF', 'tier1', M34, { tags: ['performance'] }),
    item('b3-raf-double-buffer', 'Double rAF Pattern', 'tier2', M56, { tags: ['performance'] }),
  ]),

  section('B3.10', 'Browser HTTP', 88, [
    item('b3-browser-http', 'HTTP in the Browser', 'tier1', M34, { tags: ['http'] }),
    nest('b3-browser-http', 'b3-http-request-structure', 'HTTP Request Structure', 'tier1', M34, { tags: ['http'] }),
    nest('b3-browser-http', 'b3-http-response-structure', 'HTTP Response Structure', 'tier1', M34, { tags: ['http'] }),
    nest('b3-browser-http', 'b3-http-methods', 'HTTP Methods (GET, POST, PUT, PATCH, DELETE)', 'tier1', M34, { tags: ['http'] }),
    item('b3-http-headers', 'HTTP Headers', 'tier1', M34, { tags: ['http'] }),
    nest('b3-http-headers', 'b3-request-headers', 'Common Request Headers', 'tier1', M34, { tags: ['http'] }),
    nest('b3-http-headers', 'b3-response-headers', 'Common Response Headers', 'tier1', M34, { tags: ['http'] }),
    nest('b3-http-headers', 'b3-content-type-charset', 'Content-Type & Charset', 'tier1', M34, { tags: ['http'] }),
    nest('b3-http-headers', 'b3-cache-control-headers', 'Cache-Control Headers', 'tier1', M34, { tags: ['http'] }),
    nest('b3-http-headers', 'b3-cookie-headers', 'Set-Cookie / Cookie Headers', 'tier1', M34, { tags: ['http'] }),
    item('b3-http-status-codes', 'HTTP Status Codes', 'tier1', M34, { tags: ['http'] }),
    nest('b3-http-status-codes', 'b3-status-2xx', '2xx Success Codes', 'tier1', M34, { tags: ['http'] }),
    nest('b3-http-status-codes', 'b3-status-3xx', '3xx Redirection Codes', 'tier1', M34, { tags: ['http'] }),
    nest('b3-http-status-codes', 'b3-status-4xx', '4xx Client Error Codes', 'tier1', M34, { tags: ['http'] }),
    nest('b3-http-status-codes', 'b3-status-5xx', '5xx Server Error Codes', 'tier1', M34, { tags: ['http'] }),
    item('b3-http-versions', 'HTTP Versions', 'tier1', M34, { tags: ['http'] }),
    nest('b3-http-versions', 'b3-http1-1', 'HTTP/1.1', 'tier1', M34, { tags: ['http'] }),
    nest('b3-http-versions', 'b3-http2', 'HTTP/2', 'tier1', M34, { tags: ['http'] }),
    nest('b3-http-versions', 'b3-http3-quic', 'HTTP/3 & QUIC', 'tier2', M56, { tags: ['http'] }),
    item('b3-https-browser', 'HTTPS in the Browser', 'tier1', M34, { tags: ['http', 'security'] }),
    nest('b3-https-browser', 'b3-tls-certificates', 'TLS Certificates & Trust', 'tier1', M34, { tags: ['http', 'security'] }),
    nest('b3-https-browser', 'b3-mixed-content', 'Mixed Content', 'tier1', M34, { tags: ['http', 'security'] }),
    item('b3-cookies-http', 'Cookies in HTTP', 'tier1', M34, { tags: ['http', 'storage'] }),
  ]),

  section('B3.11', 'Fetch API', 89, [
    item('b3-fetch', 'Fetch API', 'tier1', M34, { tags: ['http'] }),
    nest('b3-fetch', 'b3-fetch-request', 'Request Object', 'tier1', M34, { tags: ['http'] }),
    nest('b3-fetch', 'b3-fetch-response', 'Response Object', 'tier1', M34, { tags: ['http'] }),
    nest('b3-fetch', 'b3-fetch-headers', 'Headers Object', 'tier1', M34, { tags: ['http'] }),
    nest('b3-fetch', 'b3-fetch-methods', 'GET / POST / PUT / DELETE with fetch', 'tier1', M34, { tags: ['http'] }),
    nest('b3-fetch', 'b3-fetch-json-text', 'response.json() / text() / blob()', 'tier1', M34, { tags: ['http'] }),
    nest('b3-fetch', 'b3-fetch-credentials', 'credentials: include / same-origin / omit', 'tier1', M34, { tags: ['http'] }),
    nest('b3-fetch', 'b3-fetch-mode', 'mode: cors / no-cors / same-origin', 'tier1', M34, { tags: ['http'] }),
    nest('b3-fetch', 'b3-fetch-cache', 'cache Option', 'tier1', M34, { tags: ['http'] }),
    item('b3-fetch-error-handling', 'Fetch Error Handling', 'tier1', M34, { tags: ['http'] }),
    nest('b3-fetch-error-handling', 'b3-fetch-network-errors', 'Network vs HTTP Errors', 'tier1', M34, { tags: ['http'] }),
    nest('b3-fetch-error-handling', 'b3-fetch-ok-status', 'response.ok & Status Checking', 'tier1', M34, { tags: ['http'] }),
    item('b3-fetch-streaming', 'Streaming with Fetch', 'tier2', M56, { tags: ['http'] }),
    nest('b3-fetch-streaming', 'b3-readablestream-body', 'ReadableStream Response Body', 'tier2', M56, { tags: ['http'] }),
    item('b3-fetch-vs-xhr', 'Fetch vs XMLHttpRequest', 'tier1', M34, { tags: ['http'] }),
    item('b3-formdata-fetch', 'FormData with Fetch', 'tier1', M34, { tags: ['http'] }),
  ]),

  section('B3.12', 'AbortController & Cancellation', 90, [
    item('b3-abort-controller', 'AbortController', 'tier1', M34, { tags: ['http'] }),
    nest('b3-abort-controller', 'b3-abort-signal', 'AbortSignal', 'tier1', M34, { tags: ['http'] }),
    nest('b3-abort-controller', 'b3-abort-fetch', 'Aborting fetch Requests', 'tier1', M34, { tags: ['http'] }),
    nest('b3-abort-controller', 'b3-abort-timeout', 'Timeout via AbortController', 'tier1', M34, { tags: ['http'] }),
    item('b3-stale-requests', 'Stale Request Handling', 'tier1', M34, { tags: ['http'] }),
    nest('b3-stale-requests', 'b3-request-deduplication', 'Request Deduplication', 'tier2', M56, { tags: ['http'] }),
    nest('b3-stale-requests', 'b3-ignore-stale-responses', 'Ignoring Stale Responses', 'tier1', M34, { tags: ['http'] }),
    item('b3-race-conditions-fetch', 'Race Conditions in Data Fetching', 'tier1', M34, { tags: ['http'] }),
    nest('b3-race-conditions-fetch', 'b3-latest-request-wins', 'Latest-Request-Wins Pattern', 'tier1', M34, { tags: ['http'] }),
    item('b3-abort-other-apis', 'AbortSignal with Other APIs', 'tier2', M56, { tags: ['http'] }),
  ]),

  section('B3.13', 'Same-Origin Policy', 91, [
    item('b3-same-origin', 'Same-Origin Policy', 'tier1', M34, { tags: ['security'] }),
    nest('b3-same-origin', 'b3-origin-definition', 'Origin Definition (scheme + host + port)', 'tier1', M34, { tags: ['security'] }),
    nest('b3-same-origin', 'b3-same-site-vs-same-origin', 'Same-Site vs Same-Origin', 'tier1', M34, { tags: ['security'] }),
    nest('b3-same-origin', 'b3-sop-dom-access', 'SOP & DOM Access', 'tier1', M34, { tags: ['security'] }),
    nest('b3-same-origin', 'b3-sop-network-access', 'SOP & Network Access', 'tier1', M34, { tags: ['security'] }),
    nest('b3-same-origin', 'b3-sop-storage-access', 'SOP & Storage Access', 'tier1', M34, { tags: ['security'] }),
    item('b3-cross-origin-isolation', 'Cross-Origin Isolation', 'tier2', M56, { tags: ['security'] }),
    nest('b3-cross-origin-isolation', 'b3-coop-coep', 'COOP & COEP Headers', 'tier2', M56, { tags: ['security'] }),
    item('b3-document-domain-legacy', 'document.domain (Legacy)', 'tier3', M78, { tags: ['security'] }),
  ]),

  section('B3.14', 'CORS', 92, [
    item('b3-cors', 'CORS', 'tier1', M34, { tags: ['security', 'http'] }),
    nest('b3-cors', 'b3-cors-preflight', 'Preflight Requests (OPTIONS)', 'tier1', M34, { tags: ['security', 'http'] }),
    nest('b3-cors', 'b3-cors-simple-requests', 'Simple vs Non-Simple Requests', 'tier1', M34, { tags: ['security', 'http'] }),
    nest('b3-cors', 'b3-cors-headers', 'Access-Control-* Headers', 'tier1', M34, { tags: ['security', 'http'] }),
    nest('b3-cors', 'b3-cors-credentials', 'Credentials in CORS', 'tier1', M34, { tags: ['security', 'http'] }),
    nest('b3-cors', 'b3-cors-errors', 'CORS Error Messages & Debugging', 'tier1', M34, { tags: ['security', 'http'] }),
    item('b3-cors-server-config', 'Server-Side CORS Configuration', 'tier1', M34, { tags: ['security', 'http'] }),
    item('b3-cors-proxy', 'CORS Proxy Patterns (Dev)', 'tier2', M56, { tags: ['security', 'http'] }),
    item('b3-jsonp-legacy', 'JSONP (Legacy)', 'tier3', M78, { tags: ['security', 'http'] }),
  ]),

  section('B3.15', 'Cookies', 93, [
    item('b3-cookies', 'Cookies', 'tier1', M34, { tags: ['storage', 'security'] }),
    nest('b3-cookies', 'b3-cookie-attributes', 'Cookie Attributes', 'tier1', M34, { tags: ['storage', 'security'] }),
    nest('b3-cookies', 'b3-cookie-httponly', 'HttpOnly', 'tier1', M34, { tags: ['storage', 'security'] }),
    nest('b3-cookies', 'b3-cookie-secure', 'Secure', 'tier1', M34, { tags: ['storage', 'security'] }),
    nest('b3-cookies', 'b3-cookie-samesite', 'SameSite (Strict / Lax / None)', 'tier1', M34, { tags: ['storage', 'security'] }),
    nest('b3-cookies', 'b3-cookie-domain-path', 'Domain & Path', 'tier1', M34, { tags: ['storage', 'security'] }),
    nest('b3-cookies', 'b3-cookie-max-age-expires', 'Max-Age & Expires', 'tier1', M34, { tags: ['storage', 'security'] }),
    item('b3-document-cookie', 'document.cookie API', 'tier1', M34, { tags: ['storage'] }),
    item('b3-cookie-size-limits', 'Cookie Size & Count Limits', 'tier1', M34, { tags: ['storage'] }),
    item('b3-third-party-cookies', 'Third-Party Cookies', 'tier1', M34, { tags: ['storage', 'security'] }),
    nest('b3-third-party-cookies', 'b3-cookie-deprecation', 'Third-Party Cookie Deprecation', 'tier1', M34, { tags: ['storage', 'security'] }),
    item('b3-cookie-security-model', 'Cookie Security Model', 'tier1', M34, { tags: ['security'] }),
    item('b3-cookie-storage-api', 'Cookie Store API', 'tier2', M56, { tags: ['storage'] }),
  ]),

  section('B3.16', 'Web Storage', 94, [
    item('b3-web-storage', 'Web Storage API', 'tier1', M34, { tags: ['storage'] }),
    nest('b3-web-storage', 'b3-localstorage', 'localStorage', 'tier1', M34, { tags: ['storage'] }),
    nest('b3-web-storage', 'b3-sessionstorage', 'sessionStorage', 'tier1', M34, { tags: ['storage'] }),
    nest('b3-web-storage', 'b3-localstorage-api', 'localStorage API (getItem / setItem / removeItem)', 'tier1', M34, { tags: ['storage'] }),
    nest('b3-web-storage', 'b3-sessionstorage-lifecycle', 'sessionStorage Tab Lifecycle', 'tier1', M34, { tags: ['storage'] }),
    item('b3-storage-comparison', 'localStorage vs sessionStorage vs Cookies', 'tier1', M34, { tags: ['storage'] }),
    nest('b3-storage-comparison', 'b3-storage-quota', 'Storage Quotas & Limits', 'tier1', M34, { tags: ['storage'] }),
    nest('b3-storage-comparison', 'b3-storage-events', 'storage Event', 'tier1', M34, { tags: ['storage'] }),
    item('b3-storage-security', 'Web Storage Security Considerations', 'tier1', M34, { tags: ['storage', 'security'] }),
    item('b3-storage-serialization', 'Storage Serialization (Strings Only)', 'tier1', M34, { tags: ['storage'] }),
  ]),

  section('B3.17', 'IndexedDB', 95, [
    item('b3-indexeddb', 'IndexedDB', 'tier1', M34, { tags: ['storage'] }),
    nest('b3-indexeddb', 'b3-idb-database', 'IDBDatabase', 'tier1', M34, { tags: ['storage'] }),
    nest('b3-indexeddb', 'b3-idb-transactions', 'Transactions & Version Changes', 'tier1', M34, { tags: ['storage'] }),
    nest('b3-indexeddb', 'b3-idb-object-stores', 'Object Stores & Indexes', 'tier1', M34, { tags: ['storage'] }),
    nest('b3-indexeddb', 'b3-idb-cursor', 'Cursors & Key Ranges', 'tier2', M56, { tags: ['storage'] }),
    item('b3-idb-vs-localstorage', 'IndexedDB vs localStorage', 'tier1', M34, { tags: ['storage'] }),
    item('b3-idb-async-model', 'IndexedDB Async Model', 'tier1', M34, { tags: ['storage'] }),
    item('b3-idb-libraries', 'IndexedDB Wrapper Libraries', 'tier2', M56, { tags: ['storage'] }),
  ]),

  section('B3.18', 'Browser Caching', 96, [
    item('b3-http-caching', 'HTTP Caching', 'tier1', M34, { tags: ['http', 'performance'] }),
    nest('b3-http-caching', 'b3-cache-control-directives', 'Cache-Control Directives', 'tier1', M34, { tags: ['http', 'performance'] }),
    nest('b3-http-caching', 'b3-etag', 'ETag & If-None-Match', 'tier1', M34, { tags: ['http', 'performance'] }),
    nest('b3-http-caching', 'b3-last-modified', 'Last-Modified & If-Modified-Since', 'tier1', M34, { tags: ['http', 'performance'] }),
    nest('b3-http-caching', 'b3-cache-validation', 'Cache Validation vs Freshness', 'tier1', M34, { tags: ['http', 'performance'] }),
    item('b3-memory-disk-cache', 'Memory Cache vs Disk Cache', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-memory-disk-cache', 'b3-cache-partitioning', 'Cache Partitioning (Third-Party)', 'tier2', M56, { tags: ['performance', 'security'] }),
    item('b3-service-worker-cache', 'Service Worker Cache (Overview)', 'tier2', M56, { tags: ['performance'] }),
    item('b3-cache-busting', 'Cache Busting Strategies', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-cache-busting', 'b3-fingerprinting-assets', 'Asset Fingerprinting / Hashing', 'tier1', M34, { tags: ['performance'] }),
    item('b3-stale-while-revalidate', 'stale-while-revalidate', 'tier2', M56, { tags: ['http', 'performance'] }),
  ]),

  section('B3.19', 'Content Security Policy', 97, [
    item('b3-csp', 'Content Security Policy', 'tier1', M34, { tags: ['security'] }),
    nest('b3-csp', 'b3-csp-directives', 'CSP Directives', 'tier1', M34, { tags: ['security'] }),
    nest('b3-csp', 'b3-csp-script-src', 'script-src', 'tier1', M34, { tags: ['security'] }),
    nest('b3-csp', 'b3-csp-style-src', 'style-src', 'tier1', M34, { tags: ['security'] }),
    nest('b3-csp', 'b3-csp-img-src', 'img-src & media-src', 'tier1', M34, { tags: ['security'] }),
    nest('b3-csp', 'b3-csp-connect-src', 'connect-src', 'tier1', M34, { tags: ['security'] }),
    nest('b3-csp', 'b3-csp-frame-ancestors', 'frame-ancestors', 'tier1', M34, { tags: ['security'] }),
    nest('b3-csp', 'b3-csp-report-only', 'Content-Security-Policy-Report-Only', 'tier2', M56, { tags: ['security'] }),
    nest('b3-csp', 'b3-csp-nonces-hashes', 'Nonces & Hashes', 'tier1', M34, { tags: ['security'] }),
    nest('b3-csp', 'b3-csp-inline-scripts', 'Inline Script Restrictions', 'tier1', M34, { tags: ['security'] }),
    item('b3-csp-deployment', 'CSP Deployment Strategy', 'tier2', M56, { tags: ['security'] }),
  ]),

  section('B3.20', 'Browser Security Fundamentals', 98, [
    item('b3-browser-security', 'Browser Security Fundamentals', 'tier1', M34, { tags: ['security'] }),
    item('b3-xss', 'Cross-Site Scripting (XSS)', 'tier1', M34, { tags: ['security'] }),
    nest('b3-xss', 'b3-xss-reflected', 'Reflected XSS', 'tier1', M34, { tags: ['security'] }),
    nest('b3-xss', 'b3-xss-stored', 'Stored XSS', 'tier1', M34, { tags: ['security'] }),
    nest('b3-xss', 'b3-xss-dom-based', 'DOM-Based XSS', 'tier1', M34, { tags: ['security'] }),
    nest('b3-xss', 'b3-xss-prevention', 'XSS Prevention (encode, sanitize, CSP)', 'tier1', M34, { tags: ['security'] }),
    item('b3-csrf', 'Cross-Site Request Forgery (CSRF)', 'tier1', M34, { tags: ['security'] }),
    nest('b3-csrf', 'b3-csrf-tokens', 'CSRF Tokens', 'tier1', M34, { tags: ['security'] }),
    nest('b3-csrf', 'b3-csrf-samesite-defense', 'SameSite Cookie Defense', 'tier1', M34, { tags: ['security'] }),
    nest('b3-csrf', 'b3-csrf-double-submit', 'Double-Submit Cookie Pattern', 'tier2', M56, { tags: ['security'] }),
    item('b3-clickjacking', 'Clickjacking', 'tier1', M34, { tags: ['security'] }),
    nest('b3-clickjacking', 'b3-x-frame-options', 'X-Frame-Options', 'tier1', M34, { tags: ['security'] }),
    nest('b3-clickjacking', 'b3-frame-busting', 'Frame Busting (Legacy)', 'tier3', M78, { tags: ['security'] }),
    item('b3-open-redirect', 'Open Redirect Vulnerabilities', 'tier2', M56, { tags: ['security'] }),
    item('b3-security-headers', 'Security Headers Overview', 'tier1', M34, { tags: ['security'] }),
    nest('b3-security-headers', 'b3-hsts', 'Strict-Transport-Security (HSTS)', 'tier1', M34, { tags: ['security'] }),
    nest('b3-security-headers', 'b3-referrer-policy', 'Referrer-Policy', 'tier1', M34, { tags: ['security'] }),
    nest('b3-security-headers', 'b3-permissions-policy', 'Permissions-Policy', 'tier2', M56, { tags: ['security'] }),
  ]),

  section('B3.21', 'Web Workers', 99, [
    item('b3-web-workers', 'Web Workers', 'tier1', M34),
    nest('b3-web-workers', 'b3-dedicated-workers', 'Dedicated Workers', 'tier1', M34),
    nest('b3-web-workers', 'b3-shared-workers', 'Shared Workers', 'tier2', M56),
    nest('b3-web-workers', 'b3-worker-postmessage', 'postMessage & Message Passing', 'tier1', M34),
    nest('b3-web-workers', 'b3-worker-transferables', 'Transferable Objects', 'tier1', M34),
    nest('b3-web-workers', 'b3-worker-termination', 'Worker Termination', 'tier1', M34),
    item('b3-worker-limitations', 'Worker Limitations (No DOM)', 'tier1', M34),
    item('b3-worker-use-cases', 'Worker Use Cases', 'tier1', M34),
    nest('b3-worker-use-cases', 'b3-worker-heavy-computation', 'Offloading Heavy Computation', 'tier1', M34),
    nest('b3-worker-use-cases', 'b3-worker-parsing', 'Background Parsing / Processing', 'tier2', M56),
    item('b3-worker-modules', 'Module Workers (type: module)', 'tier1', M34),
  ]),

  section('B3.22', 'Service Workers', 100, [
    item('b3-service-workers', 'Service Workers', 'tier2', M56),
    nest('b3-service-workers', 'b3-sw-lifecycle', 'Service Worker Lifecycle', 'tier2', M56),
    nest('b3-service-workers', 'b3-sw-install', 'install Event', 'tier2', M56),
    nest('b3-service-workers', 'b3-sw-activate', 'activate Event', 'tier2', M56),
    nest('b3-service-workers', 'b3-sw-update', 'Update & skipWaiting', 'tier2', M56),
    nest('b3-service-workers', 'b3-sw-fetch-intercept', 'fetch Event & Request Interception', 'tier2', M56),
    nest('b3-service-workers', 'b3-sw-cache-api', 'Cache API with Service Workers', 'tier2', M56),
    nest('b3-service-workers', 'b3-sw-scope', 'Service Worker Scope', 'tier2', M56),
    item('b3-sw-offline', 'Offline-First Patterns', 'tier2', M56),
    item('b3-sw-push-notifications', 'Push Notifications (Overview)', 'tier3', M78),
    item('b3-sw-background-sync', 'Background Sync (Overview)', 'tier3', M78),
  ]),

  section('B3.23', 'WebSockets', 101, [
    item('b3-websockets', 'WebSockets', 'tier2', M56),
    nest('b3-websockets', 'b3-ws-handshake', 'WebSocket Handshake', 'tier2', M56),
    nest('b3-websockets', 'b3-ws-api', 'WebSocket API (send / close / events)', 'tier2', M56),
    nest('b3-websockets', 'b3-ws-binary-messages', 'Binary & Text Messages', 'tier2', M56),
    nest('b3-websockets', 'b3-ws-reconnection', 'Reconnection Strategies', 'tier2', M56),
    item('b3-ws-vs-http', 'WebSockets vs HTTP Polling', 'tier2', M56),
    item('b3-ws-security', 'WebSocket Security (wss://)', 'tier2', M56),
    item('b3-ws-use-cases', 'WebSocket Use Cases', 'tier2', M56),
  ]),

  section('B3.24', 'Server-Sent Events', 102, [
    item('b3-sse', 'Server-Sent Events (SSE)', 'tier2', M56),
    nest('b3-sse', 'b3-event-source', 'EventSource API', 'tier2', M56),
    nest('b3-sse', 'b3-sse-event-format', 'SSE Event Format', 'tier2', M56),
    nest('b3-sse', 'b3-sse-reconnection', 'Automatic Reconnection', 'tier2', M56),
    item('b3-sse-vs-websockets', 'SSE vs WebSockets', 'tier2', M56),
    item('b3-sse-vs-polling', 'SSE vs Long Polling', 'tier2', M56),
    item('b3-sse-use-cases', 'SSE Use Cases', 'tier2', M56),
  ]),

  section('B3.25', 'Observer APIs', 103, [
    item('b3-intersection-observer', 'Intersection Observer', 'tier1', M34),
    nest('b3-intersection-observer', 'b3-io-root-margin', 'root / rootMargin / threshold', 'tier1', M34),
    nest('b3-intersection-observer', 'b3-io-lazy-loading', 'Lazy Loading with Intersection Observer', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-intersection-observer', 'b3-io-infinite-scroll', 'Infinite Scroll Detection', 'tier1', M34),
    item('b3-mutation-observer', 'Mutation Observer', 'tier2', M56),
    nest('b3-mutation-observer', 'b3-mo-observe-options', 'observe Options & Callback', 'tier2', M56),
    nest('b3-mutation-observer', 'b3-mo-use-cases', 'DOM Change Detection Use Cases', 'tier2', M56),
    item('b3-resize-observer', 'Resize Observer', 'tier2', M56),
    nest('b3-resize-observer', 'b3-ro-element-resize', 'Element Resize Detection', 'tier2', M56),
    item('b3-performance-observer', 'Performance Observer', 'tier2', M56, { tags: ['performance'] }),
    nest('b3-performance-observer', 'b3-po-entry-types', 'Performance Entry Types', 'tier2', M56, { tags: ['performance'] }),
    nest('b3-performance-observer', 'b3-po-web-vitals-observe', 'Observing Web Vitals', 'tier2', M56, { tags: ['performance'] }),
  ]),

  section('B3.26', 'Blob & File APIs', 104, [
    item('b3-blob-file', 'Blob & File API', 'tier2', M56),
    nest('b3-blob-file', 'b3-blob-constructor', 'Blob Constructor', 'tier2', M56),
    nest('b3-blob-file', 'b3-file-object', 'File Object', 'tier2', M56),
    nest('b3-blob-file', 'b3-file-reader', 'FileReader', 'tier2', M56),
    nest('b3-blob-file', 'b3-object-url', 'URL.createObjectURL / revokeObjectURL', 'tier2', M56),
    item('b3-blob-download', 'Downloading Blobs', 'tier2', M56),
    nest('b3-blob-download', 'b3-anchor-download', 'Anchor download Attribute', 'tier2', M56),
    item('b3-blob-upload', 'Uploading Blobs via Fetch', 'tier2', M56, { tags: ['http'] }),
    item('b3-blob-streaming', 'Blob Streaming', 'tier3', M78),
  ]),

  section('B3.27', 'Browser Performance', 105, [
    item('b3-browser-performance', 'Browser Performance', 'tier1', M34, { tags: ['performance'] }),
    item('b3-core-web-vitals', 'Core Web Vitals', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-core-web-vitals', 'b3-lcp', 'Largest Contentful Paint (LCP)', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-core-web-vitals', 'b3-inp', 'Interaction to Next Paint (INP)', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-core-web-vitals', 'b3-cls', 'Cumulative Layout Shift (CLS)', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-core-web-vitals', 'b3-fcp-ttfb', 'FCP & TTFB', 'tier1', M34, { tags: ['performance'] }),
    item('b3-performance-api', 'Performance API', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-performance-api', 'b3-performance-now', 'performance.now()', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-performance-api', 'b3-performance-timing', 'Performance Timing / Navigation Timing', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-performance-api', 'b3-resource-timing', 'Resource Timing API', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-performance-api', 'b3-user-timing', 'User Timing API (mark / measure)', 'tier2', M56, { tags: ['performance'] }),
    item('b3-perf-devtools', 'Performance Profiling with DevTools', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-perf-devtools', 'b3-flame-chart', 'Flame Chart Reading', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-perf-devtools', 'b3-main-thread-analysis', 'Main-Thread Analysis', 'tier1', M34, { tags: ['performance'] }),
    item('b3-runtime-performance', 'Runtime Performance Optimization', 'tier1', M34, { tags: ['performance'] }),
    item('b3-loading-performance', 'Loading Performance Optimization', 'tier1', M34, { tags: ['performance'] }),
  ]),

  section('B3.28', 'Resource Loading & Performance', 106, [
    item('b3-resource-hints', 'Resource Hints', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-resource-hints', 'b3-preload', 'preload', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-resource-hints', 'b3-prefetch', 'prefetch', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-resource-hints', 'b3-preconnect', 'preconnect & dns-prefetch', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-resource-hints', 'b3-modulepreload', 'modulepreload', 'tier2', M56, { tags: ['performance'] }),
    item('b3-lazy-loading', 'Lazy Loading', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-lazy-loading', 'b3-lazy-loading-images', 'loading="lazy" on Images', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-lazy-loading', 'b3-lazy-loading-iframes', 'Lazy Loading iframes', 'tier2', M56, { tags: ['performance'] }),
    item('b3-image-optimization', 'Image Optimization in Browser', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-image-optimization', 'b3-srcset-sizes', 'srcset & sizes', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-image-optimization', 'b3-picture-element', 'picture Element', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-image-optimization', 'b3-modern-image-formats', 'WebP / AVIF', 'tier2', M56, { tags: ['performance'] }),
    item('b3-font-loading-perf', 'Font Loading Performance', 'tier1', M34, { tags: ['performance'] }),
    item('b3-code-splitting-browser', 'Code Splitting in the Browser', 'tier1', M34, { tags: ['performance'] }),
    item('b3-bundle-size', 'Bundle Size & Tree Shaking Impact', 'tier1', M34, { tags: ['performance'] }),
  ]),

  section('B3.29', 'Navigation & SPA Browser Behavior', 107, [
    item('b3-spa-navigation', 'SPA Navigation in the Browser', 'tier1', M34, { tags: ['navigation'] }),
    nest('b3-spa-navigation', 'b3-client-side-routing', 'Client-Side Routing', 'tier1', M34, { tags: ['navigation'] }),
    nest('b3-spa-navigation', 'b3-history-api-spa', 'History API in SPAs', 'tier1', M34, { tags: ['navigation'] }),
    nest('b3-spa-navigation', 'b3-hash-routing', 'Hash-Based Routing', 'tier2', M56, { tags: ['navigation'] }),
    item('b3-scroll-restoration', 'Scroll Restoration', 'tier1', M34, { tags: ['navigation'] }),
    nest('b3-scroll-restoration', 'b3-history-scroll-restoration', 'history.scrollRestoration', 'tier1', M34, { tags: ['navigation'] }),
    item('b3-page-lifecycle', 'Page Lifecycle API', 'tier2', M56, { tags: ['navigation'] }),
    nest('b3-page-lifecycle', 'b3-page-visibility', 'Page Visibility (document.visibilityState)', 'tier1', M34, { tags: ['navigation'] }),
    nest('b3-page-lifecycle', 'b3-freeze-resume', 'freeze / resume Events', 'tier3', M78, { tags: ['navigation'] }),
    item('b3-bfcache', 'Back/Forward Cache (bfcache)', 'tier1', M34, { tags: ['navigation', 'performance'] }),
    nest('b3-bfcache', 'b3-bfcache-blockers', 'bfcache Blockers', 'tier1', M34, { tags: ['navigation', 'performance'] }),
    item('b3-hard-vs-soft-nav', 'Hard Navigation vs Soft Navigation', 'tier1', M34, { tags: ['navigation'] }),
  ]),

  section('B3.30', 'iframe & Cross-Document Communication', 108, [
    item('b3-iframes', 'iframe Fundamentals', 'tier1', M34),
    nest('b3-iframes', 'b3-iframe-sandbox', 'sandbox Attribute', 'tier1', M34, { tags: ['security'] }),
    nest('b3-iframes', 'b3-iframe-loading', 'iframe Loading & Lazy Loading', 'tier1', M34),
    nest('b3-iframes', 'b3-iframe-security', 'iframe Security Considerations', 'tier1', M34, { tags: ['security'] }),
    item('b3-postmessage', 'postMessage API', 'tier1', M34),
    nest('b3-postmessage', 'b3-postmessage-origin-check', 'Origin Validation', 'tier1', M34, { tags: ['security'] }),
    nest('b3-postmessage', 'b3-postmessage-structured-clone', 'Structured Clone Algorithm', 'tier1', M34),
    item('b3-window-opener', 'window.opener Security', 'tier1', M34, { tags: ['security'] }),
    nest('b3-window-opener', 'b3-rel-noopener', 'rel="noopener"', 'tier1', M34, { tags: ['security'] }),
    item('b3-channel-messaging', 'MessageChannel', 'tier2', M56),
    item('b3-broadcast-channel', 'BroadcastChannel', 'tier2', M56),
    item('b3-cross-document-embedding', 'Cross-Document Embedding Patterns', 'tier2', M56),
  ]),

  section('B3.31', 'URL & URL APIs', 109, [
    item('b3-url-parsing', 'URL Parsing & Structure', 'tier1', M34, { tags: ['navigation'] }),
    nest('b3-url-parsing', 'b3-url-components', 'scheme / host / port / path / query / hash', 'tier1', M34, { tags: ['navigation'] }),
    nest('b3-url-parsing', 'b3-url-encoding', 'URL Encoding (encodeURIComponent)', 'tier1', M34, { tags: ['navigation'] }),
    item('b3-url-api', 'URL API', 'tier1', M34, { tags: ['navigation'] }),
    nest('b3-url-api', 'b3-urlsearchparams', 'URLSearchParams', 'tier1', M34, { tags: ['navigation'] }),
    nest('b3-url-api', 'b3-url-base-relative', 'Base URLs & Relative Resolution', 'tier1', M34, { tags: ['navigation'] }),
    item('b3-url-canparse', 'URL.canParse()', 'tier2', M56, { tags: ['navigation'] }),
    item('b3-url-fragment-directives', 'URL Fragment Directives', 'tier3', M78, { tags: ['navigation'] }),
    item('b3-url-security', 'URL Security (javascript: / data: URLs)', 'tier1', M34, { tags: ['security'] }),
  ]),

  section('B3.32', 'Forms & Browser Input', 110, [
    item('b3-forms-browser', 'Forms in the Browser', 'tier1', M34),
    nest('b3-forms-browser', 'b3-form-submission', 'Form Submission (GET / POST)', 'tier1', M34),
    nest('b3-forms-browser', 'b3-form-validation', 'HTML5 Form Validation', 'tier1', M34),
    nest('b3-forms-browser', 'b3-constraint-validation', 'Constraint Validation API', 'tier1', M34),
    nest('b3-forms-browser', 'b3-checkvalidity-reportvalidity', 'checkValidity / reportValidity', 'tier1', M34),
    item('b3-input-types', 'Input Types & Browser Behavior', 'tier1', M34),
    nest('b3-input-types', 'b3-input-date-time', 'date / time / datetime-local', 'tier1', M34),
    nest('b3-input-types', 'b3-input-file', 'file Input', 'tier1', M34),
    nest('b3-input-types', 'b3-input-number-range', 'number / range', 'tier1', M34),
    item('b3-form-events-browser', 'Form Events (submit / reset / input / change)', 'tier1', M34, { tags: ['events'] }),
    item('b3-autocomplete', 'autocomplete Attribute', 'tier2', M56),
    item('b3-form-serialization', 'Form Serialization', 'tier1', M34),
    nest('b3-form-serialization', 'b3-formdata-api', 'FormData API', 'tier1', M34),
  ]),

  section('B3.33', 'Clipboard, Drag & Drop, Selection', 111, [
    item('b3-clipboard-api', 'Clipboard API', 'tier2', M56),
    nest('b3-clipboard-api', 'b3-clipboard-read-write', 'navigator.clipboard.readText / writeText', 'tier2', M56),
    nest('b3-clipboard-api', 'b3-clipboard-permissions', 'Clipboard Permissions', 'tier2', M56),
    item('b3-drag-drop', 'Drag & Drop API', 'tier2', M56),
    nest('b3-drag-drop', 'b3-drag-events-detail', 'dragstart / dragover / drop', 'tier2', M56),
    nest('b3-drag-drop', 'b3-data-transfer', 'dataTransfer Object', 'tier2', M56),
    item('b3-selection-api', 'Selection API', 'tier2', M56),
    nest('b3-selection-api', 'b3-window-getselection', 'window.getSelection()', 'tier2', M56),
    nest('b3-selection-api', 'b3-selection-ranges', 'Selection Ranges', 'tier3', M78),
    item('b3-contenteditable', 'contenteditable', 'tier2', M56),
  ]),

  section('B3.34', 'Permissions & Device APIs', 112, [
    item('b3-permissions-api', 'Permissions API', 'tier2', M56),
    nest('b3-permissions-api', 'b3-permission-query', 'navigator.permissions.query()', 'tier2', M56),
    nest('b3-permissions-api', 'b3-permission-lifecycle', 'Permission Lifecycle & Prompts', 'tier2', M56),
    item('b3-geolocation', 'Geolocation API', 'tier2', M56),
    item('b3-media-devices', 'MediaDevices (Camera / Microphone)', 'tier2', M56),
    nest('b3-media-devices', 'b3-getusermedia', 'getUserMedia()', 'tier2', M56),
    item('b3-notifications-api', 'Notifications API', 'tier2', M56),
    item('b3-vibration-api', 'Vibration API', 'tier3', M78),
    item('b3-battery-api', 'Battery Status API', 'tier3', M78),
    item('b3-device-orientation', 'Device Orientation / Motion', 'tier3', M78),
    item('b3-web-bluetooth-usb', 'Web Bluetooth / USB (Overview)', 'tier3', M78),
  ]),

  section('B3.35', 'Accessibility Tree & Focus', 113, [
    item('b3-accessibility-tree', 'Accessibility Tree', 'tier1', M34, { tags: ['a11y'] }),
    nest('b3-accessibility-tree', 'b3-a11y-tree-construction', 'How the Accessibility Tree Is Built', 'tier1', M34, { tags: ['a11y'] }),
    nest('b3-accessibility-tree', 'b3-a11y-roles', 'ARIA Roles in the Browser', 'tier1', M34, { tags: ['a11y'] }),
    nest('b3-accessibility-tree', 'b3-a11y-name-description', 'Accessible Name & Description', 'tier1', M34, { tags: ['a11y'] }),
    item('b3-focus-management', 'Focus Management', 'tier1', M34, { tags: ['a11y'] }),
    nest('b3-focus-management', 'b3-tabindex', 'tabindex', 'tier1', M34, { tags: ['a11y'] }),
    nest('b3-focus-management', 'b3-focus-trap', 'Focus Trap Pattern', 'tier1', M34, { tags: ['a11y'] }),
    nest('b3-focus-management', 'b3-focus-visible', ':focus-visible', 'tier1', M34, { tags: ['a11y'] }),
    nest('b3-focus-management', 'b3-programmatic-focus', 'element.focus() / blur()', 'tier1', M34, { tags: ['a11y'] }),
    item('b3-keyboard-navigation', 'Keyboard Navigation', 'tier1', M34, { tags: ['a11y'] }),
    nest('b3-keyboard-navigation', 'b3-roving-tabindex', 'Roving Tabindex', 'tier2', M56, { tags: ['a11y'] }),
    item('b3-live-regions', 'Live Regions (aria-live)', 'tier1', M34, { tags: ['a11y'] }),
    item('b3-screen-reader-browser', 'Screen Reader Browser Interaction', 'tier2', M56, { tags: ['a11y'] }),
  ]),

  section('B3.36', 'Browser Developer Tools', 114, [
    item('b3-devtools-overview', 'Browser DevTools Overview', 'tier1', M34),
    item('b3-devtools-elements', 'Elements Panel', 'tier1', M34),
    nest('b3-devtools-elements', 'b3-devtools-dom-inspector', 'DOM Inspector & Styles', 'tier1', M34),
    nest('b3-devtools-elements', 'b3-devtools-computed-layout', 'Computed Styles & Layout', 'tier1', M34),
    nest('b3-devtools-elements', 'b3-devtools-event-listeners', 'Event Listeners Panel', 'tier1', M34),
    item('b3-devtools-console', 'Console Panel', 'tier1', M34),
    nest('b3-devtools-console', 'b3-console-logging-levels', 'Logging Levels & Filtering', 'tier1', M34),
    nest('b3-devtools-console', 'b3-console-live-expressions', 'Live Expressions', 'tier2', M56),
    item('b3-devtools-network', 'Network Panel', 'tier1', M34, { tags: ['http'] }),
    nest('b3-devtools-network', 'b3-network-waterfall', 'Network Waterfall Analysis', 'tier1', M34, { tags: ['http'] }),
    nest('b3-devtools-network', 'b3-network-throttling', 'Network Throttling', 'tier1', M34, { tags: ['http'] }),
    nest('b3-devtools-network', 'b3-network-initiator', 'Request Initiator Chain', 'tier1', M34, { tags: ['http'] }),
    item('b3-devtools-performance', 'Performance Panel', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-devtools-performance', 'b3-devtools-record-profile', 'Recording & Profiling', 'tier1', M34, { tags: ['performance'] }),
    nest('b3-devtools-performance', 'b3-devtools-performance-insights', 'Performance Insights', 'tier1', M34, { tags: ['performance'] }),
    item('b3-devtools-application', 'Application Panel', 'tier1', M34, { tags: ['storage'] }),
    nest('b3-devtools-application', 'b3-devtools-storage-inspector', 'Storage Inspector (Cookies, LS, IDB)', 'tier1', M34, { tags: ['storage'] }),
    nest('b3-devtools-application', 'b3-devtools-service-workers', 'Service Workers in DevTools', 'tier2', M56),
    item('b3-devtools-sources', 'Sources Panel & Debugging', 'tier1', M34),
    nest('b3-devtools-sources', 'b3-devtools-breakpoints', 'Breakpoints & Conditional Breakpoints', 'tier1', M34),
    nest('b3-devtools-sources', 'b3-devtools-source-maps', 'Source Maps in DevTools', 'tier1', M34),
    item('b3-devtools-lighthouse', 'Lighthouse in DevTools', 'tier1', M34, { tags: ['performance'] }),
    item('b3-devtools-memory', 'Memory Panel', 'tier2', M56),
    nest('b3-devtools-memory', 'b3-devtools-heap-snapshot', 'Heap Snapshots', 'tier2', M56),
  ]),

  section('B3.37', 'Browser Interview Scenarios', 115, [
    item('b3-interview-rendering-path', 'Explain the Critical Rendering Path', 'tier1', M34, { tags: ['interview'] }),
    item('b3-interview-reflow-repaint', 'What Triggers Reflow vs Repaint?', 'tier1', M34, { tags: ['interview', 'performance'] }),
    item('b3-interview-event-loop', 'Browser Event Loop & Rendering', 'tier1', M34, { tags: ['interview', 'performance'] }),
    item('b3-interview-cors', 'Explain CORS End-to-End', 'tier1', M34, { tags: ['interview', 'security'] }),
    item('b3-interview-same-origin', 'Same-Origin Policy Scenarios', 'tier1', M34, { tags: ['interview', 'security'] }),
    item('b3-interview-cookies-vs-storage', 'Cookies vs localStorage vs sessionStorage', 'tier1', M34, { tags: ['interview', 'storage'] }),
    item('b3-interview-xss-csrf', 'XSS vs CSRF — Prevention', 'tier1', M34, { tags: ['interview', 'security'] }),
    item('b3-interview-http-caching', 'HTTP Caching Strategy Design', 'tier1', M34, { tags: ['interview', 'http'] }),
    item('b3-interview-fetch-abort', 'Fetch Cancellation & Race Conditions', 'tier1', M34, { tags: ['interview', 'http'] }),
    item('b3-interview-observers', 'When to Use Each Observer API', 'tier1', M34, { tags: ['interview'] }),
    item('b3-interview-web-workers', 'Web Workers vs Service Workers', 'tier1', M34, { tags: ['interview'] }),
    item('b3-interview-websockets-sse', 'WebSockets vs SSE vs Polling', 'tier2', M56, { tags: ['interview'] }),
    item('b3-interview-core-web-vitals', 'Improve LCP / INP / CLS', 'tier1', M34, { tags: ['interview', 'performance'] }),
    item('b3-interview-spa-navigation', 'SPA Navigation & bfcache', 'tier1', M34, { tags: ['interview', 'navigation'] }),
    item('b3-interview-debounce-raf', 'Debounce vs rAF vs setTimeout', 'tier1', M34, { tags: ['interview', 'performance'] }),
    item('b3-interview-postmessage-security', 'Secure postMessage Patterns', 'tier2', M56, { tags: ['interview', 'security'] }),
    item('b3-interview-layout-thrashing', 'Detect & Fix Layout Thrashing', 'tier1', M34, { tags: ['interview', 'performance'] }),
    item('b3-interview-script-loading', 'async vs defer vs module', 'tier1', M34, { tags: ['interview', 'rendering'] }),
    item('b3-interview-csp-design', 'Design a CSP for a SPA', 'tier2', M56, { tags: ['interview', 'security'] }),
    item('b3-interview-browser-architecture', 'Browser Process Architecture', 'tier1', M34, { tags: ['interview', 'architecture'] }),
  ]),
]
