import type { SectionSeed } from './build'
import { TRACK_C_BOOT_SECTIONS } from './track-c-boot'
import { TRACK_C_CONCURRENCY_SECTIONS } from './track-c-concurrency'
import { TRACK_C_JAVA_SECTIONS } from './track-c-java'
import { TRACK_C_JVM_SECTIONS } from './track-c-jvm'
import { TRACK_C_NETWORKING_SECTIONS } from './track-c-networking'
import { TRACK_C_SQL_SECTIONS } from './track-c-sql'
import { TRACK_C_SPRING_SECTIONS } from './track-c-spring'

/** Track C — Java & Backend Engineering. C1 Core Java, then JVM through observability. */
export const TRACK_C_SECTIONS: SectionSeed[] = [
  ...TRACK_C_JAVA_SECTIONS,
  ...TRACK_C_JVM_SECTIONS,
  ...TRACK_C_CONCURRENCY_SECTIONS,
  ...TRACK_C_NETWORKING_SECTIONS,
  ...TRACK_C_SPRING_SECTIONS,
  ...TRACK_C_BOOT_SECTIONS,
  ...TRACK_C_SQL_SECTIONS,
  {
    id: 'C8',
    track: 'C',
    title: 'JPA / Hibernate',
    order: 119,
    defaultKind: 'theory',
    defaultDepth: 'deep',
    topics: [
      { id: 'c8-entities', title: 'Entities', priority: 'tier1', months: [3, 4], tags: ['jpa'] },
      { id: 'c8-relationships', title: 'Relationships', priority: 'tier1', months: [3, 4], tags: ['jpa'] },
      { id: 'c8-repositories', title: 'Repositories', priority: 'tier1', months: [3, 4], tags: ['jpa'] },
      { id: 'c8-persistence-context', title: 'Persistence Context', priority: 'tier1', months: [3, 4], tags: ['jpa'], depth: 'deep' },
      { id: 'c8-entity-lifecycle', title: 'Entity Lifecycle', priority: 'tier1', months: [3, 4], tags: ['jpa'] },
      { id: 'c8-lazy-loading', title: 'Lazy/Eager Loading', priority: 'tier1', months: [3, 4], tags: ['jpa'] },
      { id: 'c8-eager-loading', title: 'Eager Loading', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'c8-lazy-loading', months: [3, 4], tags: ['jpa'] },
      { id: 'c8-nplus1', title: 'N+1 Problem', priority: 'tier1', months: [3, 4], tags: ['jpa'] },
      { id: 'c8-transactions', title: 'JPA Transactions', priority: 'tier1', months: [3, 4], tags: ['jpa'], related: ['c7-transactions'] },
      { id: 'c8-dirty-checking', title: 'Dirty Checking', priority: 'tier1', months: [3, 4], tags: ['jpa'] },
      { id: 'c8-fetch-joins', title: 'Fetch Joins', priority: 'tier1', months: [3, 4], tags: ['jpa'] },
      { id: 'c8-optimistic-locking', title: 'Optimistic/Pessimistic Locking', priority: 'tier1', months: [3, 4], tags: ['jpa'], related: ['c7-isolation-levels'], capstone: 'Versioned seat/inventory updates under concurrent booking attempts.' },
      { id: 'c8-pessimistic-locking', title: 'Pessimistic Locking', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'c8-optimistic-locking', months: [3, 4], tags: ['jpa'], related: ['c7-locks'] },
      { id: 'c8-orm-abuse', title: 'Avoiding ORM Abuse', priority: 'tier1', months: [3, 4], tags: ['jpa'] },
    ],
  },
  {
    id: 'C9',
    track: 'C',
    title: 'Security',
    order: 120,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'c9-authentication', title: 'Authentication vs Authorization', priority: 'tier1', months: [4, 5], tags: ['security'] },
      { id: 'c9-spring-security', title: 'Spring Security', priority: 'tier1', months: [4, 5], tags: ['security', 'spring'] },
      { id: 'c9-sessions', title: 'Sessions (Security)', priority: 'tier1', months: [4, 5], tags: ['security'] },
      { id: 'c9-jwt', title: 'JWT', priority: 'tier1', months: [4, 5], tags: ['security'] },
      { id: 'c9-oauth2', title: 'OAuth 2.0 Concepts', priority: 'tier1', months: [4, 5], tags: ['security'] },
      { id: 'c9-oidc', title: 'OpenID Connect Concepts', priority: 'tier1', months: [4, 5], tags: ['security'] },
      { id: 'c9-rbac', title: 'RBAC', priority: 'tier1', months: [4, 5], tags: ['security'] },
      { id: 'c9-password-hashing', title: 'Password Hashing', priority: 'tier1', months: [4, 5], tags: ['security'] },
      { id: 'c9-csrf', title: 'CSRF', priority: 'tier1', months: [4, 5], tags: ['security'] },
      { id: 'c9-xss', title: 'XSS', priority: 'tier1', months: [4, 5], tags: ['security'] },
      { id: 'c9-sql-injection', title: 'SQL Injection', priority: 'tier1', months: [4, 5], tags: ['security'] },
      { id: 'c9-cors-security', title: 'CORS (Security)', priority: 'tier1', months: [4, 5], tags: ['security'], related: ['c4-cors'] },
      { id: 'c9-secrets', title: 'Secrets Management', priority: 'tier1', months: [4, 5], tags: ['security'] },
      { id: 'c9-owasp', title: 'OWASP Basics', priority: 'tier1', months: [4, 5], tags: ['security'] },
    ],
  },
  {
    id: 'C10',
    track: 'C',
    title: 'Redis',
    order: 121,
    defaultKind: 'theory',
    defaultDepth: 'deep',
    topics: [
      { id: 'c10-data-structures', title: 'Redis Data Structures', priority: 'tier1', months: [5, 6], tags: ['redis'] },
      { id: 'c10-cache-aside', title: 'Cache-Aside', priority: 'tier1', months: [5, 6], tags: ['redis', 'caching'] },
      { id: 'c10-ttl', title: 'TTL', priority: 'tier1', months: [5, 6], tags: ['redis'] },
      { id: 'c10-invalidation', title: 'Cache Invalidation', priority: 'tier1', months: [5, 6], tags: ['redis', 'caching'], related: ['d7-cache-invalidation'] },
      { id: 'c10-distributed-caching', title: 'Distributed Caching', priority: 'tier1', months: [5, 6], tags: ['redis'], related: ['d5-caching'] },
      { id: 'c10-rate-limiting', title: 'Rate Limiting with Redis', priority: 'tier1', months: [5, 6], tags: ['redis'], related: ['d10-rate-limiter'], capstone: 'Relevant to inventory/cache/rate-limiting decisions for flash sales.' },
      { id: 'c10-when-not-to-cache', title: 'When Not to Cache', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'c10-cache-aside', months: [5, 6], tags: ['redis'] },
      { id: 'c10-distributed-locks', title: 'Distributed Locks', priority: 'tier2', months: [5, 6], tags: ['redis'] },
      { id: 'c10-pubsub', title: 'Pub/Sub', priority: 'tier2', months: [5, 6], tags: ['redis'] },
      { id: 'c10-persistence', title: 'Redis Persistence', priority: 'tier2', months: [5, 6], tags: ['redis'] },
      { id: 'c10-replication', title: 'Redis Replication', priority: 'tier2', months: [5, 6], tags: ['redis'] },
    ],
  },
  {
    id: 'C11',
    track: 'C',
    title: 'Kafka & Event-Driven Systems',
    order: 122,
    defaultKind: 'theory',
    defaultDepth: 'deep',
    topics: [
      { id: 'c11-eda', title: 'Event-Driven Architecture', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-topics', title: 'Topics', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-partitions', title: 'Partitions', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-producers', title: 'Producers', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-consumers', title: 'Consumers', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-consumer-groups', title: 'Consumer Groups', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-offsets', title: 'Offsets', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-ordering', title: 'Ordering Guarantees', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-at-most-once', title: 'At-Most/At-Least/Exactly-Once Concepts', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-at-least-once', title: 'At-Least-Once', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'c11-at-most-once', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-exactly-once', title: 'Exactly-Once Concepts', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'c11-at-most-once', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-idempotent-consumers', title: 'Idempotent Consumers', priority: 'tier1', months: [5, 6], tags: ['kafka'], related: ['c12-idempotency'], capstone: 'Relevant to duplicate payment/order events.' },
      { id: 'c11-retries', title: 'Retries', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-dlq', title: 'Dead-Letter Queues', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-schema-evolution', title: 'Schema Evolution', priority: 'tier1', months: [5, 6], tags: ['kafka'] },
      { id: 'c11-internals', title: 'Kafka Internals', priority: 'tier2', months: [6, 7], tags: ['kafka'] },
      { id: 'c11-rebalancing', title: 'Consumer Rebalancing', priority: 'tier2', months: [6, 7], tags: ['kafka'] },
      { id: 'c11-outbox', title: 'Outbox Pattern', priority: 'tier2', months: [6, 7], tags: ['kafka'], related: ['d4-distributed-transactions'] },
      { id: 'c11-saga', title: 'Saga Pattern', priority: 'tier2', months: [6, 7], tags: ['kafka'], related: ['d4-saga'] },
    ],
  },
  {
    id: 'C12',
    track: 'C',
    title: 'Backend Reliability',
    order: 123,
    defaultKind: 'theory',
    defaultDepth: 'deep',
    topics: [
      { id: 'c12-timeouts', title: 'Timeouts', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
      { id: 'c12-retries', title: 'Retries', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
      { id: 'c12-exponential-backoff', title: 'Exponential Backoff', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
      { id: 'c12-idempotency', title: 'Idempotency', priority: 'tier1', months: [5, 6], tags: ['reliability'], related: ['c11-idempotent-consumers', 'd4-idempotency'], capstone: 'Critical for payment and booking retries without double charges.' },
      { id: 'c12-rate-limiting', title: 'Rate Limiting', priority: 'tier1', months: [5, 6], tags: ['reliability'], related: ['d10-rate-limiter'] },
      { id: 'c12-circuit-breakers', title: 'Circuit Breakers', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
      { id: 'c12-graceful-degradation', title: 'Graceful Degradation', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
      { id: 'c12-health-checks', title: 'Health Checks', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
      { id: 'c12-bulkheads', title: 'Bulkheads', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
      { id: 'c12-backpressure', title: 'Backpressure', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
      { id: 'c12-eventual-consistency', title: 'Eventual Consistency', priority: 'tier1', months: [5, 6], tags: ['reliability'], related: ['d4-eventual-consistency'] },
      { id: 'c12-failure-recovery', title: 'Failure Recovery', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
    ],
  },
  {
    id: 'C13',
    track: 'C',
    title: 'Testing',
    order: 124,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'c13-unit-testing', title: 'Unit Testing', priority: 'tier1', months: [3, 4], tags: ['testing'] },
      { id: 'c13-junit', title: 'JUnit', priority: 'tier1', months: [3, 4], tags: ['testing'] },
      { id: 'c13-mockito', title: 'Mockito', priority: 'tier1', months: [3, 4], tags: ['testing'] },
      { id: 'c13-integration-testing', title: 'Integration Testing', priority: 'tier1', months: [3, 4], tags: ['testing'] },
      { id: 'c13-api-testing', title: 'API Testing', priority: 'tier1', months: [3, 4], tags: ['testing'] },
      { id: 'c13-database-testing', title: 'Database Testing', priority: 'tier1', months: [3, 4], tags: ['testing'] },
      { id: 'c13-testcontainers', title: 'Testcontainers', priority: 'tier2', months: [5, 6], tags: ['testing'] },
      { id: 'c13-contract-testing', title: 'Contract Testing', priority: 'tier2', months: [5, 6], tags: ['testing'] },
      { id: 'c13-load-testing', title: 'Load Testing', priority: 'tier2', months: [7, 8], tags: ['testing'] },
    ],
  },
  {
    id: 'C14',
    track: 'C',
    title: 'Docker / DevOps',
    order: 125,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'c14-linux', title: 'Linux Fundamentals', priority: 'tier1', months: [7, 8], tags: ['devops'] },
      { id: 'c14-processes', title: 'Processes', priority: 'tier1', months: [7, 8], tags: ['devops'] },
      { id: 'c14-permissions', title: 'Files/Permissions', priority: 'tier1', months: [7, 8], tags: ['devops'] },
      { id: 'c14-env-vars', title: 'Environment Variables', priority: 'tier1', months: [7, 8], tags: ['devops'] },
      { id: 'c14-docker-images', title: 'Docker Images', priority: 'tier1', months: [7, 8], tags: ['docker'] },
      { id: 'c14-containers', title: 'Containers', priority: 'tier1', months: [7, 8], tags: ['docker'] },
      { id: 'c14-dockerfile', title: 'Dockerfile', priority: 'tier1', months: [7, 8], tags: ['docker'] },
      { id: 'c14-compose', title: 'Docker Compose', priority: 'tier1', months: [7, 8], tags: ['docker'] },
      { id: 'c14-networking', title: 'Docker Networking', priority: 'tier1', months: [7, 8], tags: ['docker'] },
      { id: 'c14-volumes', title: 'Volumes', priority: 'tier1', months: [7, 8], tags: ['docker'] },
      { id: 'c14-multi-stage', title: 'Multi-stage Builds', priority: 'tier1', months: [7, 8], tags: ['docker'] },
      { id: 'c14-cicd', title: 'CI/CD Concepts', priority: 'tier1', months: [7, 8], tags: ['devops'] },
      { id: 'c14-github-actions', title: 'GitHub Actions / Jenkins', priority: 'tier2', months: [7, 8], tags: ['devops'] },
      { id: 'c14-kubernetes', title: 'Kubernetes', priority: 'tier3', months: [10, 12], tags: ['devops'] },
    ],
  },
  {
    id: 'C15',
    track: 'C',
    title: 'AWS / Cloud',
    order: 126,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'c15-ec2', title: 'EC2', priority: 'tier1', months: [7, 8], tags: ['aws'] },
      { id: 'c15-s3', title: 'S3', priority: 'tier1', months: [7, 8], tags: ['aws'] },
      { id: 'c15-rds', title: 'RDS', priority: 'tier1', months: [7, 8], tags: ['aws'] },
      { id: 'c15-vpc', title: 'VPC Fundamentals', priority: 'tier1', months: [7, 8], tags: ['aws'] },
      { id: 'c15-iam', title: 'IAM', priority: 'tier1', months: [7, 8], tags: ['aws'] },
      { id: 'c15-load-balancers', title: 'Load Balancers (AWS)', priority: 'tier1', months: [7, 8], tags: ['aws'] },
      { id: 'c15-auto-scaling', title: 'Auto Scaling', priority: 'tier1', months: [7, 8], tags: ['aws'] },
      { id: 'c15-cloudwatch', title: 'CloudWatch', priority: 'tier1', months: [7, 8], tags: ['aws'] },
      { id: 'c15-ecs', title: 'ECS', priority: 'tier2', months: [8, 9], tags: ['aws'] },
      { id: 'c15-lambda', title: 'Lambda', priority: 'tier2', months: [8, 9], tags: ['aws'] },
      { id: 'c15-sqs', title: 'SQS', priority: 'tier2', months: [8, 9], tags: ['aws'] },
      { id: 'c15-sns', title: 'SNS', priority: 'tier2', months: [8, 9], tags: ['aws'] },
      { id: 'c15-route53', title: 'Route 53', priority: 'tier2', months: [8, 9], tags: ['aws'] },
      { id: 'c15-cloudfront', title: 'CloudFront', priority: 'tier2', months: [8, 9], tags: ['aws'] },
      { id: 'c15-secrets-manager', title: 'Secrets Manager', priority: 'tier2', months: [8, 9], tags: ['aws'] },
      { id: 'c15-eks', title: 'EKS', priority: 'tier3', months: [10, 12], tags: ['aws'] },
    ],
  },
  {
    id: 'C16',
    track: 'C',
    title: 'Observability',
    order: 127,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'c16-structured-logging', title: 'Structured Logging', priority: 'tier1', months: [7, 8], tags: ['observability'] },
      { id: 'c16-metrics', title: 'Metrics', priority: 'tier1', months: [7, 8], tags: ['observability'] },
      { id: 'c16-tracing', title: 'Distributed Tracing', priority: 'tier1', months: [7, 8], tags: ['observability'] },
      { id: 'c16-correlation-ids', title: 'Correlation IDs', priority: 'tier1', months: [7, 8], tags: ['observability'] },
      { id: 'c16-health-metrics', title: 'Health Metrics', priority: 'tier1', months: [7, 8], tags: ['observability'] },
      { id: 'c16-latency-percentiles', title: 'Latency Percentiles', priority: 'tier1', months: [7, 8], tags: ['observability'] },
      { id: 'c16-error-rates', title: 'Error Rates', priority: 'tier1', months: [7, 8], tags: ['observability'] },
      { id: 'c16-throughput', title: 'Throughput', priority: 'tier1', months: [7, 8], tags: ['observability'] },
      { id: 'c16-otel', title: 'OpenTelemetry Concepts', priority: 'tier1', months: [7, 8], tags: ['observability'] },
      { id: 'c16-prometheus', title: 'Prometheus', priority: 'tier2', months: [8, 9], tags: ['observability'] },
      { id: 'c16-grafana', title: 'Grafana', priority: 'tier2', months: [8, 9], tags: ['observability'] },
    ],
  },
]
