import type { SectionSeed } from './build'

/** Track D — LLD, System Design & Distributed Systems */
export const TRACK_D_SECTIONS: SectionSeed[] = [
  {
    id: 'D1',
    track: 'D',
    title: 'Object-Oriented Design',
    order: 1,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'd1-encapsulation', title: 'Encapsulation', priority: 'tier1', months: [1, 2], tags: ['ood'], related: ['c1-encapsulation'] },
      { id: 'd1-abstraction', title: 'Abstraction', priority: 'tier1', months: [1, 2], tags: ['ood'] },
      { id: 'd1-composition-vs-inheritance', title: 'Composition vs Inheritance', priority: 'tier1', months: [1, 2], tags: ['ood'] },
      { id: 'd1-solid', title: 'SOLID', priority: 'tier1', months: [1, 2], tags: ['ood'] },
      { id: 'd1-coupling-cohesion', title: 'Coupling/Cohesion', priority: 'tier1', months: [1, 2], tags: ['ood'] },
      { id: 'd1-interfaces', title: 'Interfaces (Design)', priority: 'tier1', months: [1, 2], tags: ['ood'] },
      { id: 'd1-immutability', title: 'Immutability (Design)', priority: 'tier1', months: [1, 2], tags: ['ood'], related: ['c1-immutability'] },
    ],
  },
  {
    id: 'D2',
    track: 'D',
    title: 'Design Patterns',
    order: 2,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'd2-strategy', title: 'Strategy', priority: 'tier1', months: [2, 3], tags: ['patterns'] },
      { id: 'd2-factory', title: 'Factory', priority: 'tier1', months: [2, 3], tags: ['patterns'] },
      { id: 'd2-builder', title: 'Builder', priority: 'tier1', months: [2, 3], tags: ['patterns'] },
      { id: 'd2-observer', title: 'Observer', priority: 'tier1', months: [2, 3], tags: ['patterns'] },
      { id: 'd2-adapter', title: 'Adapter', priority: 'tier1', months: [2, 3], tags: ['patterns'] },
      { id: 'd2-decorator', title: 'Decorator', priority: 'tier1', months: [2, 3], tags: ['patterns'] },
      { id: 'd2-facade', title: 'Facade', priority: 'tier1', months: [2, 3], tags: ['patterns'] },
      { id: 'd2-command', title: 'Command', priority: 'tier2', months: [3, 4], tags: ['patterns'] },
      { id: 'd2-template-method', title: 'Template Method', priority: 'tier2', months: [3, 4], tags: ['patterns'] },
      { id: 'd2-chain-of-responsibility', title: 'Chain of Responsibility', priority: 'tier2', months: [3, 4], tags: ['patterns'] },
      { id: 'd2-state', title: 'State', priority: 'tier2', months: [3, 4], tags: ['patterns'] },
      { id: 'd2-proxy', title: 'Proxy', priority: 'tier2', months: [3, 4], tags: ['patterns'], related: ['c5-proxies'] },
      { id: 'd2-visitor', title: 'Visitor', priority: 'tier3', months: [5, 6], tags: ['patterns'] },
    ],
  },
  {
    id: 'D3',
    track: 'D',
    title: 'LLD Interview Problems',
    order: 3,
    defaultKind: 'lld',
    defaultDepth: 'deep',
    topics: [
      { id: 'd3-parking-lot', title: 'Parking Lot', priority: 'tier1', months: [2, 4], tags: ['lld'] },
      { id: 'd3-elevator', title: 'Elevator', priority: 'tier1', months: [2, 4], tags: ['lld'] },
      { id: 'd3-library', title: 'Library', priority: 'tier1', months: [2, 4], tags: ['lld'] },
      { id: 'd3-vending-machine', title: 'Vending Machine', priority: 'tier1', months: [2, 4], tags: ['lld'] },
      { id: 'd3-tic-tac-toe', title: 'Tic-Tac-Toe', priority: 'tier1', months: [2, 4], tags: ['lld'] },
      { id: 'd3-chess', title: 'Chess', priority: 'tier1', months: [3, 4], tags: ['lld'] },
      { id: 'd3-splitwise', title: 'Splitwise', priority: 'tier1', months: [3, 4], tags: ['lld'] },
      { id: 'd3-atm', title: 'ATM', priority: 'tier1', months: [3, 4], tags: ['lld'] },
      { id: 'd3-notification-service', title: 'Notification Service (LLD)', priority: 'tier1', months: [3, 4], tags: ['lld'] },
      { id: 'd3-logging-framework', title: 'Logging Framework', priority: 'tier1', months: [3, 4], tags: ['lld'] },
      { id: 'd3-rate-limiter-lld', title: 'Rate Limiter (LLD)', priority: 'tier1', months: [3, 4], tags: ['lld'], related: ['d10-rate-limiter'] },
      { id: 'd3-cache', title: 'Cache (LLD)', priority: 'tier1', months: [3, 4], tags: ['lld'], related: ['a4-lru-style', 'c10-cache-aside'] },
      { id: 'd3-movie-ticket-booking', title: 'Movie Ticket Booking (LLD)', priority: 'tier2', months: [4, 5], tags: ['lld'], related: ['d10-ticket-booking'] },
      { id: 'd3-food-delivery', title: 'Food Delivery (LLD)', priority: 'tier2', months: [4, 5], tags: ['lld'] },
    ],
  },
  {
    id: 'D4',
    track: 'D',
    title: 'Distributed Systems Fundamentals',
    order: 4,
    defaultKind: 'theory',
    defaultDepth: 'deep',
    topics: [
      { id: 'd4-horizontal-vs-vertical', title: 'Horizontal vs Vertical Scaling', priority: 'tier1', months: [3, 5], tags: ['distributed'] },
      { id: 'd4-stateless-vs-stateful', title: 'Stateless vs Stateful Services', priority: 'tier1', months: [3, 5], tags: ['distributed'] },
      { id: 'd4-load-balancing', title: 'Load Balancing', priority: 'tier1', months: [3, 5], tags: ['distributed'], related: ['c4-load-balancers'] },
      { id: 'd4-replication', title: 'Replication', priority: 'tier1', months: [3, 5], tags: ['distributed'], related: ['c7-replication'] },
      { id: 'd4-partitioning', title: 'Partitioning/Sharding', priority: 'tier1', months: [3, 5], tags: ['distributed'] },
      { id: 'd4-consistency', title: 'Consistency', priority: 'tier1', months: [3, 5], tags: ['distributed'] },
      { id: 'd4-availability', title: 'Availability', priority: 'tier1', months: [3, 5], tags: ['distributed'] },
      { id: 'd4-cap', title: 'CAP Theorem', priority: 'tier1', months: [3, 5], tags: ['distributed'] },
      { id: 'd4-strong-consistency', title: 'Strong/Eventual Consistency', priority: 'tier1', months: [3, 5], tags: ['distributed'] },
      { id: 'd4-eventual-consistency', title: 'Eventual Consistency', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'd4-strong-consistency', months: [3, 5], tags: ['distributed'], related: ['c12-eventual-consistency'] },
      { id: 'd4-quorums', title: 'Quorums Conceptually', priority: 'tier1', months: [4, 5], tags: ['distributed'] },
      { id: 'd4-leader-follower', title: 'Leader/Follower Architecture', priority: 'tier1', months: [4, 5], tags: ['distributed'] },
      { id: 'd4-consensus', title: 'Consensus Concepts', priority: 'tier1', months: [4, 5], tags: ['distributed'] },
      { id: 'd4-distributed-transactions', title: 'Distributed Transactions', priority: 'tier1', months: [4, 5], tags: ['distributed'], related: ['c11-outbox', 'c11-saga'] },
      { id: 'd4-idempotency', title: 'Idempotency (Distributed)', priority: 'tier1', months: [4, 5], tags: ['distributed'], related: ['c12-idempotency'] },
      { id: 'd4-delivery-semantics', title: 'Message-Delivery Semantics', priority: 'tier1', months: [4, 5], tags: ['distributed'], related: ['c11-at-least-once'] },
      { id: 'd4-failure-modes', title: 'Failure Modes', priority: 'tier1', months: [4, 5], tags: ['distributed'] },
      { id: 'd4-distributed-time', title: 'Distributed Clock/Time Issues', priority: 'tier1', months: [4, 5], tags: ['distributed'] },
      { id: 'd4-consistent-hashing', title: 'Consistent Hashing', priority: 'tier2', months: [5, 6], tags: ['distributed'] },
      { id: 'd4-leader-election', title: 'Leader Election', priority: 'tier2', months: [5, 6], tags: ['distributed'] },
      { id: 'd4-gossip', title: 'Gossip Protocols', priority: 'tier2', months: [5, 6], tags: ['distributed'] },
      { id: 'd4-2pc', title: 'Two-Phase Commit', priority: 'tier2', months: [5, 6], tags: ['distributed'] },
      { id: 'd4-saga', title: 'Saga', priority: 'tier2', months: [5, 6], tags: ['distributed'], related: ['c11-saga'] },
      { id: 'd4-raft', title: 'Raft Details', priority: 'tier3', months: [8, 10], tags: ['distributed'] },
    ],
  },
  {
    id: 'D5',
    track: 'D',
    title: 'Data/System Architecture',
    order: 5,
    defaultKind: 'theory',
    defaultDepth: 'deep',
    topics: [
      { id: 'd5-sql-vs-nosql', title: 'SQL vs NoSQL', priority: 'tier1', months: [3, 4], tags: ['data'] },
      { id: 'd5-relational', title: 'Relational Databases', priority: 'tier1', months: [3, 4], tags: ['data'], related: ['c7-schema-design'] },
      { id: 'd5-key-value', title: 'Key-Value Stores', priority: 'tier1', months: [3, 4], tags: ['data'], related: ['c10-data-structures'] },
      { id: 'd5-document', title: 'Document Databases', priority: 'tier1', months: [3, 4], tags: ['data'] },
      { id: 'd5-wide-column', title: 'Wide-Column Stores Conceptually', priority: 'tier1', months: [3, 4], tags: ['data'] },
      { id: 'd5-search', title: 'Search Engines Conceptually', priority: 'tier1', months: [3, 4], tags: ['data'] },
      { id: 'd5-caching', title: 'Caching', priority: 'tier1', months: [3, 5], tags: ['data'], related: ['c10-cache-aside'] },
      { id: 'd5-cdn', title: 'CDN', priority: 'tier1', months: [3, 5], tags: ['data'] },
      { id: 'd5-object-storage', title: 'Blob/Object Storage', priority: 'tier1', months: [3, 5], tags: ['data'], related: ['c15-s3'] },
      { id: 'd5-queues', title: 'Queues', priority: 'tier1', months: [3, 5], tags: ['data'] },
      { id: 'd5-streams', title: 'Streams', priority: 'tier1', months: [3, 5], tags: ['data'], related: ['c11-eda'] },
      { id: 'd5-db-replication', title: 'Database Replication', priority: 'tier1', months: [4, 5], tags: ['data'], related: ['d4-replication'] },
      { id: 'd5-sharding', title: 'Sharding', priority: 'tier1', months: [4, 5], tags: ['data'], related: ['d4-partitioning'] },
      { id: 'd5-read-replicas', title: 'Read Replicas', priority: 'tier1', months: [4, 5], tags: ['data'] },
      { id: 'd5-data-partitioning', title: 'Data Partitioning', priority: 'tier1', months: [4, 5], tags: ['data'] },
      { id: 'd5-hot-partitions', title: 'Hot Partitions', priority: 'tier1', months: [4, 5], tags: ['data'] },
      { id: 'd5-retention', title: 'Data Retention', priority: 'tier1', months: [4, 5], tags: ['data'] },
    ],
  },
  {
    id: 'D6',
    track: 'D',
    title: 'API Design',
    order: 6,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'd6-rest', title: 'REST', priority: 'tier1', months: [3, 4], tags: ['api'], related: ['c4-rest'] },
      { id: 'd6-resource-modelling', title: 'Resource Modelling', priority: 'tier1', months: [3, 4], tags: ['api'] },
      { id: 'd6-pagination', title: 'Pagination (API)', priority: 'tier1', months: [3, 4], tags: ['api'] },
      { id: 'd6-filtering', title: 'Filtering/Sorting', priority: 'tier1', months: [3, 4], tags: ['api'] },
      { id: 'd6-sorting', title: 'Sorting (API)', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'd6-filtering', months: [3, 4], tags: ['api'] },
      { id: 'd6-versioning', title: 'Versioning', priority: 'tier1', months: [3, 4], tags: ['api'] },
      { id: 'd6-idempotency', title: 'Idempotency (API)', priority: 'tier1', months: [3, 4], tags: ['api'], related: ['c12-idempotency'] },
      { id: 'd6-authentication', title: 'Authentication (API)', priority: 'tier1', months: [3, 4], tags: ['api'], related: ['c9-authentication'] },
      { id: 'd6-rate-limiting', title: 'Rate Limiting (API)', priority: 'tier1', months: [3, 4], tags: ['api'], related: ['d10-rate-limiter'] },
      { id: 'd6-error-modelling', title: 'Error Modelling', priority: 'tier1', months: [3, 4], tags: ['api'] },
      { id: 'd6-graphql', title: 'GraphQL Concepts', priority: 'tier2', months: [5, 6], tags: ['api'] },
      { id: 'd6-grpc', title: 'gRPC', priority: 'tier2', months: [5, 6], tags: ['api'], related: ['c4-grpc'] },
      { id: 'd6-websockets', title: 'WebSockets', priority: 'tier2', months: [5, 6], tags: ['api'], related: ['b3-websockets'] },
      { id: 'd6-sse', title: 'SSE', priority: 'tier2', months: [5, 6], tags: ['api'], related: ['b3-sse'] },
    ],
  },
  {
    id: 'D7',
    track: 'D',
    title: 'Scalability & Reliability',
    order: 7,
    defaultKind: 'theory',
    defaultDepth: 'deep',
    topics: [
      { id: 'd7-caching-strategies', title: 'Caching Strategies', priority: 'tier1', months: [5, 6], tags: ['scalability'], related: ['c10-cache-aside'] },
      { id: 'd7-cache-invalidation', title: 'Cache Invalidation', priority: 'tier1', months: [5, 6], tags: ['scalability'], related: ['c10-invalidation'] },
      { id: 'd7-load-shedding', title: 'Load Shedding', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
      { id: 'd7-rate-limiting', title: 'Rate Limiting (Systems)', priority: 'tier1', months: [5, 6], tags: ['reliability'], related: ['d10-rate-limiter'] },
      { id: 'd7-circuit-breakers', title: 'Circuit Breakers', priority: 'tier1', months: [5, 6], tags: ['reliability'], related: ['c12-circuit-breakers'] },
      { id: 'd7-retry-strategies', title: 'Retry Strategies', priority: 'tier1', months: [5, 6], tags: ['reliability'], related: ['c12-retries'] },
      { id: 'd7-backpressure', title: 'Backpressure', priority: 'tier1', months: [5, 6], tags: ['reliability'], related: ['c12-backpressure'] },
      { id: 'd7-failover', title: 'Failover', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
      { id: 'd7-redundancy', title: 'Redundancy', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
      { id: 'd7-disaster-recovery', title: 'Disaster Recovery', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
      { id: 'd7-spof', title: 'Single Points of Failure', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
      { id: 'd7-sli', title: 'SLI/SLO/SLA Concepts', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
      { id: 'd7-slo', title: 'SLO', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'd7-sli', months: [5, 6], tags: ['reliability'] },
      { id: 'd7-sla', title: 'SLA', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'd7-sli', months: [5, 6], tags: ['reliability'] },
      { id: 'd7-availability-calc', title: 'Availability Calculations', priority: 'tier1', months: [5, 6], tags: ['reliability'] },
    ],
  },
  {
    id: 'D8',
    track: 'D',
    title: 'Capacity Estimation',
    order: 8,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'd8-qps', title: 'Requests per Second', priority: 'tier1', months: [5, 6], tags: ['capacity'] },
      { id: 'd8-read-write-ratios', title: 'Read/Write Ratios', priority: 'tier1', months: [5, 6], tags: ['capacity'] },
      { id: 'd8-storage', title: 'Storage Estimation', priority: 'tier1', months: [5, 6], tags: ['capacity'] },
      { id: 'd8-bandwidth', title: 'Bandwidth Estimation', priority: 'tier1', months: [5, 6], tags: ['capacity'] },
      { id: 'd8-cache-sizing', title: 'Cache-Size Estimation', priority: 'tier1', months: [5, 6], tags: ['capacity'] },
      { id: 'd8-db-growth', title: 'Database-Growth Estimation', priority: 'tier1', months: [5, 6], tags: ['capacity'] },
      { id: 'd8-server-requirements', title: 'Server Requirements', priority: 'tier2', months: [5, 6], tags: ['capacity'] },
    ],
  },
  {
    id: 'D9',
    track: 'D',
    title: 'System Design Interview Methodology',
    order: 9,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'd9-requirements', title: 'Requirements Gathering', priority: 'tier1', months: [3, 5], tags: ['interview', 'hld'] },
      { id: 'd9-functional', title: 'Functional + Non-Functional Requirements', priority: 'tier1', months: [3, 5], tags: ['interview', 'hld'] },
      { id: 'd9-non-functional', title: 'Non-Functional Requirements', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'd9-functional', months: [3, 5], tags: ['interview', 'hld'] },
      { id: 'd9-capacity', title: 'Capacity Estimation (Interview)', priority: 'tier1', months: [3, 5], tags: ['interview', 'hld'], related: ['d8-qps'] },
      { id: 'd9-api-design', title: 'API Design (Interview)', priority: 'tier1', months: [3, 5], tags: ['interview', 'hld'], related: ['d6-rest'] },
      { id: 'd9-data-modelling', title: 'Data Modelling (Interview)', priority: 'tier1', months: [3, 5], tags: ['interview', 'hld'] },
      { id: 'd9-hla', title: 'High-Level Architecture', priority: 'tier1', months: [3, 5], tags: ['interview', 'hld'] },
      { id: 'd9-deep-dives', title: 'Component Deep Dives', priority: 'tier1', months: [3, 5], tags: ['interview', 'hld'] },
      { id: 'd9-scaling', title: 'Scaling (Interview)', priority: 'tier1', months: [3, 5], tags: ['interview', 'hld'] },
      { id: 'd9-reliability', title: 'Reliability / Failure Handling', priority: 'tier1', months: [3, 5], tags: ['interview', 'hld'] },
      { id: 'd9-failure-handling', title: 'Failure Handling', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'd9-reliability', months: [3, 5], tags: ['interview', 'hld'] },
      { id: 'd9-consistency', title: 'Consistency (Interview)', priority: 'tier1', months: [3, 5], tags: ['interview', 'hld'] },
      { id: 'd9-security', title: 'Security (Interview)', priority: 'tier1', months: [3, 5], tags: ['interview', 'hld'] },
      { id: 'd9-observability', title: 'Observability (Interview)', priority: 'tier1', months: [3, 5], tags: ['interview', 'hld'] },
      { id: 'd9-tradeoffs', title: 'Trade-off Analysis', priority: 'tier1', months: [3, 5], tags: ['interview', 'hld'] },
    ],
  },
  {
    id: 'D10',
    track: 'D',
    title: 'System Design Practice',
    order: 10,
    defaultKind: 'system-design',
    defaultDepth: 'deep',
    topics: [
      { id: 'd10-url-shortener', title: 'URL Shortener', priority: 'tier1', months: [3, 4], tags: ['hld', 'beginner'] },
      { id: 'd10-pastebin', title: 'Pastebin', priority: 'tier1', months: [3, 4], tags: ['hld', 'beginner'] },
      {
        id: 'd10-rate-limiter',
        title: 'Rate Limiter',
        priority: 'tier1',
        months: [3, 4, 5],
        tags: ['hld', 'redis', 'scalability', 'reliability'],
        prereqs: ['c7-isolation-levels', 'd9-requirements'],
        related: ['c10-rate-limiting', 'c12-rate-limiting', 'd3-rate-limiter-lld', 'd7-rate-limiting'],
        capstone: 'Protects booking and payment APIs from abuse; Redis token bucket for flash-sale traffic.',
        contentReady: true,
        depth: 'deep',
      },
      { id: 'd10-notification-system', title: 'Notification System', priority: 'tier1', months: [3, 4], tags: ['hld', 'beginner'] },
      { id: 'd10-news-feed', title: 'Twitter / News Feed', priority: 'tier1', months: [5, 6], tags: ['hld', 'intermediate'] },
      { id: 'd10-chat', title: 'Chat System', priority: 'tier1', months: [5, 6], tags: ['hld', 'intermediate'] },
      { id: 'd10-drive', title: 'Dropbox / Google Drive', priority: 'tier1', months: [5, 6], tags: ['hld', 'intermediate'] },
      { id: 'd10-youtube', title: 'YouTube', priority: 'tier1', months: [5, 6], tags: ['hld', 'intermediate'] },
      { id: 'd10-autocomplete', title: 'Search Autocomplete', priority: 'tier1', months: [5, 6], tags: ['hld', 'intermediate'] },
      { id: 'd10-ticket-booking', title: 'Ticket-Booking System', priority: 'tier1', months: [5, 6], tags: ['hld', 'intermediate'], related: ['c7-isolation-levels', 'c10-rate-limiting', 'c11-idempotent-consumers'], capstone: 'Core capstone domain — concurrent inventory, reservations, payments.' },
      { id: 'd10-uber', title: 'Uber', priority: 'tier1', months: [6, 8], tags: ['hld', 'advanced'] },
      { id: 'd10-payments', title: 'Payment System', priority: 'tier1', months: [6, 8], tags: ['hld', 'advanced'] },
      { id: 'd10-job-scheduler', title: 'Distributed Job Scheduler', priority: 'tier1', months: [6, 8], tags: ['hld', 'advanced'] },
      { id: 'd10-monitoring', title: 'Metrics/Monitoring Platform', priority: 'tier1', months: [6, 8], tags: ['hld', 'advanced'] },
      { id: 'd10-distributed-cache', title: 'Distributed Cache', priority: 'tier1', months: [6, 8], tags: ['hld', 'advanced'] },
      { id: 'd10-ad-aggregation', title: 'Ad-Click Aggregation', priority: 'tier2', months: [7, 8], tags: ['hld', 'advanced'] },
      { id: 'd10-web-crawler', title: 'Web Crawler', priority: 'tier2', months: [7, 8], tags: ['hld', 'advanced'] },
    ],
  },
]
