import type { SectionSeed } from './build'
import { TRACK_A_GRAPH_SECTIONS } from './track-a-graphs'

/** Track A — DSA & Problem Solving (metadata only; content in Phase 4). */
export const TRACK_A_SECTIONS: SectionSeed[] = [
  {
    id: 'A1',
    track: 'A',
    title: 'Programming for Interviews',
    order: 1,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'a1-java-syntax-competitive', title: 'Java Syntax for Competitive Coding', priority: 'tier1', months: [1, 2], tags: ['java', 'interviews'] },
      { id: 'a1-arraylist', title: 'Collections Framework', priority: 'tier1', months: [1, 2], tags: ['collections'], prereqs: ['a1-java-syntax-competitive'] },
      { id: 'a1-hashmap', title: 'HashMap', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'a1-arraylist', months: [1, 2], tags: ['collections', 'hashing'], related: ['c1-hashmap-internals'] },
      { id: 'a1-hashset', title: 'HashSet', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'a1-arraylist', months: [1, 2], tags: ['collections'], prereqs: ['a1-hashmap'] },
      { id: 'a1-treemap', title: 'TreeMap', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'a1-arraylist', months: [1, 2], tags: ['collections'] },
      { id: 'a1-treeset', title: 'TreeSet', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'a1-arraylist', months: [1, 2], tags: ['collections'], related: ['a1-treemap'] },
      { id: 'a1-deque', title: 'Deque', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'a1-arraylist', months: [1, 2], tags: ['collections'], related: ['a5-deque'] },
      { id: 'a1-priorityqueue', title: 'PriorityQueue', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'a1-arraylist', months: [1, 2], tags: ['collections', 'heaps'], related: ['a7-priority-queues'] },
      { id: 'a1-comparable-comparator', title: 'Comparable / Comparator', priority: 'tier1', months: [1, 2], tags: ['java', 'sorting'] },
      { id: 'a1-strings-stringbuilder', title: 'Strings / StringBuilder', priority: 'tier1', months: [1, 2], tags: ['strings'] },
      { id: 'a1-custom-classes', title: 'Custom Classes', priority: 'tier1', months: [1, 2], tags: ['java'] },
      { id: 'a1-recursion', title: 'Recursion', priority: 'tier1', months: [1, 2], tags: ['recursion'], related: ['a9-subsets'] },
      { id: 'a1-time-complexity', title: 'Time/Space Complexity', priority: 'tier1', months: [1, 2], tags: ['complexity'] },
      { id: 'a1-space-complexity', title: 'Space Complexity', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'a1-time-complexity', months: [1, 2], tags: ['complexity'], prereqs: ['a1-time-complexity'] },
      { id: 'a1-big-o', title: 'Big-O Analysis', priority: 'tier1', months: [1, 2], tags: ['complexity'], prereqs: ['a1-time-complexity', 'a1-space-complexity'] },
      { id: 'a1-java-streams-interviews', title: 'Java Streams for Interviews', priority: 'tier2', months: [2, 3], tags: ['java', 'streams'] },
    ],
  },
  {
    id: 'A2',
    track: 'A',
    title: 'Arrays & Strings',
    order: 2,
    defaultKind: 'dsa-pattern',
    defaultDepth: 'deep',
    topics: [
      { id: 'a2-array-string-traversal', title: 'Array/String Traversal and Manipulation', priority: 'tier1', months: [1, 2], tags: ['arrays', 'strings'] },
      { id: 'a2-prefix-suffix', title: 'Prefix/Suffix Techniques', priority: 'tier1', months: [1, 2], tags: ['arrays', 'prefix'] },
      { id: 'a2-two-pointers', title: 'Two Pointers', priority: 'tier1', months: [1, 2], tags: ['arrays', 'two-pointers'], related: ['a2-sliding-window'] },
      {
        id: 'a2-sliding-window',
        title: 'Sliding Window',
        priority: 'tier1',
        months: [1, 2, 3],
        tags: ['arrays', 'strings', 'two-pointers', 'patterns'],
        prereqs: ['a2-two-pointers', 'a1-big-o'],
        related: ['a2-prefix-suffix', 'a5-monotonic-queue'],
        next: ['a2-frequency-counting'],
        contentReady: true,
        depth: 'deep',
      },
      { id: 'a2-frequency-counting', title: 'Frequency Counting', priority: 'tier1', months: [1, 2], tags: ['hashing'], related: ['a2-hashing'] },
      { id: 'a2-hashing', title: 'Hashing', priority: 'tier1', months: [1, 2], tags: ['hashing'], related: ['a1-hashmap'] },
      { id: 'a2-sorting-based', title: 'Sorting-Based Problems', priority: 'tier1', months: [1, 2], tags: ['sorting'], related: ['a3-comparator-sorting'] },
      { id: 'a2-matrix', title: 'Matrix Problems', priority: 'tier1', months: [2, 3], tags: ['arrays', 'matrix'] },
      { id: 'a2-intervals', title: 'Interval Problems', priority: 'tier1', months: [2, 3], tags: ['intervals'], related: ['a10-interval-scheduling'] },
      { id: 'a2-kadane', title: "Kadane's Algorithm", priority: 'tier1', months: [1, 2], tags: ['arrays', 'dp'] },
      { id: 'a2-difference-arrays', title: 'Difference Arrays', priority: 'tier2', months: [3, 4], tags: ['arrays', 'prefix'] },
    ],
  },
  {
    id: 'A3',
    track: 'A',
    title: 'Searching & Sorting',
    order: 3,
    defaultKind: 'dsa-pattern',
    defaultDepth: 'deep',
    topics: [
      { id: 'a3-binary-search', title: 'Binary Search', priority: 'tier1', months: [1, 2], tags: ['search'] },
      { id: 'a3-binary-search-on-answer', title: 'Binary Search on Answer', priority: 'tier1', months: [2, 3], tags: ['search'], prereqs: ['a3-binary-search'] },
      { id: 'a3-lower-upper-bounds', title: 'Lower/Upper Bounds', priority: 'tier1', months: [1, 2], tags: ['search'], prereqs: ['a3-binary-search'] },
      { id: 'a3-merge-sort', title: 'Merge Sort', priority: 'tier1', months: [1, 2], tags: ['sorting'] },
      { id: 'a3-quick-sort', title: 'Quick Sort Concepts', priority: 'tier1', months: [1, 2], tags: ['sorting'] },
      { id: 'a3-comparator-sorting', title: 'Comparator-Based Sorting', priority: 'tier1', months: [1, 2], tags: ['sorting'], related: ['a1-comparable-comparator'] },
      { id: 'a3-quickselect', title: 'Quickselect', priority: 'tier2', months: [3, 4], tags: ['sorting', 'selection'], prereqs: ['a3-quick-sort'] },
      { id: 'a3-counting-sort', title: 'Counting/Bucket Sorting Concepts', priority: 'tier2', months: [3, 4], tags: ['sorting'] },
      { id: 'a3-bucket-sort', title: 'Bucket Sort Concepts', priority: 'tier2', curriculumLevel: 'nested-concept', parentTopicId: 'a3-counting-sort', months: [3, 4], tags: ['sorting'] },
    ],
  },
  {
    id: 'A4',
    track: 'A',
    title: 'Linked Lists',
    order: 4,
    defaultKind: 'dsa-pattern',
    defaultDepth: 'medium',
    topics: [
      { id: 'a4-singly-linked-lists', title: 'Singly/Doubly Linked Lists', priority: 'tier1', months: [1, 2], tags: ['linked-list'] },
      { id: 'a4-doubly-linked-lists', title: 'Doubly Linked Lists', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'a4-singly-linked-lists', months: [1, 2], tags: ['linked-list'] },
      { id: 'a4-fast-slow-pointers', title: 'Fast/Slow Pointers', priority: 'tier1', months: [1, 2], tags: ['linked-list', 'two-pointers'] },
      { id: 'a4-reversal', title: 'Linked List Reversal', priority: 'tier1', months: [1, 2], tags: ['linked-list'] },
      { id: 'a4-cycle-detection', title: 'Cycle Detection', priority: 'tier1', months: [1, 2], tags: ['linked-list'], prereqs: ['a4-fast-slow-pointers'] },
      { id: 'a4-merge-lists', title: 'Merge Lists', priority: 'tier1', months: [2, 3], tags: ['linked-list'] },
      { id: 'a4-intersection', title: 'List Intersection', priority: 'tier1', months: [2, 3], tags: ['linked-list'] },
      { id: 'a4-lru-style', title: 'LRU-Style Linked-List Manipulation', priority: 'tier1', months: [2, 3], tags: ['linked-list', 'design'], related: ['d3-cache'] },
    ],
  },
  {
    id: 'A5',
    track: 'A',
    title: 'Stack & Queue',
    order: 5,
    defaultKind: 'dsa-pattern',
    defaultDepth: 'medium',
    topics: [
      { id: 'a5-stack', title: 'Stack', priority: 'tier1', months: [1, 2], tags: ['stack'] },
      { id: 'a5-queue', title: 'Queue', priority: 'tier1', months: [1, 2], tags: ['queue'] },
      { id: 'a5-deque', title: 'Deque', priority: 'tier1', months: [1, 2], tags: ['deque'], related: ['a1-deque'] },
      { id: 'a5-monotonic-stack', title: 'Monotonic Stack', priority: 'tier1', months: [2, 3], tags: ['stack'], prereqs: ['a5-stack'] },
      { id: 'a5-monotonic-queue', title: 'Monotonic Queue', priority: 'tier1', months: [2, 3], tags: ['queue', 'deque'], related: ['a2-sliding-window'] },
      { id: 'a5-next-greater-smaller', title: 'Next Greater/Smaller Element', priority: 'tier1', months: [2, 3], tags: ['stack'], prereqs: ['a5-monotonic-stack'] },
      { id: 'a5-parentheses', title: 'Parentheses/Expression Problems', priority: 'tier1', months: [1, 2], tags: ['stack'] },
      { id: 'a5-expression', title: 'Expression Problems', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'a5-parentheses', months: [2, 3], tags: ['stack'] },
    ],
  },
  {
    id: 'A6',
    track: 'A',
    title: 'Trees',
    order: 6,
    defaultKind: 'dsa-pattern',
    defaultDepth: 'deep',
    topics: [
      { id: 'a6-binary-trees', title: 'Binary Trees', priority: 'tier1', months: [2, 3], tags: ['trees'] },
      { id: 'a6-dfs', title: 'Tree DFS', priority: 'tier1', months: [2, 3], tags: ['trees', 'dfs'], prereqs: ['a6-binary-trees'] },
      { id: 'a6-bfs', title: 'Tree BFS/Level-Order Traversal', priority: 'tier1', months: [2, 3], tags: ['trees', 'bfs'], related: ['a6-level-order'] },
      { id: 'a6-level-order', title: 'Level-Order Traversal', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'a6-bfs', months: [2, 3], tags: ['trees', 'bfs'] },
      { id: 'a6-bst', title: 'Binary Search Trees', priority: 'tier1', months: [2, 3], tags: ['trees', 'bst'] },
      { id: 'a6-height-depth', title: 'Tree Height/Depth', priority: 'tier1', months: [2, 3], tags: ['trees'] },
      { id: 'a6-diameter', title: 'Tree Diameter', priority: 'tier1', months: [2, 3], tags: ['trees'] },
      { id: 'a6-lca', title: 'Lowest Common Ancestor', priority: 'tier1', months: [2, 3], tags: ['trees'] },
      { id: 'a6-path-problems', title: 'Tree Path Problems', priority: 'tier1', months: [2, 3], tags: ['trees'] },
      { id: 'a6-construction', title: 'Tree Construction', priority: 'tier1', months: [3, 4], tags: ['trees'] },
      { id: 'a6-serialization', title: 'Serialization/Deserialization', priority: 'tier1', months: [3, 4], tags: ['trees'] },
      { id: 'a6-tree-views', title: 'Tree Views', priority: 'tier2', months: [3, 4], tags: ['trees'] },
      { id: 'a6-nary-trees', title: 'N-ary Trees', priority: 'tier2', months: [3, 4], tags: ['trees'] },
    ],
  },
  {
    id: 'A7',
    track: 'A',
    title: 'Heaps',
    order: 7,
    defaultKind: 'dsa-pattern',
    defaultDepth: 'medium',
    topics: [
      { id: 'a7-min-heap', title: 'Min/Max Heap', priority: 'tier1', months: [2, 3], tags: ['heaps'] },
      { id: 'a7-max-heap', title: 'Max Heap', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'a7-min-heap', months: [2, 3], tags: ['heaps'] },
      { id: 'a7-priority-queues', title: 'Priority Queues', priority: 'tier1', months: [2, 3], tags: ['heaps'], related: ['a1-priorityqueue'] },
      { id: 'a7-top-k', title: 'Top-K Problems', priority: 'tier1', months: [2, 3], tags: ['heaps'] },
      { id: 'a7-k-way-merge', title: 'K-way Merge', priority: 'tier1', months: [3, 4], tags: ['heaps'] },
      { id: 'a7-running-median', title: 'Running Median', priority: 'tier1', months: [3, 4], tags: ['heaps'], related: ['a7-two-heap-pattern'] },
      { id: 'a7-two-heap-pattern', title: 'Two-Heap Pattern', priority: 'tier2', months: [3, 4], tags: ['heaps'] },
    ],
  },
  ...TRACK_A_GRAPH_SECTIONS,
  {
    id: 'A9',
    track: 'A',
    title: 'Recursion & Backtracking',
    order: 25,
    defaultKind: 'dsa-pattern',
    defaultDepth: 'deep',
    topics: [
      { id: 'a9-subsets', title: 'Subsets', priority: 'tier1', months: [3, 4], tags: ['backtracking'], prereqs: ['a1-recursion'] },
      { id: 'a9-permutations', title: 'Permutations', priority: 'tier1', months: [3, 4], tags: ['backtracking'] },
      { id: 'a9-combinations', title: 'Combinations', priority: 'tier1', months: [3, 4], tags: ['backtracking'] },
      { id: 'a9-combination-sum', title: 'Combination Sum', priority: 'tier1', months: [3, 4], tags: ['backtracking'] },
      { id: 'a9-grid-search', title: 'Grid Search Backtracking', priority: 'tier1', months: [3, 4], tags: ['backtracking'] },
      { id: 'a9-n-queens', title: 'N-Queens', priority: 'tier1', months: [3, 4], tags: ['backtracking'] },
      { id: 'a9-constraint-backtracking', title: 'Constraint-Based Backtracking', priority: 'tier1', months: [3, 4], tags: ['backtracking'] },
      { id: 'a9-pruning', title: 'Pruning', priority: 'tier1', months: [3, 4], tags: ['backtracking'] },
    ],
  },
  {
    id: 'A10',
    track: 'A',
    title: 'Greedy',
    order: 26,
    defaultKind: 'dsa-pattern',
    defaultDepth: 'medium',
    topics: [
      { id: 'a10-interval-scheduling', title: 'Interval Scheduling', priority: 'tier1', months: [3, 4], tags: ['greedy', 'intervals'], related: ['a2-intervals'] },
      { id: 'a10-sorting-greedy', title: 'Sorting + Greedy', priority: 'tier1', months: [3, 4], tags: ['greedy'] },
      { id: 'a10-heap-greedy', title: 'Heap + Greedy', priority: 'tier1', months: [3, 4], tags: ['greedy', 'heaps'] },
      { id: 'a10-local-vs-global', title: 'Local vs Global Optimum Reasoning', priority: 'tier1', months: [3, 4], tags: ['greedy'] },
    ],
  },
  {
    id: 'A11',
    track: 'A',
    title: 'Dynamic Programming',
    order: 27,
    defaultKind: 'dsa-pattern',
    defaultDepth: 'deep',
    topics: [
      { id: 'a11-memoization', title: 'Memoization vs Tabulation', priority: 'tier1', months: [3, 4], tags: ['dp'] },
      { id: 'a11-tabulation', title: 'Tabulation', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'a11-memoization', months: [3, 4], tags: ['dp'], related: ['a11-memoization'] },
      { id: 'a11-1d-dp', title: '1D DP', priority: 'tier1', months: [3, 4], tags: ['dp'] },
      { id: 'a11-2d-dp', title: '2D DP', priority: 'tier1', months: [3, 4], tags: ['dp'] },
      { id: 'a11-knapsack', title: 'Knapsack Patterns', priority: 'tier1', months: [3, 4], tags: ['dp'] },
      { id: 'a11-subsequences', title: 'Subsequence Problems', priority: 'tier1', months: [3, 4], tags: ['dp'] },
      { id: 'a11-lis', title: 'Longest Increasing Subsequence', priority: 'tier1', months: [3, 4], tags: ['dp'] },
      { id: 'a11-lcs', title: 'Longest Common Subsequence', priority: 'tier1', months: [3, 4], tags: ['dp'] },
      { id: 'a11-grid-dp', title: 'Grid DP', priority: 'tier1', months: [3, 4], tags: ['dp'] },
      { id: 'a11-partition-dp', title: 'Partition DP Basics', priority: 'tier1', months: [4, 5], tags: ['dp'] },
      { id: 'a11-tree-dp', title: 'DP on Trees', priority: 'tier2', months: [5, 6], tags: ['dp', 'trees'] },
      { id: 'a11-state-machine-dp', title: 'State-Machine DP', priority: 'tier2', months: [5, 6], tags: ['dp'] },
      { id: 'a11-bitmask-dp', title: 'Bitmask DP', priority: 'tier3', months: [6, 7], tags: ['dp', 'bitmask'] },
    ],
  },
  {
    id: 'A12',
    track: 'A',
    title: 'Tries & Advanced Structures',
    order: 28,
    defaultKind: 'dsa-pattern',
    defaultDepth: 'medium',
    topics: [
      { id: 'a12-trie', title: 'Trie', priority: 'tier2', months: [5, 6], tags: ['trie'] },
      { id: 'a12-prefix-matching', title: 'Prefix Matching', priority: 'tier2', months: [5, 6], tags: ['trie'], prereqs: ['a12-trie'] },
      { id: 'a12-segment-trees', title: 'Segment Trees', priority: 'tier2', months: [5, 6], tags: ['advanced'] },
      { id: 'a12-fenwick', title: 'Fenwick Tree', priority: 'tier3', months: [6, 7], tags: ['advanced'] },
      { id: 'a12-sparse-tables', title: 'Sparse Tables', priority: 'tier3', months: [6, 7], tags: ['advanced'] },
    ],
  },
  {
    id: 'A13',
    track: 'A',
    title: 'Bit Manipulation',
    order: 29,
    defaultKind: 'dsa-pattern',
    defaultDepth: 'medium',
    topics: [
      { id: 'a13-and-or-xor', title: 'AND / OR / XOR', priority: 'tier1', months: [2, 3], tags: ['bits'] },
      { id: 'a13-set-bit', title: 'Set/Unset/Check Bit', priority: 'tier1', months: [2, 3], tags: ['bits'] },
      { id: 'a13-unset-bit', title: 'Unset Bit', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'a13-set-bit', months: [2, 3], tags: ['bits'] },
      { id: 'a13-check-bit', title: 'Check Bit', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'a13-set-bit', months: [2, 3], tags: ['bits'] },
      { id: 'a13-powers-of-two', title: 'Powers of Two', priority: 'tier1', months: [2, 3], tags: ['bits'] },
      { id: 'a13-xor-tricks', title: 'XOR Tricks', priority: 'tier2', months: [3, 4], tags: ['bits'] },
      { id: 'a13-bitmasking', title: 'Bitmasking', priority: 'tier2', months: [4, 5], tags: ['bits'], related: ['a11-bitmask-dp'] },
    ],
  },
  {
    id: 'A14',
    track: 'A',
    title: 'Coding Interview Execution',
    order: 30,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'a14-clarifying-requirements', title: 'Clarifying Requirements', priority: 'tier1', months: [1, 7], tags: ['interview'] },
      { id: 'a14-brute-force-first', title: 'Explaining Brute-Force First', priority: 'tier1', months: [1, 7], tags: ['interview'] },
      { id: 'a14-deriving-optimization', title: 'Deriving Optimized Solution', priority: 'tier1', months: [1, 7], tags: ['interview'] },
      { id: 'a14-thinking-aloud', title: 'Thinking Aloud', priority: 'tier1', months: [1, 7], tags: ['interview'] },
      { id: 'a14-clean-coding', title: 'Clean Coding Without IDE Assistance', priority: 'tier1', months: [2, 7], tags: ['interview'] },
      { id: 'a14-manual-testing', title: 'Manual Testing', priority: 'tier1', months: [2, 7], tags: ['interview'] },
      { id: 'a14-edge-cases', title: 'Edge-Case Identification', priority: 'tier1', months: [2, 7], tags: ['interview'] },
      { id: 'a14-complexity-in-interview', title: 'Complexity Analysis in Interviews', priority: 'tier1', months: [1, 7], tags: ['interview'], related: ['a1-big-o'] },
      { id: 'a14-responding-to-hints', title: 'Responding to Interviewer Hints', priority: 'tier1', months: [5, 8], tags: ['interview'] },
      { id: 'a14-timed-coding', title: 'Timed Mock Interviews', priority: 'tier1', months: [5, 8], tags: ['interview'] },
      { id: 'a14-mock-interviews', title: 'Mock Interviews', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'a14-timed-coding', months: [7, 10], tags: ['interview'] },
    ],
  },
]
