import type { SectionSeed } from './build'
import { TRACK_B_JAVASCRIPT_SECTIONS } from './track-b-javascript'
import { TRACK_B_TYPESCRIPT_SECTIONS } from './track-b-typescript'
import { TRACK_B_BROWSER_SECTIONS } from './track-b-browser'

/** Track B — Frontend Engineering. B1 JS, B2 TypeScript, B3 Browser & Web Platform. */
export const TRACK_B_SECTIONS: SectionSeed[] = [
  ...TRACK_B_JAVASCRIPT_SECTIONS,
  ...TRACK_B_TYPESCRIPT_SECTIONS,
  ...TRACK_B_BROWSER_SECTIONS,
  {
    id: 'B4',
    track: 'B',
    title: 'React',
    order: 116,
    defaultKind: 'theory',
    defaultDepth: 'deep',
    topics: [
      { id: 'b4-component-model', title: 'Component Model', priority: 'tier1', months: [5, 6], tags: ['react'] },
      { id: 'b4-props', title: 'Props/State', priority: 'tier1', months: [5, 6], tags: ['react'] },
      { id: 'b4-state', title: 'State', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'b4-props', months: [5, 6], tags: ['react'] },
      { id: 'b4-controlled', title: 'Controlled/Uncontrolled Components', priority: 'tier1', months: [5, 6], tags: ['react'] },
      { id: 'b4-uncontrolled', title: 'Uncontrolled Components', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'b4-controlled', months: [5, 6], tags: ['react'] },
      { id: 'b4-composition', title: 'Composition', priority: 'tier1', months: [5, 6], tags: ['react'] },
      { id: 'b4-reconciliation', title: 'Reconciliation', priority: 'tier1', months: [5, 6], tags: ['react'], depth: 'deep' },
      { id: 'b4-virtual-dom', title: 'Virtual DOM', priority: 'tier1', months: [5, 6], tags: ['react'] },
      { id: 'b4-keys', title: 'Keys', priority: 'tier1', months: [5, 6], tags: ['react'] },
      { id: 'b4-rendering-lifecycle', title: 'Rendering Lifecycle', priority: 'tier1', months: [5, 6], tags: ['react'] },
      { id: 'b4-usestate', title: 'useState', priority: 'tier1', months: [5, 6], tags: ['react', 'hooks'] },
      { id: 'b4-useeffect', title: 'useEffect', priority: 'tier1', months: [5, 6], tags: ['react', 'hooks'] },
      { id: 'b4-useref', title: 'useRef', priority: 'tier1', months: [5, 6], tags: ['react', 'hooks'] },
      { id: 'b4-usecontext', title: 'useContext', priority: 'tier1', months: [5, 6], tags: ['react', 'hooks'] },
      { id: 'b4-usereducer', title: 'useReducer', priority: 'tier1', months: [5, 6], tags: ['react', 'hooks'] },
      { id: 'b4-usememo', title: 'useMemo', priority: 'tier1', months: [5, 6], tags: ['react', 'hooks'] },
      { id: 'b4-usecallback', title: 'useCallback', priority: 'tier1', months: [5, 6], tags: ['react', 'hooks'] },
      { id: 'b4-custom-hooks', title: 'Custom Hooks', priority: 'tier1', months: [5, 6], tags: ['react', 'hooks'] },
      { id: 'b4-effect-dependencies', title: 'Effect Dependency Reasoning', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'b4-useeffect', months: [5, 6], tags: ['react', 'hooks'], prereqs: ['b4-useeffect'] },
      { id: 'b4-when-not-effects', title: 'When Not to Use Effects', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'b4-useeffect', months: [5, 6], tags: ['react', 'hooks'] },
      { id: 'b4-when-not-memoize', title: 'When Not to Memoize', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'b4-memoization-perf', months: [5, 6], tags: ['react', 'performance'] },
      { id: 'b4-state-placement', title: 'State Placement', priority: 'tier1', months: [5, 6], tags: ['react', 'architecture'] },
      { id: 'b4-component-boundaries', title: 'Component Boundaries', priority: 'tier1', months: [5, 6], tags: ['react', 'architecture'] },
      { id: 'b4-state-management-tradeoffs', title: 'State-Management Trade-offs', priority: 'tier1', months: [5, 6], tags: ['react', 'architecture'] },
      { id: 'b4-server-vs-client-state', title: 'Server vs Client State', priority: 'tier1', months: [5, 6], tags: ['react', 'architecture'] },
      { id: 'b4-data-fetching', title: 'Data-Fetching Patterns', priority: 'tier1', months: [5, 6], tags: ['react'] },
      { id: 'b4-error-boundaries', title: 'Error Boundaries', priority: 'tier1', months: [5, 6], tags: ['react'] },
      { id: 'b4-suspense', title: 'Suspense Concepts', priority: 'tier1', months: [5, 6], tags: ['react'] },
      { id: 'b4-code-splitting', title: 'Code Splitting', priority: 'tier1', months: [5, 6], tags: ['react', 'performance'] },
      { id: 'b4-lazy-loading', title: 'Lazy Loading', priority: 'tier1', months: [5, 6], tags: ['react', 'performance'] },
      { id: 'b4-profiler', title: 'React Profiler', priority: 'tier1', months: [5, 6], tags: ['react', 'performance'] },
      { id: 'b4-unnecessary-renders', title: 'Unnecessary Renders', priority: 'tier1', months: [5, 6], tags: ['react', 'performance'] },
      { id: 'b4-memoization-perf', title: 'Memoization for Performance', priority: 'tier1', months: [5, 6], tags: ['react', 'performance'] },
      { id: 'b4-virtualization', title: 'List Virtualization', priority: 'tier1', months: [5, 6], tags: ['react', 'performance'] },
      { id: 'b4-bundle-optimization', title: 'Bundle Optimization', priority: 'tier1', months: [5, 6], tags: ['react', 'performance'] },
      { id: 'b4-network-waterfalls', title: 'Network Waterfalls', priority: 'tier1', months: [5, 6], tags: ['react', 'performance'] },
      { id: 'b4-modern-rendering', title: 'Modern React Rendering Model', priority: 'tier1', months: [5, 6], tags: ['react'] },
      { id: 'b4-server-components', title: 'Server Components Concepts', priority: 'tier1', months: [5, 6], tags: ['react'] },
      { id: 'b4-ssr', title: 'SSR', priority: 'tier1', months: [5, 6], tags: ['react'] },
      { id: 'b4-csr', title: 'CSR', priority: 'tier1', months: [5, 6], tags: ['react'] },
      { id: 'b4-ssg', title: 'SSG', priority: 'tier1', months: [5, 6], tags: ['react'] },
      { id: 'b4-nextjs', title: 'Next.js Architecture', priority: 'tier2', months: [7, 8], tags: ['react', 'nextjs'] },
    ],
  },
  {
    id: 'B5',
    track: 'B',
    title: 'CSS / UI Engineering',
    order: 117,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'b5-box-model', title: 'Box Model', priority: 'tier1', months: [2, 3], tags: ['css'] },
      { id: 'b5-flexbox', title: 'Flexbox', priority: 'tier1', months: [2, 3], tags: ['css'] },
      { id: 'b5-grid', title: 'Grid', priority: 'tier1', months: [2, 3], tags: ['css'] },
      { id: 'b5-positioning', title: 'Positioning', priority: 'tier1', months: [2, 3], tags: ['css'] },
      { id: 'b5-responsive', title: 'Responsive Design', priority: 'tier1', months: [2, 3], tags: ['css'] },
      { id: 'b5-specificity', title: 'Specificity', priority: 'tier1', months: [2, 3], tags: ['css'] },
      { id: 'b5-accessibility', title: 'Accessibility', priority: 'tier1', months: [3, 4], tags: ['a11y'] },
      { id: 'b5-semantic-html', title: 'Semantic HTML', priority: 'tier1', months: [2, 3], tags: ['html', 'a11y'] },
      { id: 'b5-aria', title: 'ARIA Basics', priority: 'tier1', months: [3, 4], tags: ['a11y'] },
      { id: 'b5-css-architecture', title: 'CSS Architecture', priority: 'tier2', months: [5, 6], tags: ['css'] },
      { id: 'b5-design-systems', title: 'Design Systems', priority: 'tier2', months: [5, 6], tags: ['css', 'design'] },
    ],
  },
  {
    id: 'B6',
    track: 'B',
    title: 'Frontend System Design',
    order: 118,
    defaultKind: 'system-design',
    defaultDepth: 'deep',
    topics: [
      { id: 'b6-large-app-architecture', title: 'Large-Application Architecture', priority: 'tier1', months: [7, 8], tags: ['frontend-sd'] },
      { id: 'b6-component-architecture', title: 'Component Architecture', priority: 'tier1', months: [7, 8], tags: ['frontend-sd'] },
      { id: 'b6-state-architecture', title: 'State Architecture', priority: 'tier1', months: [7, 8], tags: ['frontend-sd'] },
      { id: 'b6-api-layer', title: 'API-Layer Design', priority: 'tier1', months: [7, 8], tags: ['frontend-sd'] },
      { id: 'b6-authentication', title: 'Frontend Authentication', priority: 'tier1', months: [7, 8], tags: ['frontend-sd'], related: ['c9-authentication'] },
      { id: 'b6-performance', title: 'Frontend Performance', priority: 'tier1', months: [7, 8], tags: ['frontend-sd'] },
      { id: 'b6-caching', title: 'Frontend Caching', priority: 'tier1', months: [7, 8], tags: ['frontend-sd'] },
      { id: 'b6-pagination', title: 'Pagination/Infinite Scrolling', priority: 'tier1', months: [7, 8], tags: ['frontend-sd'] },
      { id: 'b6-infinite-scrolling', title: 'Infinite Scrolling', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'b6-pagination', months: [7, 8], tags: ['frontend-sd'] },
      { id: 'b6-realtime-ui', title: 'Real-time UI', priority: 'tier1', months: [7, 8], tags: ['frontend-sd'] },
      { id: 'b6-error-handling', title: 'Frontend Error Handling', priority: 'tier1', months: [7, 8], tags: ['frontend-sd'] },
      { id: 'b6-observability', title: 'Frontend Observability', priority: 'tier1', months: [7, 8], tags: ['frontend-sd'] },
      { id: 'b6-micro-frontends', title: 'Micro-frontends Concepts', priority: 'tier1', months: [7, 8], tags: ['frontend-sd'] },
      { id: 'b6-design-systems-sd', title: 'Design Systems (System Design)', priority: 'tier1', months: [7, 8], tags: ['frontend-sd'] },
      { id: 'b6-a11y-sd', title: 'Accessibility in Large Apps', priority: 'tier1', months: [7, 8], tags: ['frontend-sd', 'a11y'] },
      { id: 'b6-i18n', title: 'Internationalization', priority: 'tier1', months: [7, 8], tags: ['frontend-sd'] },
      { id: 'b6-practice-google-docs', title: 'Practice: Google Docs Frontend', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'b6-large-app-architecture', months: [7, 8], kind: 'system-design', tags: ['frontend-sd', 'practice'] },
      { id: 'b6-practice-youtube', title: 'Practice: YouTube Frontend', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'b6-large-app-architecture', months: [7, 8], kind: 'system-design', tags: ['frontend-sd', 'practice'] },
      { id: 'b6-practice-slack', title: 'Practice: Slack Frontend', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'b6-large-app-architecture', months: [7, 8], kind: 'system-design', tags: ['frontend-sd', 'practice'] },
      { id: 'b6-practice-gmail', title: 'Practice: Gmail Frontend', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'b6-large-app-architecture', months: [7, 8], kind: 'system-design', tags: ['frontend-sd', 'practice'] },
      { id: 'b6-practice-uber', title: 'Practice: Uber Web App', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'b6-large-app-architecture', months: [7, 8], kind: 'system-design', tags: ['frontend-sd', 'practice'] },
      { id: 'b6-practice-trading', title: 'Practice: Trading Dashboard', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'b6-large-app-architecture', months: [7, 8], kind: 'system-design', tags: ['frontend-sd', 'practice'] },
      { id: 'b6-practice-social-feed', title: 'Practice: Infinite Social Feed', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'b6-large-app-architecture', months: [7, 8], kind: 'system-design', tags: ['frontend-sd', 'practice'] },
    ],
  },
]
