import type { SectionSeed } from './build'

/** Track E — Applied AI Engineering (secondary until A/C/D strong) */
export const TRACK_E_SECTIONS: SectionSeed[] = [
  {
    id: 'E1',
    track: 'E',
    title: 'Python Essentials',
    order: 1,
    defaultKind: 'theory',
    defaultDepth: 'shallow',
    topics: [
      { id: 'e1-syntax', title: 'Python Syntax', priority: 'tier1', months: [9, 10], tags: ['python'] },
      { id: 'e1-collections', title: 'Collections', priority: 'tier1', months: [9, 10], tags: ['python'] },
      { id: 'e1-functions', title: 'Functions', priority: 'tier1', months: [9, 10], tags: ['python'] },
      { id: 'e1-classes', title: 'Classes', priority: 'tier1', months: [9, 10], tags: ['python'] },
      { id: 'e1-type-hints', title: 'Type Hints', priority: 'tier1', months: [9, 10], tags: ['python'] },
      { id: 'e1-venvs', title: 'Virtual Environments', priority: 'tier1', months: [9, 10], tags: ['python'] },
      { id: 'e1-packages', title: 'Package Management', priority: 'tier1', months: [9, 10], tags: ['python'] },
      { id: 'e1-async', title: 'Async Basics', priority: 'tier1', months: [9, 10], tags: ['python'] },
      { id: 'e1-numpy', title: 'NumPy Basics', priority: 'tier2', months: [9, 10], tags: ['python'] },
      { id: 'e1-pandas', title: 'Pandas Basics', priority: 'tier2', months: [9, 10], tags: ['python'] },
    ],
  },
  {
    id: 'E2',
    track: 'E',
    title: 'AI / ML Fundamentals',
    order: 2,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'e2-ml-vs-dl-vs-genai', title: 'ML vs Deep Learning vs Generative AI', priority: 'tier1', months: [9, 10], tags: ['ai'] },
      { id: 'e2-training-vs-inference', title: 'Training vs Inference', priority: 'tier1', months: [9, 10], tags: ['ai'] },
      { id: 'e2-supervised-unsupervised', title: 'Supervised vs Unsupervised Concepts', priority: 'tier1', months: [9, 10], tags: ['ai'] },
      { id: 'e2-neural-networks', title: 'Neural-Network Concepts', priority: 'tier1', months: [9, 10], tags: ['ai'] },
      { id: 'e2-transformers', title: 'Transformers Conceptually', priority: 'tier1', months: [9, 10], tags: ['ai'] },
      { id: 'e2-tokens', title: 'Tokens', priority: 'tier1', months: [9, 10], tags: ['ai'] },
      { id: 'e2-tokenization', title: 'Tokenization', priority: 'tier1', months: [9, 10], tags: ['ai'] },
      { id: 'e2-embeddings', title: 'Embeddings', priority: 'tier1', months: [9, 10], tags: ['ai'], related: ['e5-embeddings'] },
      { id: 'e2-attention', title: 'Attention Conceptually', priority: 'tier1', months: [9, 10], tags: ['ai'] },
      { id: 'e2-context-windows', title: 'Context Windows', priority: 'tier1', months: [9, 10], tags: ['ai'] },
      { id: 'e2-temperature', title: 'Temperature/Sampling', priority: 'tier1', months: [9, 10], tags: ['ai'] },
      { id: 'e2-hallucinations', title: 'Hallucinations', priority: 'tier1', months: [9, 10], tags: ['ai'] },
      { id: 'e2-fine-tuning', title: 'Fine-Tuning', priority: 'tier2', months: [10, 11], tags: ['ai'] },
      { id: 'e2-quantization', title: 'Quantization', priority: 'tier2', months: [10, 11], tags: ['ai'] },
      { id: 'e2-gpu-inference', title: 'GPU Inference Concepts', priority: 'tier2', months: [10, 11], tags: ['ai'] },
    ],
  },
  {
    id: 'E3',
    track: 'E',
    title: 'LLM APIs',
    order: 3,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'e3-chat-apis', title: 'Chat/Completion APIs', priority: 'tier1', months: [9, 10], tags: ['llm'] },
      { id: 'e3-messages', title: 'System/User Messages', priority: 'tier1', months: [9, 10], tags: ['llm'] },
      { id: 'e3-structured-outputs', title: 'Structured Outputs', priority: 'tier1', months: [9, 10], tags: ['llm'] },
      { id: 'e3-json-schemas', title: 'JSON Schemas', priority: 'tier1', months: [9, 10], tags: ['llm'] },
      { id: 'e3-tool-calling', title: 'Tool/Function Calling', priority: 'tier1', months: [9, 10], tags: ['llm'], related: ['e7-tool-calling'] },
      { id: 'e3-streaming', title: 'Streaming', priority: 'tier1', months: [9, 10], tags: ['llm'] },
      { id: 'e3-token-usage', title: 'Token Usage', priority: 'tier1', months: [9, 10], tags: ['llm'] },
      { id: 'e3-rate-limits', title: 'Rate Limits', priority: 'tier1', months: [9, 10], tags: ['llm'], related: ['d10-rate-limiter'] },
      { id: 'e3-retries', title: 'Retries', priority: 'tier1', months: [9, 10], tags: ['llm'], related: ['c12-retries'] },
      { id: 'e3-model-selection', title: 'Model Selection', priority: 'tier1', months: [9, 10], tags: ['llm'] },
      { id: 'e3-cost-latency-quality', title: 'Cost/Latency/Quality Trade-offs', priority: 'tier1', months: [9, 10], tags: ['llm'] },
    ],
  },
  {
    id: 'E4',
    track: 'E',
    title: 'Prompt & Context Engineering',
    order: 4,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'e4-system-instructions', title: 'System Instructions', priority: 'tier1', months: [9, 10], tags: ['prompting'] },
      { id: 'e4-few-shot', title: 'Few-Shot Prompting', priority: 'tier1', months: [9, 10], tags: ['prompting'] },
      { id: 'e4-structured-prompting', title: 'Structured Prompting', priority: 'tier1', months: [9, 10], tags: ['prompting'] },
      { id: 'e4-context-management', title: 'Context Management', priority: 'tier1', months: [9, 10], tags: ['prompting'] },
      { id: 'e4-prompt-injection', title: 'Prompt-Injection Awareness', priority: 'tier1', months: [9, 10], tags: ['prompting', 'security'], related: ['e11-prompt-injection'] },
      { id: 'e4-context-optimization', title: 'Context-Window Optimization', priority: 'tier1', months: [9, 10], tags: ['prompting'] },
      { id: 'e4-output-validation', title: 'Output Validation', priority: 'tier1', months: [9, 10], tags: ['prompting'] },
      { id: 'e4-prompt-versioning', title: 'Prompt Versioning', priority: 'tier2', months: [10, 11], tags: ['prompting'] },
    ],
  },
  {
    id: 'E5',
    track: 'E',
    title: 'Embeddings & Semantic Search',
    order: 5,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'e5-embeddings', title: 'Embeddings', priority: 'tier1', months: [9, 10], tags: ['search'], related: ['e2-embeddings'] },
      { id: 'e5-similarity', title: 'Vector Similarity', priority: 'tier1', months: [9, 10], tags: ['search'] },
      { id: 'e5-cosine', title: 'Cosine Similarity', priority: 'tier1', months: [9, 10], tags: ['search'] },
      { id: 'e5-semantic-search', title: 'Semantic Search', priority: 'tier1', months: [9, 10], tags: ['search'] },
      { id: 'e5-metadata-filtering', title: 'Metadata Filtering', priority: 'tier1', months: [9, 10], tags: ['search'] },
      { id: 'e5-hybrid-search', title: 'Hybrid Search', priority: 'tier1', months: [9, 10], tags: ['search'] },
      { id: 'e5-ann', title: 'Approximate Nearest Neighbour Search', priority: 'tier2', months: [10, 11], tags: ['search'] },
      { id: 'e5-vector-indexes', title: 'Vector Indexes', priority: 'tier2', months: [10, 11], tags: ['search'] },
      { id: 'e5-pgvector', title: 'pgvector Practical Usage', priority: 'tier2', curriculumLevel: 'nested-concept', parentTopicId: 'e5-vector-indexes', months: [10, 11], tags: ['search', 'postgresql'], related: ['c7-indexes'] },
    ],
  },
  {
    id: 'E6',
    track: 'E',
    title: 'RAG',
    order: 6,
    defaultKind: 'theory',
    defaultDepth: 'deep',
    topics: [
      { id: 'e6-ingestion', title: 'Document Ingestion', priority: 'tier1', months: [9, 10], tags: ['rag'] },
      { id: 'e6-parsing', title: 'Document Parsing', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'e6-ingestion', months: [9, 10], tags: ['rag'] },
      { id: 'e6-chunking', title: 'Chunking Strategies', priority: 'tier1', months: [9, 10], tags: ['rag'] },
      { id: 'e6-embedding-models', title: 'Embedding Models', priority: 'tier1', months: [9, 10], tags: ['rag'] },
      { id: 'e6-indexing', title: 'Indexing', priority: 'tier1', curriculumLevel: 'nested-concept', parentTopicId: 'e6-embedding-models', months: [9, 10], tags: ['rag'] },
      { id: 'e6-retrieval', title: 'Retrieval', priority: 'tier1', months: [9, 10], tags: ['rag'] },
      { id: 'e6-top-k', title: 'Top-K Retrieval', priority: 'tier1', months: [9, 10], tags: ['rag'] },
      { id: 'e6-metadata-filtering', title: 'Metadata Filtering (RAG)', priority: 'tier1', months: [9, 10], tags: ['rag'] },
      { id: 'e6-hybrid-retrieval', title: 'Hybrid Retrieval', priority: 'tier1', months: [9, 10], tags: ['rag'] },
      { id: 'e6-reranking', title: 'Reranking', priority: 'tier1', months: [9, 10], tags: ['rag'] },
      { id: 'e6-context-construction', title: 'Context Construction', priority: 'tier1', months: [9, 10], tags: ['rag'] },
      { id: 'e6-grounding', title: 'Grounding/Citations', priority: 'tier1', months: [9, 10], tags: ['rag'] },
      { id: 'e6-evaluation', title: 'Retrieval Evaluation', priority: 'tier1', months: [9, 10], tags: ['rag'], related: ['e9-retrieval-metrics'] },
      { id: 'e6-failure-modes', title: 'RAG Failure Modes', priority: 'tier1', months: [9, 10], tags: ['rag'] },
    ],
  },
  {
    id: 'E7',
    track: 'E',
    title: 'Agents & Tool Use',
    order: 7,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'e7-tool-calling', title: 'Tool Calling', priority: 'tier1', months: [10, 11], tags: ['agents'], related: ['e3-tool-calling'] },
      { id: 'e7-workflows', title: 'Multi-Step Workflows', priority: 'tier1', months: [10, 11], tags: ['agents'] },
      { id: 'e7-agent-loops', title: 'Agent Loops', priority: 'tier1', months: [10, 11], tags: ['agents'] },
      { id: 'e7-state', title: 'State', priority: 'tier1', months: [10, 11], tags: ['agents'] },
      { id: 'e7-memory', title: 'Memory Concepts', priority: 'tier1', months: [10, 11], tags: ['agents'] },
      { id: 'e7-planning', title: 'Planning', priority: 'tier1', months: [10, 11], tags: ['agents'] },
      { id: 'e7-human-in-loop', title: 'Human-in-the-Loop', priority: 'tier1', months: [10, 11], tags: ['agents'] },
      { id: 'e7-error-recovery', title: 'Error Recovery', priority: 'tier1', months: [10, 11], tags: ['agents'] },
      { id: 'e7-tool-permissions', title: 'Tool Permissions', priority: 'tier1', months: [10, 11], tags: ['agents', 'security'] },
      { id: 'e7-sandboxing', title: 'Sandboxing/Security', priority: 'tier1', months: [10, 11], tags: ['agents', 'security'] },
      { id: 'e7-multi-agent', title: 'Multi-Agent Architectures', priority: 'tier2', months: [11, 12], tags: ['agents'] },
    ],
  },
  {
    id: 'E8',
    track: 'E',
    title: 'AI Frameworks',
    order: 8,
    defaultKind: 'theory',
    defaultDepth: 'shallow',
    topics: [
      { id: 'e8-langchain', title: 'LangChain/LangGraph or Equivalent', priority: 'tier2', months: [11, 12], tags: ['frameworks'] },
      { id: 'e8-orchestration', title: 'Workflow Orchestration Frameworks', priority: 'tier2', curriculumLevel: 'nested-concept', parentTopicId: 'e8-langchain', months: [11, 12], tags: ['frameworks'] },
    ],
  },
  {
    id: 'E9',
    track: 'E',
    title: 'AI Evaluation',
    order: 9,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'e9-golden-datasets', title: 'Golden Datasets', priority: 'tier1', months: [10, 11], tags: ['evaluation'] },
      { id: 'e9-offline-evals', title: 'Offline Evaluations', priority: 'tier1', months: [10, 11], tags: ['evaluation'] },
      { id: 'e9-retrieval-metrics', title: 'Retrieval Metrics', priority: 'tier1', months: [10, 11], tags: ['evaluation'] },
      { id: 'e9-correctness', title: 'Answer Correctness', priority: 'tier1', months: [10, 11], tags: ['evaluation'] },
      { id: 'e9-groundedness', title: 'Groundedness', priority: 'tier1', months: [10, 11], tags: ['evaluation'] },
      { id: 'e9-tool-correctness', title: 'Tool-Call Correctness', priority: 'tier1', months: [10, 11], tags: ['evaluation'] },
      { id: 'e9-regression', title: 'Regression Testing', priority: 'tier1', months: [10, 11], tags: ['evaluation'] },
      { id: 'e9-human-eval', title: 'Human Evaluation', priority: 'tier1', months: [10, 11], tags: ['evaluation'] },
      { id: 'e9-llm-as-judge', title: 'LLM-as-Judge', priority: 'tier2', months: [11, 12], tags: ['evaluation'] },
      { id: 'e9-ab-testing', title: 'A/B Testing', priority: 'tier2', months: [11, 12], tags: ['evaluation'] },
    ],
  },
  {
    id: 'E10',
    track: 'E',
    title: 'Production AI Engineering',
    order: 10,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'e10-streaming', title: 'Streaming', priority: 'tier1', months: [10, 11], tags: ['production-ai'] },
      { id: 'e10-async', title: 'Async Processing', priority: 'tier1', months: [10, 11], tags: ['production-ai'] },
      { id: 'e10-queues', title: 'Queues', priority: 'tier1', months: [10, 11], tags: ['production-ai'], related: ['d5-queues'] },
      { id: 'e10-caching', title: 'Caching', priority: 'tier1', months: [10, 11], tags: ['production-ai'], related: ['c10-cache-aside'] },
      { id: 'e10-retries', title: 'Retries', priority: 'tier1', months: [10, 11], tags: ['production-ai'] },
      { id: 'e10-rate-limiting', title: 'Rate Limiting', priority: 'tier1', months: [10, 11], tags: ['production-ai'] },
      { id: 'e10-timeouts', title: 'Timeouts', priority: 'tier1', months: [10, 11], tags: ['production-ai'] },
      { id: 'e10-fallbacks', title: 'Fallback Models', priority: 'tier1', months: [10, 11], tags: ['production-ai'] },
      { id: 'e10-model-routing', title: 'Model Routing', priority: 'tier1', months: [10, 11], tags: ['production-ai'] },
      { id: 'e10-cost-tracking', title: 'Cost Tracking', priority: 'tier1', months: [10, 11], tags: ['production-ai'] },
      { id: 'e10-token-budgets', title: 'Token Budgeting', priority: 'tier1', months: [10, 11], tags: ['production-ai'] },
      { id: 'e10-observability', title: 'Observability', priority: 'tier1', months: [10, 11], tags: ['production-ai'], related: ['c16-otel'] },
      { id: 'e10-version-tracking', title: 'Prompt/Version Tracking', priority: 'tier1', months: [10, 11], tags: ['production-ai'] },
      { id: 'e10-pii', title: 'PII Handling', priority: 'tier1', months: [10, 11], tags: ['production-ai', 'security'] },
      { id: 'e10-secrets', title: 'Secrets', priority: 'tier1', months: [10, 11], tags: ['production-ai', 'security'] },
      { id: 'e10-access-control', title: 'Access Control', priority: 'tier1', months: [10, 11], tags: ['production-ai', 'security'] },
    ],
  },
  {
    id: 'E11',
    track: 'E',
    title: 'AI Security',
    order: 11,
    defaultKind: 'theory',
    defaultDepth: 'medium',
    topics: [
      { id: 'e11-prompt-injection', title: 'Prompt Injection', priority: 'tier1', months: [10, 11], tags: ['ai-security'] },
      { id: 'e11-indirect-injection', title: 'Indirect Prompt Injection', priority: 'tier1', months: [10, 11], tags: ['ai-security'] },
      { id: 'e11-data-leakage', title: 'Data Leakage', priority: 'tier1', months: [10, 11], tags: ['ai-security'] },
      { id: 'e11-tool-abuse', title: 'Tool Abuse', priority: 'tier1', months: [10, 11], tags: ['ai-security'] },
      { id: 'e11-excessive-agency', title: 'Excessive Agency', priority: 'tier1', months: [10, 11], tags: ['ai-security'] },
      { id: 'e11-io-validation', title: 'Input/Output Validation', priority: 'tier1', months: [10, 11], tags: ['ai-security'] },
      { id: 'e11-permissions', title: 'Permission Boundaries', priority: 'tier1', months: [10, 11], tags: ['ai-security'] },
      { id: 'e11-sensitive-data', title: 'Sensitive-Data Handling', priority: 'tier1', months: [10, 11], tags: ['ai-security'] },
      { id: 'e11-adversarial', title: 'Adversarial Testing', priority: 'tier2', months: [11, 12], tags: ['ai-security'] },
    ],
  },
  {
    id: 'E12',
    track: 'E',
    title: 'AI System Design',
    order: 12,
    defaultKind: 'system-design',
    defaultDepth: 'medium',
    topics: [
      { id: 'e12-enterprise-rag', title: 'Enterprise RAG/Search System', priority: 'tier1', months: [11, 12], tags: ['ai-sd'] },
      { id: 'e12-ai-support', title: 'AI Customer-Support System', priority: 'tier1', months: [11, 12], tags: ['ai-sd'] },
      { id: 'e12-coding-assistant', title: 'Coding Assistant', priority: 'tier1', months: [11, 12], tags: ['ai-sd'] },
      { id: 'e12-document-analysis', title: 'Document-Analysis Platform', priority: 'tier1', months: [11, 12], tags: ['ai-sd'] },
      { id: 'e12-research-assistant', title: 'AI Research Assistant', priority: 'tier1', months: [11, 12], tags: ['ai-sd'] },
      { id: 'e12-tool-agent', title: 'AI Agent with External Tools', priority: 'tier1', months: [11, 12], tags: ['ai-sd'] },
      { id: 'e12-recommendation', title: 'Recommendation/Personalization System', priority: 'tier2', months: [11, 12], tags: ['ai-sd'] },
      { id: 'e12-multi-tenant', title: 'Multi-Tenant AI Platform', priority: 'tier2', months: [11, 12], tags: ['ai-sd'] },
    ],
  },
]
