/** Printable end-matter for the Graphs handbook (A8). */
export const GRAPH_ALGORITHMS_SUMMARY = {
  title: 'Summary of All Core Graph Algorithms',
  intro:
    'Cheat sheet for interview and contest prep. Assumptions: 0-indexed vertices, adjacency list unless noted.',
  algorithms: [
    ['1', 'BFS', 'Level-order / unweighted shortest path', 'Queue; first visit = shortest', 'O(V+E)', 'O(V)'],
    ['2', 'DFS Recursive', 'Traversal, paths, topo, SCC', 'Go deep; call stack', 'O(V+E)', 'O(V)'],
    ['3', 'DFS Iterative', 'Same as DFS, no recursion', 'Explicit stack', 'O(V+E)', 'O(V)'],
    ['4', 'Cycle (Undirected)', 'Is there a cycle?', 'Visited neighbor ≠ parent', 'O(V+E)', 'O(V)'],
    ['5a', 'Shortest cycle', 'Length of shortest cycle', 'Per edge: BFS without that edge', 'O(E(V+E))', 'O(V)'],
    ['5b', 'All cycles', 'Enumerate cycles', 'DFS path + back edge; normalize', 'cycle-dependent', 'O(V+)'],
    ['6', 'Topological sort', 'Valid order in a DAG', 'Kahn indegree-0 / DFS post-order', 'O(V+E)', 'O(V)'],
    ['7', 'Cycle (Directed)', 'Is there a directed cycle?', 'GRAY back edge or Kahn count < V', 'O(V+E)', 'O(V)'],
    ['8', 'Shortest path DAG', 'SSSP in weighted DAG', 'Topo order + one-pass relax', 'O(V+E)', 'O(V)'],
    ['9', 'Dijkstra', 'SSSP, non-negative weights', 'Min-heap; greedy settle', 'O((V+E) log V)', 'O(V)'],
    ['10', "Prim's MST", 'Minimum spanning tree', 'Grow tree by min edge to new vertex', 'O(E log V)', 'O(V+E)'],
    ['11', 'Kosaraju SCC', 'Strongly connected components', '2× DFS: finish order + reverse', 'O(V+E)', 'O(V+E)'],
    ['12', 'Bellman-Ford', 'SSSP + negative weights', 'Relax all edges V−1 times', 'O(VE)', 'O(V)'],
    ['13', 'Articulation points', 'Cut vertices', 'disc/low; root ≥2 children', 'O(V+E)', 'O(V)'],
    ['14', 'Bridges', 'Cut edges', 'low[v] > disc[u]', 'O(V+E)', 'O(V)'],
    ['15', 'Tarjan SCC', 'SCCs in one DFS', 'Stack + low[u]==disc[u]', 'O(V+E)', 'O(V+E)'],
    ['16', 'Kruskal MST', 'Minimum spanning tree', 'Sort edges + Union-Find', 'O(E log E)', 'O(V+E)'],
    ['17', 'Floyd-Warshall', 'All-pairs shortest path', 'DP via each intermediate k', 'O(V³)', 'O(V²)'],
    ['18', 'Bipartite check', '2-colorable?', 'BFS/DFS 2-color; conflict → no', 'O(V+E)', 'O(V)'],
    ['19', '0-1 BFS', 'SSSP weights 0 or 1', 'Deque: 0 front, 1 back', 'O(V+E)', 'O(V)'],
  ] as const,
  shortestPath: [
    ['BFS', 'Any', 'Unit (unweighted)', 'N/A'],
    ['0-1 BFS', 'Any', '0 or 1', 'N/A'],
    ['DAG shortest', 'DAG', 'Any', 'No (acyclic)'],
    ['Dijkstra', 'Any', 'Non-negative', 'No'],
    ['Bellman-Ford', 'Any', 'Any', 'Detects'],
    ['Floyd-Warshall', 'Any', 'Any', 'Detects (dist[i][i]<0)'],
  ] as const,
  mst: [
    ['Prim', 'Node-based, heap', 'O(E log V)', 'Dense / adj-list graphs'],
    ['Kruskal', 'Edge-based, sort + DSU', 'O(E log E)', 'Sparse / edge-list graphs'],
  ] as const,
  scc: [
    ['Kosaraju', '2 DFS', 'Finish order + reversed graph'],
    ['Tarjan', '1 DFS', 'Stack + low/disc; one pass'],
  ] as const,
  decisionRules: [
    'Unweighted shortest path → BFS (or multi-source BFS).',
    'Weights only 0/1 → 0-1 BFS (deque).',
    'Non-negative weights → Dijkstra.',
    'Negative weights / detect neg cycle → Bellman-Ford.',
    'All-pairs, small V → Floyd-Warshall.',
    'DAG order / deps → Topological sort (Kahn or DFS).',
    'Directed mutual reachability → SCC (Kosaraju or Tarjan).',
    'Critical edge → Bridge; critical vertex → Articulation point.',
    'Connect all with min cost → MST (Kruskal or Prim).',
    'Odd cycle / 2-coloring → Bipartite check.',
  ],
}
