import type { TopicContent } from '@/domain/types'

export const content: TopicContent = {
  whatIsIt:
    'The JIT (Just-In-Time) compiler translates hot JVM bytecode into native machine code at runtime. HotSpot uses tiered compilation: C1 (fast compile, light opts) → C2 (aggressive opts, inlining, escape analysis). Methods compile after invocation/loop thresholds; OSR compiles long running loops.',
  whyExists:
    'Pure interpretation is too slow for production. JIT adapts to actual workloads—inlines hot callees, eliminates dead paths, unboxes—turning bytecode into near-native speed after warm-up while deferring compile cost for cold code.',
  mentalModel:
    'Interpreter runs first; counter hits threshold → C1 quick native code → hotter still → C2 optimized. Deoptimization drops back to interpreter if assumptions break (class loaded, branch profile wrong).',
  howItWorks: [
    {
      type: 'list',
      items: [
        'Invocation counter + back-edge counter trigger compile.',
        'C1 (client): fast compile, some inlining, used on tiered level 3.',
        'C2 (server): full optimizations—inlining limits, loop unroll, vectorization.',
        'Tiered compilation (-XX:+TieredCompilation default): interpreter → C1 → C2.',
        'OSR (On-Stack Replacement): compile loop body mid-execution in long loops.',
        'Deopt: invalid speculation (monomorphic call becomes megamorphic) reverts to interpreter.',
        '-XX:CompileThreshold, -XX:+PrintCompilation, JITWatch for analysis.',
      ],
    },
    {
      type: 'table',
      headers: ['Tier', 'Compiler', 'Typical role'],
      rows: [
        ['0', 'Interpreter', 'Cold code, profiling'],
        ['1-3', 'C1', 'Fast native, profile data'],
        ['4', 'C2', 'Max optimization hot methods'],
      ],
    },
  ],
  example: [
    {
      type: 'code',
      language: 'bash',
      caption: 'Observe compilation',
      code: `java -XX:+PrintCompilation -XX:CompileThreshold=100 -jar app.jar 2> compile.log
# Lines like:  123    4       3  com.app.Service::hotMethod (45 bytes)`,
    },
    {
      type: 'code',
      language: 'java',
      caption: 'Code shape affects inlining',
      code: `// Small private helpers often inlined into hot loop
private int score(int x) { return x * x + 1; }
void hot() {
    for (int i = 0; i < 1_000_000; i++) sum += score(i);
}`,
    },
  ],
  tradeoffs: {
    advantages: [
      'Peak throughput near native after warm-up',
      'Profile-guided optimizations on real branches',
      'No separate compile step for deploy artifact',
    ],
    disadvantages: [
      'Warm-up latency before C2 kicks in',
      'Compilation CPU spikes at startup',
      'Deopt pauses and obscure perf cliffs',
      'Code cache pressure (-XX:ReservedCodeCacheSize)',
    ],
    alternatives: ['AOT (GraalVM native-image) for instant peak cold start', 'JDK Flight Recorder for compile events'],
    whenToUse: ['Long-running server JVMs amortize JIT cost', 'Throughput over cold-start ms'],
    whenNotToUse: ['Serverless strict cold start—consider AOT', 'Tiny one-shot CLI'],
  },
  failureModes: [
    'CodeCache full → stop compiling → interpreter fallback perf crash.',
    'Megamorphic virtual calls block inlining hotspot.',
    'Assuming steady-state perf in first 30s benchmark—misleading without warm-up.',
    'Huge generated bytecode (dynamic proxies) explodes compile queue.',
  ],
  interview: {
    expectations: [
      'C1 vs C2 tiered compilation',
      'Hot methods compile after threshold',
      'Inlining and deoptimization concept',
    ],
    commonQuestions: ['How JVM makes code fast?', 'What is deoptimization?', 'Warm-up in benchmarks?'],
    followUps: ['OSR when?', 'PrintCompilation read?', 'Graal vs C2?'],
    misconceptions: ['Java always interpreted', 'All methods compiled at startup', 'JIT same as AOT'],
    traps: ['Microbench without warm-up', 'Ignoring code cache limits'],
    strongSignals: ['Tiered path interpreter→C1→C2', 'Mentions profile-driven inlining', 'Warm-up iterations in perf tests'],
  },
  keyTakeaways: [
    'HotSpot JIT: tiered C1 then C2 on hot code.',
    'Compile triggered by invocation/back-edge counters.',
    'Inlining key win; deopt when assumptions fail.',
    'Warm up before measuring server throughput.',
    'PrintCompilation / JFR for compile diagnostics.',
  ],
  interviewQuestions: [
    { level: 'basic', question: 'Why JIT instead of only interpreter?', answerHint: 'Hot paths compiled to native with optimizations; cold code stays cheap in interpreter.' },
    { level: 'intermediate', question: 'C1 vs C2?', answerHint: 'C1 fast compile lighter opts; C2 slow compile aggressive inlining/vectorization for hottest methods.' },
    { level: 'advanced', question: 'What is deoptimization?', answerHint: 'Invalidated compiled assumption—revert running frame to interpreter, re-profile, maybe recompile.' },
  ],
  flashcards: [
    { front: 'Tiered compilation default path', back: 'Interpreter → C1 → C2 as methods get hotter.' },
    { front: 'OSR', back: 'On-Stack Replacement—compile long-running loop body mid-flight.' },
    { front: 'Deoptimization trigger example', back: 'Monomorphic inline site receives new implementing class.' },
  ],
  quickRevision: [
    'C1 fast C2 aggressive',
    'Hot counters trigger compile',
    'Inlining main win',
    'Deopt on bad guess',
    'Warm up benchmarks',
    'CodeCache limit',
    'PrintCompilation flag',
  ],
  production: {
    performance: [
      'Load-test warm-up before taking SLA measurements; first minutes after deploy are not steady state.',
      'Watch CodeCache usage—Increase ReservedCodeCacheSize if "CodeCache is full" in logs.',
    ],
    observability: [
      'JFR EventCompile and EventCompilationFailure for compile stalls.',
      'async-profiler -e compile shows compile CPU overhead during startup.',
    ],
    scalability: [
      'Many JVMs cold-starting together causes compile CPU storm—stagger deploys or reuse warmed pools.',
    ],
    maintainability: [
      'Keep hot methods small and monomorphic where possible—helps inlining; avoid megamorphic call sites in inner loops.',
    ],
  },
}
