#!/usr/bin/env python3
"""Part 2: remaining wave-09 topics appended to TOPICS dict."""
import os

# TOPICS and helpers already defined in gen_phase4_wave09.py

TOPICS["b4-nextjs"] = T(
    whatIsIt="Next.js is React meta-framework with file-based routing, SSR/SSG/ISR, React Server Components (RSC), API routes, and built-in optimization (image, font, code splitting).",
    whyExists="SPAs hurt SEO and first paint. Next.js unifies routing, data fetching at build/request time, and deployment patterns for production React apps.",
    mentalModel="Pages/app router map URLs to components; server renders HTML shell + streams RSC payload; client hydrates interactive islands; data fetch colocated with route.",
    howItWorks=[{"type": "list", "items": [
        "App Router (app/): layouts, loading.tsx, error boundaries, RSC by default",
        "Server Components fetch DB directly; Client Components use 'use client'",
        "SSR: render on request; SSG: build time; ISR: revalidate interval",
        "Route handlers replace pages/api REST endpoints",
        "Middleware for auth, redirects, geo at edge",
    ]}],
    example=[{"type": "code", "lang": "typescript", "code": "// app/posts/[id]/page.tsx — Server Component\nexport default async function Page({ params }: { params: { id: string } }) {\n  const post = await db.post.find(params.id);\n  return <Article post={post} />;\n}", "caption": "RSC data fetch"}],
    tradeoffs={"advantages": ["SEO + fast FCP", "Colocated routing/data", "Vercel-optimized defaults"], "disadvantages": ["RSC mental model steep", "Vendor coupling if Vercel-specific"], "alternatives": ["Remix", "Vite SPA + SSR manual"], "whenToUse": ["Production React sites", "Content + dashboards"], "whenNotToUse": ["Tiny widget embed"]},
    failureModes=["Accidentally marking entire tree 'use client'", "Fetching in client useEffect losing SSR benefit", "ISR stale content without on-demand revalidate", "Leaking secrets in client bundle"],
    production={"performance": ["RSC for data-heavy; dynamic import client widgets"], "scalability": ["Edge middleware; CDN cache static"], "observability": ["Web vitals RUM; server timing headers"], "security": ["Env vars server-only; validate server actions"]},
    interview={"expectations": ["SSR vs SSG vs ISR", "RSC vs client components"], "commonQuestions": ["Next.js rendering modes?"], "followUps": ["When Server Component?"], "misconceptions": ["All Next.js is SSR"], "traps": ["useEffect fetch on landing page"], "strongSignals": ["App router, RSC boundaries, caching tags"]},
    keyTakeaways=["File-based routing app/", "RSC default — 'use client' when needed", "SSR/SSG/ISR tradeoffs", "Server Actions for mutations", "Middleware at edge"],
    iq=[{"level": "basic", "q": "SSR vs SSG?", "h": "SSR per request; SSG at build time."}, {"level": "intermediate", "q": "Server vs Client Component?", "h": "Server: data/no hooks; Client: interactivity/hooks."}, {"level": "advanced", "q": "ISR use case?", "h": "Semi-static pages revalidated on interval without full rebuild."}],
    flashcards=[{"f": "RSC", "b": "Server-rendered React; no client JS by default"}, {"f": "ISR", "b": "Incremental static regen with revalidate timer"}],
    quickRevision=["App router", "RSC + use client", "SSR/SSG/ISR", "Route handlers", "Middleware edge", "Server Actions"],
)

TOPICS["b5-css-architecture"] = T(
    whatIsIt="CSS architecture organizes styles at scale — methodologies (BEM, ITCSS), component-scoped CSS (CSS Modules, CSS-in-JS), design tokens, and layering to avoid specificity wars and global leakage.",
    whyExists="Global CSS does not scale in large teams. Without structure, !important cascades, duplicate rules, and unmaintainable selectors accumulate.",
    mentalModel="Layers stack: reset → tokens → utilities → components → pages. Each component owns styles; globals only for foundations.",
    howItWorks=[{"type": "list", "items": [
        "BEM: Block__element--modifier naming avoids deep nesting",
        "CSS Modules: locally scoped class hashes at build",
        "ITCSS: inverted triangle — settings, tools, generic, elements, objects, components, utilities",
        "Design tokens as CSS variables for theme consistency",
        "Lint stylelint + forbid global tag selectors in components",
    ]}],
    example=[{"type": "code", "lang": "css", "code": "/* BEM */\n.card { }\n.card__title { }\n.card--featured { }\n\n/* Token */\n:root { --color-primary: #0066cc; }", "caption": "BEM + tokens"}],
    tradeoffs={"advantages": ["Predictable specificity", "Team parallel work"], "disadvantages": ["Naming ceremony", "CSS-in-JS runtime cost"], "alternatives": ["Tailwind utility-first", "Shadow DOM encapsulation"], "whenToUse": ["Large multi-team frontends"], "whenNotToUse": ["Single landing page"]},
    failureModes=["Global !important overrides", "Deep selector chains break encapsulation", "Duplicated token values drift", "CSS-in-JS bundle bloat"],
    production={"maintainability": ["Document layering; enforce BEM/modules in review"], "performance": ["Critical CSS inline; purge unused utilities"]},
    interview={"expectations": ["BEM basics", "Scoped vs global CSS"], "commonQuestions": ["Scale CSS in large app?"], "followUps": ["CSS Modules vs styled-components?"], "misconceptions": ["Tailwind replaces architecture entirely"], "traps": ["Nested .card .title .link selectors"], "strongSignals": ["Tokens, layers, scoped components"]},
    keyTakeaways=["Layer and scope styles", "BEM or CSS Modules for components", "Tokens for theming", "Avoid deep global selectors", "Lint and document conventions"],
    iq=[{"level": "basic", "q": "BEM naming?", "h": "Block__element--modifier."}, {"level": "intermediate", "q": "CSS Modules benefit?", "h": "Local scope; no global class collisions."}, {"level": "advanced", "q": "ITCSS layers?", "h": "Settings→utilities inverted specificity triangle."}],
    flashcards=[{"f": "BEM", "b": "Block__element--modifier naming convention"}, {"f": "Design token", "b": "Named variable for color/spacing/typography"}],
    quickRevision=["BEM/Modules", "ITCSS layers", "CSS variables tokens", "No deep globals", "Stylelint enforce", "Component owns styles"],
)

TOPICS["b5-design-systems"] = T(
    whatIsIt="Design system is shared library of UI components, tokens, patterns, and documentation ensuring consistent look, accessibility, and dev speed across products.",
    whyExists="Without system, each team reinvents buttons/modals; UX inconsistent; a11y gaps repeat. Central system reduces duplication and drift.",
    mentalModel="LEGO kit: tokens = block sizes/colors; components = standard bricks; docs = assembly guide; consumers compose screens from kit.",
    howItWorks=[{"type": "list", "items": [
        "Foundation: color, typography, spacing tokens",
        "Primitive components: Button, Input, Dialog with variants",
        "Composition patterns: forms, navigation documented",
        "Storybook/Chromatic for visual regression",
        "Semantic versioning + migration guides for breaking changes",
    ]}],
    example=[{"type": "code", "lang": "tsx", "code": "<Button variant=\"primary\" size=\"md\" disabled={loading}>\n  Submit\n</Button>", "caption": "Token-driven component API"}],
    tradeoffs={"advantages": ["Consistency", "Faster delivery", "Central a11y fixes"], "disadvantages": ["Upfront investment", "Governance overhead"], "alternatives": ["Ad-hoc component copy-paste", "Third-party UI kit only"], "whenToUse": ["Multi-product orgs", "Brand-critical apps"], "whenNotToUse": ["One-off prototype"]},
    failureModes=["System ignored — teams fork components", "Breaking change without codemod", "Tokens diverge from Figma", "Over-abstracted API unusable"],
    production={"maintainability": ["RFC process for new components", "Deprecation policy"], "observability": ["Track adoption metrics per package version"], "cost": ["Shared CI for visual diff"]},
    interview={"expectations": ["Tokens + components + docs", "Versioning strategy"], "commonQuestions": ["Build vs buy design system?"], "followUps": ["Prevent drift?"], "misconceptions": ["Just a component library"], "traps": ["No a11y in primitives"], "strongSignals": ["Storybook, semver, token pipeline from Figma"]},
    keyTakeaways=["Tokens + components + guidelines", "Storybook for docs/visual test", "Semver and migration paths", "Governance prevents drift", "a11y baked into primitives"],
    iq=[{"level": "basic", "q": "Design system parts?", "h": "Tokens, components, patterns, documentation."}, {"level": "intermediate", "q": "Prevent team drift?", "h": "Lint against raw HTML; package adoption metrics."}, {"level": "advanced", "q": "Breaking button API change?", "h": "Major semver; codemod; dual export deprecation period."}],
    flashcards=[{"f": "Design token", "b": "Single source for visual primitive values"}, {"f": "Storybook", "b": "Interactive catalog and visual test hub"}],
    quickRevision=["Tokens foundation", "Variant components", "Storybook docs", "Semver migrations", "a11y in primitives", "Governance RFC"],
)

# --- e1 ---
TOPICS["e1-numpy"] = T(
    whatIsIt="NumPy provides ndarrays — homogeneous N-dimensional arrays with vectorized C-backed operations, broadcasting, linear algebra, and slicing without Python loops.",
    whyExists="Pure Python lists are slow for numeric workloads. NumPy enables ML, science, and data prep with memory-efficient contiguous arrays.",
    mentalModel="Spreadsheet matrix in RAM: shape (rows, cols); operations apply element-wise or along axes without explicit loops.",
    howItWorks=[{"type": "list", "items": [
        "np.array creates ndarray with dtype (float64, int32)",
        "Shape, reshape, transpose manipulate layout without copy when possible",
        "Broadcasting aligns shapes for element-wise ops",
        "Vectorized ufuncs (np.sin, np.dot) run in C",
        "Boolean masking and fancy indexing select subsets",
    ]}],
    example=[{"type": "code", "lang": "python", "code": "import numpy as np\na = np.array([[1,2],[3,4]])\nb = a * 2          # broadcast\nm = a @ a.T        # matrix multiply\nm[a > 2]           # mask", "caption": "Basics"}],
    tradeoffs={"advantages": ["Fast vectorized ops", "Ecosystem hub for pandas/sklearn"], "disadvantages": ["Homogeneous dtypes only", "Memory copies on bad slicing"], "alternatives": ["Pure Python", "JAX/Torch tensors"], "whenToUse": ["Numeric preprocessing", "Linear algebra"], "whenNotToUse": ["Heterogeneous records — use pandas"]},
    failureModes=["Unexpected copy on reshape vs view", "dtype overflow int32", "Broadcasting shape mismatch silent errors in older code"],
    production={"performance": ["Prefer views; avoid Python loops on elements", "Use float32 when precision allows"]},
    interview={"expectations": ["ndarray vs list", "Broadcasting rules"], "commonQuestions": ["What is broadcasting?"], "followUps": ["View vs copy?"], "misconceptions": ["NumPy multi-threaded Python loops"], "traps": ["Modifying view affects original"], "strongSignals": ["Axis parameter, dtype awareness"]},
    keyTakeaways=["ndarray homogeneous fast arrays", "Vectorization not loops", "Broadcasting aligns shapes", "Watch view vs copy", "Foundation for pandas/ML"],
    iq=[{"level": "basic", "q": "NumPy vs list?", "h": "Typed contiguous array; vectorized C ops."}, {"level": "intermediate", "q": "Broadcasting?", "h": "Align trailing dims; stretch size-1 axes."}, {"level": "advanced", "q": "View vs copy?", "h": "Slice often view; fancy index copies."}],
    flashcards=[{"f": "ndarray", "b": "Homogeneous N-D array core type"}, {"f": "Broadcasting", "b": "Align shapes for element-wise ops without copy"}],
    quickRevision=["np.array dtype", "Shape reshape", "Vectorize not loop", "Broadcast rules", "Mask indexing", "View vs copy"],
)

TOPICS["e1-pandas"] = T(
    whatIsIt="Pandas provides DataFrame/Series tabular data structures — labeled axes, missing data handling, groupby aggregations, joins, and IO for CSV/Parquet/SQL.",
    whyExists="Real data is messy tables with nulls and mixed operations. NumPy alone lacks row labels and SQL-like joins on heterogeneous columns.",
    mentalModel="Excel in Python: rows/columns with index; operations vectorized per column; groupby splits-apply-combine.",
    howItWorks=[{"type": "list", "items": [
        "DataFrame columns can differ dtypes",
        "loc vs iloc label vs integer indexing",
        "groupby().agg() split-apply-combine",
        "merge/join on keys like SQL",
        "handle NaN: isna, fillna, dropna",
    ]}],
    example=[{"type": "code", "lang": "python", "code": "import pandas as pd\ndf = pd.read_csv('sales.csv')\nmonthly = df.groupby('region')['revenue'].sum()", "caption": "Groupby aggregate"}],
    tradeoffs={"advantages": ["Expressive data wrangling", "Rich IO"], "disadvantages": ["Memory heavy", "Chained indexing pitfalls"], "alternatives": ["Polars faster", "SQL in warehouse"], "whenToUse": ["EDA", "Feature prep", "CSV pipelines"], "whenNotToUse": ["Big data beyond RAM — Spark"]},
    failureModes=["SettingWithCopyWarning silent bugs", "Mixed dtypes in column", "Loading entire CSV OOM"],
    production={"performance": ["Use categorical dtypes", "Chunk read_csv for large files", "Parquet not CSV at scale"]},
    interview={"expectations": ["DataFrame basics", "groupby merge"], "commonQuestions": ["groupby explain?"], "followUps": ["loc vs iloc?"], "misconceptions": ["Always faster than SQL"], "traps": ["Chained assignment"], "strongSignals": ["Avoid loops; vectorized ops"]},
    keyTakeaways=["DataFrame labeled tables", "groupby split-apply-combine", "loc label iloc position", "Watch SettingWithCopy", "Parquet/chunks at scale"],
    iq=[{"level": "basic", "q": "Series vs DataFrame?", "h": "Series 1D labeled; DataFrame 2D columns."}, {"level": "intermediate", "q": "groupby purpose?", "h": "Aggregate/transform per group key."}, {"level": "advanced", "q": "Avoid SettingWithCopy?", "h": "Use .loc assignment on explicit copy."}],
    flashcards=[{"f": "groupby", "b": "Split data by key; apply; combine results"}, {"f": "loc", "b": "Label-based row/col selection"}],
    quickRevision=["DataFrame/Series", "groupby agg", "merge join", "loc vs iloc", "NaN handling", "Parquet scale"],
)

# --- e2 ---
TOPICS["e2-fine-tuning"] = T(
    whatIsIt="Fine-tuning adapts a pretrained LLM to a domain or task by continued training on curated examples — full fine-tune, LoRA/QLoRA adapters, or instruction tuning on prompt-response pairs.",
    whyExists="Base models lack company tone, domain jargon, and task format. Fine-tuning improves accuracy cheaper than giant prompts or training from scratch.",
    mentalModel="Expert hires intern: base model knows language; fine-tune teaches company FAQ style and JSON output format on labeled examples.",
    howItWorks=[{"type": "list", "items": [
        "Curate high-quality prompt/completion dataset",
        "Choose method: full FT expensive; LoRA trains small adapter matrices",
        "Hyperparams: LR low, epochs few to avoid catastrophic forgetting",
        "Evaluate on held-out set + regression golden prompts",
        "Deploy adapter weights merged or sidecar",
    ]}],
    example=[{"type": "code", "lang": "python", "code": "# LoRA: train rank-decomposed delta weights\n# base frozen; inject adapters in attention layers\ntrainer.train(lora_config=LoRAConfig(r=16, alpha=32))", "caption": "LoRA concept"}],
    tradeoffs={"advantages": ["Better task accuracy", "Smaller inference prompts"], "disadvantages": ["Data curation cost", "Forgetting general skills"], "alternatives": ["RAG only", "Few-shot prompting"], "whenToUse": ["Stable format/tone", "Proprietary domain"], "whenNotToUse": ["Facts change daily — RAG better"]},
    failureModes=["Overfit tiny dataset", "Catastrophic forgetting", "Train/serve skew in formatting", "PII in training data leaked"],
    production={"cost": ["LoRA/QLoRA vs full GPU weeks"], "reliability": ["Golden eval before promote", "Version adapter weights"], "security": ["Scrub PII from training set"]},
    interview={"expectations": ["LoRA vs full FT", "When RAG vs fine-tune"], "commonQuestions": ["When fine-tune an LLM?"], "followUps": ["Catastrophic forgetting?"], "misconceptions": ["Fine-tune replaces RAG for facts"], "traps": ["100 examples overfit"], "strongSignals": ["Data quality, eval harness, LoRA"]},
    keyTakeaways=["Adapt pretrained model with domain data", "LoRA cheap adapter tuning", "Avoid overfit + forgetting", "Eval golden set before deploy", "RAG for facts; FT for behavior"],
    iq=[{"level": "basic", "q": "Fine-tune vs prompt?", "h": "FT bakes behavior in weights; prompt ephemeral."}, {"level": "intermediate", "q": "LoRA benefit?", "h": "Train small adapters; freeze base; less GPU."}, {"level": "advanced", "q": "FT vs RAG for docs?", "h": "RAG for changing facts; FT for style/format."}],
    flashcards=[{"f": "LoRA", "b": "Low-rank adapter matrices on frozen base"}, {"f": "Catastrophic forgetting", "b": "Model loses general skills after narrow FT"}],
    quickRevision=["Pretrained + domain data", "LoRA/QLoRA efficient", "Small LR few epochs", "Golden eval gate", "RAG vs FT split", "Scrub PII"],
)

TOPICS["e2-gpu-inference"] = T(
    whatIsIt="GPU inference runs model forward passes on accelerators — batching, KV-cache for autoregressive decode, tensor parallelism, and memory bandwidth dominate latency/throughput.",
    whyExists="LLM matrix ops parallelize on GPU; CPU too slow at scale. Production serving needs GPU scheduling, batching, and memory management.",
    mentalModel="Factory assembly line: prefill processes prompt in parallel; decode generates tokens sequentially reusing KV-cache; batch fills GPU lanes.",
    howItWorks=[{"type": "list", "items": [
        "Prefill: parallel attention over prompt tokens",
        "Decode: autoregressive one token at a time; KV-cache avoids recomputing past",
        "Continuous batching merges requests dynamically",
        "Tensor parallelism splits layers across GPUs",
        "Quantization (INT8/FP8) reduces memory bandwidth need",
    ]}],
    example=[{"type": "code", "lang": "text", "code": "TTFT = time to first token (prefill bound)\nTPOT = time per output token (decode bound)\nBatching improves GPU utilization vs batch=1", "caption": "Latency metrics"}],
    tradeoffs={"advantages": ["High throughput matmul", "Batch amortizes cost"], "disadvantages": ["VRAM limits model size", "Batching adds queue latency"], "alternatives": ["CPU inference small models", "Specialized ASIC"], "whenToUse": ["Production LLM serving"], "whenNotToUse": ["Tiny models on edge CPU OK"]},
    failureModes=["OOM from long context KV-cache", "Head-of-line blocking in static batch", "Cold GPU underutilization batch=1"],
    production={"performance": ["Continuous batching; paged KV-cache", "Right-size GPU for model+context"], "cost": ["Spot instances; scale to zero off-peak"], "observability": ["TTFT, TPOT, GPU util metrics"]},
    interview={"expectations": ["Prefill vs decode", "KV-cache purpose"], "commonQuestions": ["Why GPU for LLM?"], "followUps": ["Continuous batching?"], "misconceptions": ["All tokens equally parallel in decode"], "traps": ["Ignore KV-cache memory growth"], "strongSignals": ["TTFT/TPOT, batching, tensor parallel"]},
    keyTakeaways=["Prefill parallel; decode sequential", "KV-cache saves recompute", "Batching boosts throughput", "VRAM limits context batch", "Quantization helps bandwidth"],
    iq=[{"level": "basic", "q": "Why GPU for inference?", "h": "Parallel matrix ops; high memory bandwidth."}, {"level": "intermediate", "q": "KV-cache?", "h": "Stores past K/V tensors; avoid re-attending prior tokens."}, {"level": "advanced", "q": "Continuous batching?", "h": "Add/remove requests mid-flight in decode loop."}],
    flashcards=[{"f": "TTFT", "b": "Time to first token — prefill latency"}, {"f": "KV-cache", "b": "Cached keys/values for prior tokens in decode"}],
    quickRevision=["Prefill vs decode", "KV-cache memory", "Batch for util", "Tensor parallel big models", "Quantize bandwidth", "TTFT/TPOT metrics"],
)

TOPICS["e2-quantization"] = T(
    whatIsIt="Quantization reduces weight/activation precision (FP16→INT8/INT4) lowering memory and bandwidth with minimal accuracy loss — PTQ post-training or QAT aware training.",
    whyExists="Full FP16 models exceed GPU RAM and bandwidth. Quantization enables larger models, faster inference, and edge deployment.",
    mentalModel="Compress photo quality: fewer bits per number; calibrate scale/zero-point so INT8 approximates FP32 range.",
    howItWorks=[{"type": "list", "items": [
        "Post-training quant: calibrate on sample data for scales",
        "INT8/INT4 weights; sometimes activations quantized",
        "GPTQ/AWQ methods for LLM weight-only quant",
        "QAT trains with fake quant nodes",
        "Dequant in matmul: int * scale → fp accumulate",
    ]}],
    example=[{"type": "code", "lang": "python", "code": "# Concept: weight_int8 = round(weight_fp32 / scale)\n# matmul uses int8 with output rescale", "caption": "Scale quantize"}],
    tradeoffs={"advantages": ["2-4x memory savings", "Faster inference"], "disadvantages": ["Accuracy drop on hard tasks", "Hardware/kernel support needed"], "alternatives": ["Smaller model distillation", "FP16 only"], "whenToUse": ["Cost-sensitive serving", "Edge devices"], "whenNotToUse": ["Max accuracy research baseline"]},
    failureModes=["Bad calibration set → high perplexity", "Outlier channels break INT8", "Mixed precision bugs in custom ops"],
    production={"performance": ["Benchmark perplexity + task eval after quant"], "cost": ["INT4 fits model on single GPU"], "reliability": ["A/B quant vs FP16 in shadow"]},
    interview={"expectations": ["Why quantize", "PTQ vs QAT"], "commonQuestions": ["Quantization tradeoffs?"], "followUps": ["GPTQ/AWQ for LLMs?"], "misconceptions": ["Always free speedup on CPU"], "traps": ["No eval after quant"], "strongSignals": ["Calibration, scale/zero-point, weight-only"]},
    keyTakeaways=["Lower bit width saves RAM/bandwidth", "Calibrate scales on sample data", "LLM weight-only GPTQ/AWQ common", "Always eval after quant", "QAT when PTQ insufficient"],
    iq=[{"level": "basic", "q": "Why quantize?", "h": "Smaller faster models; fit in VRAM."}, {"level": "intermediate", "q": "PTQ vs QAT?", "h": "PTQ after train; QAT simulates quant during train."}, {"level": "advanced", "q": "Weight-only quant?", "h": "Keep activations FP16; compress weights INT4."}],
    flashcards=[{"f": "PTQ", "b": "Post-training quantization via calibration"}, {"f": "Scale factor", "b": "Maps float range to int representation"}],
    quickRevision=["INT8/INT4 weights", "Calibrate scales", "GPTQ/AWQ LLM", "Eval after quant", "QAT if PTQ fails", "Bandwidth savings"],
)

# --- e4 ---
TOPICS["e4-prompt-versioning"] = T(
    whatIsIt="Prompt versioning tracks system/user prompt templates like code — semantic versions, git storage, diff review, rollback, and linking prompt hash to eval scores and production traffic.",
    whyExists="Prompt tweaks silently change behavior. Without versioning, regressions untraceable and A/B tests unreproducible.",
    mentalModel="Git for prompts: v1.2.0 system prompt tagged; deploy pins version; eval suite runs on each bump before promote.",
    howItWorks=[{"type": "list", "items": [
        "Store templates in repo or registry with semver",
        "Parameterize variables {{user_name}} not string concat in code",
        "CI runs offline eval on prompt change PR",
        "Production logs prompt_version with each request",
        "Canary new version; rollback via config flag",
    ]}],
    example=[{"type": "code", "lang": "yaml", "code": "prompt_id: support-agent\nversion: 2.3.1\nsystem: |\n  You are a helpful support bot.\n  Use only provided context.\nvariables: [context, user_name]", "caption": "Versioned template"}],
    tradeoffs={"advantages": ["Reproducible behavior", "Safe rollback"], "disadvantages": ["Overhead for tiny projects"], "alternatives": ["Hardcoded strings", "Feature flags only"], "whenToUse": ["Production LLM apps"], "whenNotToUse": ["One-off experiments"]},
    failureModes=["Untracked hotfix in prod config", "Variable schema break on upgrade", "Eval not run on merge"],
    production={"maintainability": ["Prompt registry + code review", "Link version to Langfuse/LangSmith traces"], "reliability": ["Automated regression eval gate"]},
    interview={"expectations": ["Semver prompts", "Eval gate on change"], "commonQuestions": ["How version prompts?"], "followUps": ["Rollback strategy?"], "misconceptions": ["Prompts too volatile to version"], "traps": ["Edit prod prompt without tag"], "strongSignals": ["Git, semver, eval CI, request logging"]},
    keyTakeaways=["Version prompts like code", "Semver + git review", "Eval CI on prompt PR", "Log version per request", "Canary and rollback"],
    iq=[{"level": "basic", "q": "Why prompt versioning?", "h": "Trace behavior changes; rollback regressions."}, {"level": "intermediate", "q": "Deploy new prompt safely?", "h": "Offline eval → canary → full rollout."}, {"level": "advanced", "q": "Link eval to version?", "h": "Hash prompt; store scores keyed by version id."}],
    flashcards=[{"f": "Prompt registry", "b": "Central store of versioned templates"}, {"f": "Canary prompt", "b": "Route small traffic to new version first"}],
    quickRevision=["Semver templates", "Git + PR review", "Eval CI gate", "Log prompt_version", "Parameterized vars", "Canary rollback"],
)

# --- e5 ---
TOPICS["e5-ann"] = T(
    whatIsIt="Approximate Nearest Neighbour (ANN) search finds vectors close to a query in high dimensions without exact O(n) scan — HNSW, IVF, LSH trade recall for speed.",
    whyExists="Exact brute-force cosine on millions of embeddings too slow for interactive RAG. ANN indexes sub-linear query time with tunable recall.",
    mentalModel="Skip most of haystack: build graph/clusters offline; query navigates to nearby region; may miss true nearest neighbor occasionally.",
    howItWorks=[{"type": "list", "items": [
        "HNSW: hierarchical navigable small world graph layers",
        "IVF: inverted file clusters; search top probes clusters",
        "LSH: hash similar vectors to same buckets",
        "Tunable ef_search/nprobe balances recall vs latency",
        "Combine with reranker on top-k for accuracy",
    ]}],
    example=[{"type": "code", "lang": "python", "code": "# FAISS HNSW example concept\n# index.hnsw.efSearch = 64  # higher → better recall, slower", "caption": "Recall knob"}],
    tradeoffs={"advantages": ["Millisecond queries on millions"], "disadvantages": ["Imperfect recall", "Index build cost"], "alternatives": ["Exact flat index small n", "Hybrid BM25 + vector"], "whenToUse": ["RAG retrieval scale"], "whenNotToUse": ["Tiny corpus exact OK"]},
    failureModes=["Low recall misses relevant doc", "Stale index after doc updates", "Wrong distance metric for embedding model"],
    production={"performance": ["Tune ef_search on golden queries", "Rebuild index on bulk update"], "observability": ["Recall@k on eval set; query latency p99"]},
    interview={"expectations": ["ANN vs exact", "HNSW intuition"], "commonQuestions": ["How ANN works?"], "followUps": ["Improve recall?"], "misconceptions": ["Always returns true nearest"], "traps": ["No recall eval"], "strongSignals": ["ef_search, rerank top-k, hybrid search"]},
    keyTakeaways=["ANN trades recall for speed", "HNSW/IVF common algorithms", "Tune search params on eval", "Rerank top results", "Rebuild on corpus change"],
    iq=[{"level": "basic", "q": "ANN vs exact search?", "h": "ANN approximate fast; exact O(n) scan accurate."}, {"level": "intermediate", "q": "HNSW idea?", "h": "Multi-layer graph greedy navigate to neighbors."}, {"level": "advanced", "q": "Missed relevant doc?", "h": "Increase ef_search; hybrid BM25; reranker."}],
    flashcards=[{"f": "HNSW", "b": "Graph-based ANN with layered greedy search"}, {"f": "Recall@k", "b": "Fraction of true neighbors in top-k results"}],
    quickRevision=["Approx not exact", "HNSW IVF LSH", "Tune ef_search", "Eval recall@k", "Rerank top-k", "Hybrid BM25"],
)

TOPICS["e5-vector-indexes"] = T(
    whatIsIt="Vector indexes store embedding vectors with metadata enabling filtered similarity search — Pinecone, pgvector, FAISS, Weaviate, Milvus with HNSW/IVF backends and namespace/shard layout.",
    whyExists="Raw embedding files lack query API, persistence, filtering, and horizontal scale. Managed indexes provide production retrieval infrastructure.",
    mentalModel="Specialized DB for vectors: upsert id+vector+metadata; query vector returns top-k similar with optional metadata filter.",
    howItWorks=[{"type": "list", "items": [
        "Upsert: id, embedding float[], metadata JSON",
        "Index type: HNSW flat IVF per vendor",
        "Metadata pre-filter narrows search space",
        "Namespaces/collections isolate tenants",
        "Hybrid: sparse BM25 + dense vector fusion",
    ]}],
    example=[{"type": "code", "lang": "python", "code": "index.upsert([('doc1', embedding, {'team': 'eng'})])\nresults = index.query(vector=q_emb, top_k=5, filter={'team': 'eng'})", "caption": "Upsert and filtered query"}],
    tradeoffs={"advantages": ["Managed scale", "Metadata filters"], "disadvantages": ["Vendor cost", "Eventual consistency on upsert"], "alternatives": ["Self-host FAISS", "Postgres pgvector small scale"], "whenToUse": ["Production RAG"], "whenNotToUse": ["<10k vectors in Postgres OK"]},
    failureModes=["Dimension mismatch on upsert", "Filter too selective empty results", "Index lag after upsert", "Single shard hot tenant"],
    production={"scalability": ["Shard by tenant; replicate read"], "observability": ["Query latency, index size, upsert lag"], "cost": ["Right-size dimensions; prune stale vectors"]},
    interview={"expectations": ["Upsert/query API", "Metadata filter + ANN"], "commonQuestions": ["Vector DB vs relational?"], "followUps": ["Hybrid search?"], "misconceptions": ["Store full text in vector DB only"], "traps": ["No metadata for filtering"], "strongSignals": ["pgvector vs managed, HNSW, hybrid"]},
    keyTakeaways=["Store vectors + metadata + id", "ANN backend HNSW/IVF", "Pre-filter metadata", "Hybrid sparse+dense", "Match embedding dimensions"],
    iq=[{"level": "basic", "q": "Vector index query?", "h": "Similarity search top-k near query embedding."}, {"level": "intermediate", "q": "Metadata filter why?", "h": "Restrict search to tenant/doc type before ANN."}, {"level": "advanced", "q": "pgvector vs Pinecone?", "h": "pgvector simpler ops small scale; managed scales ANN ops."}],
    flashcards=[{"f": "Upsert", "b": "Insert or update vector by id"}, {"f": "Metadata filter", "b": "Pre-filter candidates before similarity search"}],
    quickRevision=["id + vector + metadata", "HNSW ANN backend", "Filtered query", "Hybrid BM25+vector", "Dimension match", "Shard tenants"],
)

# --- e7 agent topics ---
E7 = [
    ("e7-agent-loops", "Agent Loops",
     "Agent loop repeatedly calls LLM → optionally executes tools → appends results → until stop condition (final answer, max iterations, tool budget).",
     "Single-shot LLM cannot multi-step reason with tools. Loop orchestrates plan-act-observe cycles.",
     "while not done: model thinks → tool call → observe result → repeat.",
     ["Set max_iterations hard cap", "Parse tool_calls from assistant message", "Execute tools server-side; append tool role messages", "Stop on final natural language or no tool_calls", "Log each turn for debug"],
     "typescript", "for (let i = 0; i < MAX; i++) {\n  const msg = await llm(messages, tools);\n  if (!msg.tool_calls) return msg.content;\n  messages.push(...runTools(msg.tool_calls));\n}",
     ["Multi-step tasks", "Composable with any tools"], ["Runaway loops", "Latency multiplies per turn"], ["Single prompt chain", "Workflow engines"],
     ["Research agents", "Support bots with APIs"], ["Simple FAQ one-shot"],
     ["Infinite loop without cap", "Tool error not surfaced to model", "Context overflow long loops"],
     {"reliability": ["MAX_ITERATIONS=5-10", "Timeout per iteration"], "observability": ["Trace each loop step with span"]},
     ["Iteration cap mandatory", "Tool result fed back"],
     ["Cap iterations", "Server executes tools", "Append tool messages", "Stop conditions clear", "Trace each step"],
     [{"level": "basic", "q": "Agent loop steps?", "h": "LLM → tool calls → results → LLM until done."}, {"level": "intermediate", "q": "Prevent runaway?", "h": "Max iterations, budget, timeout."}, {"level": "advanced", "q": "Context grows each turn?", "h": "Summarize, trim tool outputs, sliding window."}],
     [{"f": "Max iterations", "b": "Hard cap preventing infinite tool loops"}, {"f": "Tool message", "b": "Role tool carrying function result to model"}],
     ["LLM → tools → repeat", "Cap iterations", "Server-side execution", "Tool role messages", "Stop on no tools", "Trace spans"]),
    ("e7-error-recovery", "Error Recovery",
     "Error recovery in agents handles tool failures, invalid JSON args, timeouts — retry with backoff, alternate tools, graceful degradation, user-visible error messages.",
     "Tools fail in production. Agents must not crash loop or hallucinate success when API 500.",
     "Try tool → on failure append error to context → model retries or explains to user.",
     ["Classify transient vs permanent errors", "Retry idempotent tools with exponential backoff", "Feed structured error string in tool message", "Circuit breaker after repeated failures", "Fallback tool or human handoff"],
     "typescript", "try { result = await tool(args); } catch (e) {\n  messages.push({ role: 'tool', content: JSON.stringify({ error: e.message }) });\n}",
     ["Resilient agents", "Model can self-correct args"], ["Extra tokens on errors", "Retry storms if not capped"],
     ["Fail fast no retry", "Preflight validate args"],
     ["Production agents with external APIs"], ["Demo prototypes"],
     ["Retry non-idempotent writes twice", "Hide error from model → hallucination", "Infinite retry loop"],
     {"reliability": ["Idempotency keys on mutating tools", "Circuit breaker per dependency"]},
     ["Structured tool errors to model", "Retry transient only"],
     ["Feed errors to model", "Retry transient idempotent", "Circuit breaker", "Validate args preflight", "User-visible fallback"],
     [{"level": "basic", "q": "Tool 500 in agent?", "h": "Return error in tool message; model decides retry/explain."}, {"level": "intermediate", "q": "Retry policy?", "h": "Backoff on transient; no retry on 400 validation."}, {"level": "advanced", "q": "Circuit breaker?", "h": "Stop calling failing dependency; fallback path."}],
     [{"f": "Tool error message", "b": "Structured failure returned to LLM context"}, {"f": "Circuit breaker", "b": "Halt calls after repeated dependency failures"}],
     ["Errors in tool messages", "Retry transient", "No double mutate", "Circuit breaker", "Preflight validate", "User fallback"]),
    ("e7-human-in-loop", "Human-in-the-Loop",
     "Human-in-the-loop (HITL) pauses agent for human approval, correction, or labeling on high-stakes actions — payments, deletes, policy edge cases.",
     "Fully autonomous agents risk costly mistakes. HITL adds governance and training signal.",
     "Agent proposes action → queue for human → approved/rejected/edited → resume or abort.",
     ["Define approval gates on tool class or risk score", "UI queue with context snippet", "Timeout and default deny", "Log decisions for audit and fine-tune", "Async resume via webhook/event"],
     "text", "Agent: propose refund $500\n→ Human inbox: Approve | Edit | Reject\n→ On approve: execute refund tool",
     ["Safety on high impact", "Quality labels for FT"], ["Latency and staffing cost", "Queue backlog"],
     ["Full auto", "Rule-based only no LLM"],
     ["Finance ops", "Moderation", "Medical suggestions"],
     ["Low risk read-only tasks"],
     ["Approval fatigue → rubber stamp", "Stale context when human responds late", "Bypass gate in code path"],
     {"security": ["Audit log who approved what", "Default deny on timeout"], "reliability": ["Idempotent resume tokens"]},
     ["When require human approval", "Audit trail"],
     ["Gates on risky tools", "Approval queue UI", "Default deny timeout", "Audit log", "Resume token"],
     [{"level": "basic", "q": "Why HITL?", "h": "Prevent high-stakes autonomous errors."}, {"level": "intermediate", "q": "What to gate?", "h": "Mutating tools, high $, policy sensitive."}, {"level": "advanced", "q": "Scale HITL?", "h": "Risk routing; auto-approve low risk; prioritize queue."}],
     [{"f": "HITL", "b": "Human approval before agent action proceeds"}, {"f": "Default deny", "b": "Timeout without approval aborts action"}],
     ["Risk-based gates", "Approval queue", "Audit trail", "Default deny", "Resume workflow", "Train from edits"]),
    ("e7-memory", "Memory Concepts",
     "Agent memory spans short-term conversation context, long-term user facts in vector/store, and episodic summaries — retrieval augments prompt beyond fixed window.",
     "Context windows finite. Agents need remember preferences and past sessions across turns and days.",
     "Notebook: recent messages in RAM; important facts filed in drawer; retrieve relevant notes each turn.",
     ["Short-term: sliding window + summarization", "Long-term: embed facts user_id keyed store", "Retrieve top-k memories per query", "Write memory tool after explicit consent", "TTL and delete for GDPR"],
     "python", "# Retrieve\nmemories = store.search(user_id, query_emb, k=5)\n# Inject into system prompt block",
     ["Personalization", "Cross-session continuity"], ["Stale wrong memories", "Privacy sensitivity"],
     ["Stateless each request", "Full transcript forever"],
     ["Assistants", "Support with history"], ["Anonymous one-shot"],
     ["Memory injection prompt injection vector", "Never expiring PII memories", "Retrieve irrelevant memories noise"],
     {"security": ["User consent for long-term memory", "Delete API"], "performance": ["Cap memories injected per turn"]},
     ["Short vs long-term", "Retrieval each turn"],
     ["Window + summarize short-term", "Vector store long-term", "Retrieve per query", "Consent + delete", "Avoid memory poisoning"],
     [{"level": "basic", "q": "Short vs long memory?", "h": "Short: current chat; long: persisted facts across sessions."}, {"level": "intermediate", "q": "When write memory?", "h": "Explicit facts user asked to remember; not every message."}, {"level": "advanced", "q": "Memory poisoning?", "h": "Validate writes; separate user vs system memory."}],
     [{"f": "Episodic summary", "b": "Compressed past conversation stored for retrieval"}, {"f": "Memory retrieval", "b": "Top-k relevant facts injected each turn"}],
     ["Short window + summary", "Long-term vector store", "Retrieve each turn", "Consent GDPR", "TTL delete", "Poisoning risk"]),
    ("e7-planning", "Planning",
     "Planning decomposes user goal into steps before execution — plan-and-execute, ReAct reasoning, or explicit todo list the agent updates as subtasks complete.",
     "Complex tasks fail without structure. Planning reduces wrong tool order and missed dependencies.",
     "Architect blueprint before construction: LLM outputs numbered plan → execute step 1 tool → revise plan if blocked.",
     ["Prompt for explicit plan JSON or markdown checklist", "Execute one step per loop iteration", "Replan on tool failure or new info", "Optional human approve plan upfront", "Keep plan in context for grounding"],
     "markdown", "Plan:\n1. Search KB for refund policy\n2. Call billing API get_invoice\n3. Draft response with citations",
     ["Better multi-step success", "Debuggable intermediate state"], ["Planning overhead tokens/latency", "Rigid plan misses dynamic info"],
     ["Pure reactive ReAct only", "Hardcoded workflow graph"],
     ["Open-ended multi-tool tasks"], ["Single lookup"],
     ["Plan never updated after failure", "Steps too vague to execute", "Plan stored but ignored in loop"],
     {"observability": ["Log plan revisions", "Compare planned vs executed steps"]},
     ["Plan-and-execute pattern", "Replan on failure"],
     ["Decompose before act", "Explicit checklist in context", "Replan dynamically", "One step per iteration", "Human approve risky plans"],
     [{"level": "basic", "q": "Why plan first?", "h": "Structure multi-step tasks; reduce wrong tool order."}, {"level": "intermediate", "q": "ReAct vs plan-execute?", "h": "ReAct interleaves thought/action; plan-execute batch plan then run."}, {"level": "advanced", "q": "When replan?", "h": "Tool error, missing data, user correction mid-task."}],
     [{"f": "Plan-and-execute", "b": "Generate plan then execute steps sequentially"}, {"f": "Replan", "b": "Revise remaining steps after new information"}],
     ["Decompose goal", "Plan in context", "Step-wise execute", "Replan on failure", "ReAct alternative", "Log plan vs done"]),
    ("e7-sandboxing", "Sandboxing/Security",
     "Agent sandboxing isolates code execution and tool effects — containers, WASM, seccomp, network egress deny, read-only FS, resource limits for untrusted model output.",
     "Models suggest dangerous commands. Sandboxing limits blast radius of code/run tools.",
     "Playpen: agent child process cannot touch host network or secrets; timeout kills runaway.",
     ["Run code in ephemeral Docker/Firecracker", "No env secrets in sandbox", "Network allowlist only needed APIs", "CPU/memory/time quotas", "Separate prod credentials from agent runtime"],
     "bash", "docker run --rm --network none --memory 512m sandbox:latest python user_code.py",
     ["Contain RCE from code tools", "Audit isolated environment"], ["Ops complexity", "Cold start latency"],
     ["Trust model output on host", "Static analysis only"],
     ["Code interpreter tools", "Shell command agents"],
     ["Trusted internal read-only APIs only"],
     ["Secrets mounted in sandbox", "Shared Docker socket escape", "No timeout → mining"],
     {"security": ["Default deny network", "Rotate sandboxes per request"], "reliability": ["Kill after TTL"]},
     ["Never run model shell on host", "Container isolation"],
     ["Isolate code exec", "No secrets in sandbox", "Network deny default", "Resource limits", "Ephemeral environments", "Audit runs"],
     [{"level": "basic", "q": "Why sandbox agent code?", "h": "Model output untrusted; limit RCE blast radius."}, {"level": "intermediate", "q": "Sandbox essentials?", "h": "No network/secrets; CPU/mem/time limits."}, {"level": "advanced", "q": "Docker enough?", "h": "Harden: non-root, read-only FS, gVisor/Firecracker for multi-tenant."}],
     [{"f": "Ephemeral sandbox", "b": "Fresh isolated env per code execution"}, {"f": "Egress deny", "b": "Block network by default in sandbox"}],
     ["Container/WASM isolate", "No host secrets", "Network allowlist", "CPU/mem timeout", "Non-root user", "Per-request fresh"]),
    ("e7-state", "State",
     "Agent state tracks conversation messages, plan progress, tool results, and session variables across loop iterations — persisted in DB/Redis for multi-request sessions.",
     "HTTP stateless; agents need durable thread state for resume, HITL pause, and audit.",
     "Scratchpad dict: messages[], plan_step, user_id — load at start, save after each turn.",
     ["Message array is core state for LLM API", "Persist session_id → state blob", "Version state for optimistic concurrency", "Trim/summarize old turns in state", "Separate ephemeral vs durable fields"],
     "typescript", "interface SessionState {\n  messages: Message[];\n  plan?: string[];\n  step: number;\n}",
     ["Resume sessions", "Debug replay"], ["State bloat OOM context", "Concurrency conflicts"],
     ["Stateless single shot"], ["Multi-turn assistants"],
     ["One-shot queries"],
     ["Lost state on crash mid-loop", "Race on parallel requests same session", "Storing secrets in client state"],
     {"reliability": ["Persist after each tool execution", "Session locking"], "security": ["Server-side state only"]},
     ["What persists across turns", "Session storage"],
     ["Messages core state", "Persist session server-side", "Trim old turns", "Lock concurrent updates", "No secrets client-side"],
     [{"level": "basic", "q": "Agent state contains?", "h": "Messages, plan progress, session metadata."}, {"level": "intermediate", "q": "Where persist?", "h": "Redis/DB keyed by session_id."}, {"level": "advanced", "q": "Parallel same session?", "h": "Optimistic lock or queue requests per session."}],
     [{"f": "Session state", "b": "Durable agent context across requests"}, {"f": "State trim", "b": "Summarize/remove old messages to fit window"}],
     ["messages[] core", "Server persist", "session_id key", "Trim/summarize", "Concurrency lock", "Replay debug"]),
    ("e7-tool-calling", "Tool Calling",
     "Tool calling lets LLM emit structured function requests with JSON args validated against schemas; app executes server-side and returns tool role messages.",
     "LLMs cannot access live systems alone. Tools bridge reasoning to APIs and databases safely.",
     "Model requests intern to run function — app runs it — returns result — model answers.",
     ["Register tools with name, description, parameters schema", "Model returns tool_calls in response", "Validate args; execute handler", "Append tool message with result", "Loop until final answer"],
     "typescript", "if (msg.tool_calls) {\n  for (const tc of msg.tool_calls) {\n    const result = await handlers[tc.name](parse(tc.arguments));\n    messages.push({ role: 'tool', tool_call_id: tc.id, content: JSON.stringify(result) });\n  }\n}",
     ["Live data and actions", "Structured args"], ["Security if over-permissioned", "Multi-turn latency"],
     ["ReAct string parsing", "RAG only"],
     ["Agents with APIs"], ["Static knowledge only"],
     ["Executing untrusted args", "Missing description → wrong tool", "Infinite tool loop"],
     {"security": ["Allowlist tools", "Validate schema"], "reliability": ["Max iterations cap"]},
     ["Tool loop flow", "Server executes"],
     ["Model proposes tool_calls", "Server executes", "Tool role results", "Schema validate", "Cap iterations"],
     [{"level": "basic", "q": "Tool calling loop?", "h": "Model requests → app runs → result → model answers."}, {"level": "intermediate", "q": "Security essentials?", "h": "Allowlist, validate args, least privilege."}, {"level": "advanced", "q": "Tools vs RAG?", "h": "RAG static chunks; tools live systems and mutations."}],
     [{"f": "tool_calls", "b": "Model output requesting function invocation"}, {"f": "Tool schema", "b": "JSON schema describing parameters"}],
     ["Register tools + schema", "Model tool_calls", "Server execute", "Tool message back", "Validate args", "Cap loops"]),
    ("e7-tool-permissions", "Tool Permissions",
     "Tool permissions enforce least privilege — role-based tool allowlists, scoped credentials, read-only vs mutating tools, per-user authZ before handler runs.",
     "One compromised prompt should not exfiltrate all data. Permissions map user/agent role to permitted tools and data scope.",
     "Key ring: agent holds only keys for allowed doors; each tool checks ACL before execute.",
     ["Tool registry tagged read/mutate/admin", "Map user role → allowed tool subset per session", "Inject user OAuth token into tool context not global admin", "Deny by default unknown tools", "Audit every tool invocation with principal"],
     "typescript", "function canUseTool(user: User, tool: string) {\n  return USER_TOOLS[user.role].includes(tool);\n}",
     ["Blast radius containment", "Compliance audit trail"], ["Complex policy matrix", "Token pass-through bugs"],
     ["Single admin tool suite", "Prompt-only guardrails"],
     ["Multi-tenant agents", "Enterprise copilots"],
     ["Demo with full admin API"],
     ["Prompt jailbreak grants shell", "Shared service account across users", "Tool omits authZ check"],
     {"security": ["RBAC on tools", "Per-user scoped tokens"], "observability": ["Alert on denied tool attempts"]},
     ["Least privilege tools", "RBAC before execute"],
     ["Allowlist per role/user", "Separate read vs mutate", "Scoped credentials", "Deny default", "Audit invocations"],
     [{"level": "basic", "q": "Why tool permissions?", "h": "Limit damage from bad prompts or users."}, {"level": "intermediate", "q": "Implement how?", "h": "RBAC map; check before handler; scoped OAuth."}, {"level": "advanced", "q": "Multi-tenant isolation?", "h": "Tenant id in every tool query; no cross-tenant tokens."}],
     [{"f": "Least privilege", "b": "Agent gets minimum tools needed for task"}, {"f": "Scoped token", "b": "User OAuth passed to tool not global admin key"}],
     ["RBAC tool allowlist", "Read vs mutate tags", "Scoped creds", "Deny default", "Audit log", "No shared admin"]),
    ("e7-workflows", "Multi-Step Workflows",
     "Multi-step workflows orchestrate fixed or dynamic DAG of LLM/tool/human steps — LangGraph, Temporal, state machines with checkpoints vs free-form agent loop.",
     "Ad hoc loops hard to audit and recover. Workflows encode business process with retries, branching, persistence.",
     "Flowchart with checkpoints: each node LLM or tool; edges on success/failure; resume from last checkpoint.",
     ["Define nodes: prompt, tool, human, branch", "Persist checkpoint after each node", "Retry policies per node type", "Dynamic agents as single node in larger DAG", "Visual editor for ops team"],
     "text", " ingest → classify → [billing|support] branch → tool → human_review? → respond",
     ["Auditable processes", "Resume after failure"], ["Rigid vs adaptive tradeoff", "Workflow engine ops"],
     ["Free agent loop only", "Hardcoded if/else scripts"],
     ["Regulated pipelines", "Order processing bots"],
     ["Exploratory research chat"],
     ["No checkpoint → restart from scratch", "Dynamic loop bypasses workflow guards", "Circular graph deadlocks"],
     {"reliability": ["Idempotent nodes", "Checkpoint store"], "observability": ["Visual run trace per workflow id"]},
     ["Workflow vs agent loop", "Checkpoint resume"],
     ["DAG of steps", "Checkpoints persist", "Branch on outcome", "Retry per node", "Combine with agents", "Audit visual trace"],
     [{"level": "basic", "q": "Workflow vs agent loop?", "h": "Workflow predefined graph; loop free-form LLM driven."}, {"level": "intermediate", "q": "Checkpoint why?", "h": "Resume after crash/HITL without redo all steps."}, {"level": "advanced", "q": "Embed agent in workflow?", "h": "Agent node with bounded tools inside DAG step."}],
     [{"f": "Checkpoint", "b": "Persisted state after workflow node completes"}, {"f": "DAG workflow", "b": "Directed graph of orchestrated steps"}],
     ["Nodes + edges", "Checkpoints", "Branch retry", "Agent as node", "Temporal/LangGraph", "Ops visibility"]),
]

for row in E7:
    tid, title, what, why, model, items, ex_lang, ex_code, adv, dis, alt, use, nouse, fails, prod, exp, kts, iqs, fcs, qr = row
    TOPICS[tid] = T(
        whatIsIt=what, whyExists=why, mentalModel=model,
        howItWorks=[{"type": "list", "items": items}],
        example=[{"type": "code", "lang": ex_lang, "code": ex_code}],
        tradeoffs={"advantages": adv, "disadvantages": dis, "alternatives": alt, "whenToUse": use, "whenNotToUse": nouse},
        failureModes=fails,
        production=prod,
        interview={"expectations": exp, "commonQuestions": [f"Explain {title}"], "followUps": ["Production concerns?"], "misconceptions": ["Works in demo equals prod ready"], "traps": ["Missing security cap"], "strongSignals": kts[:3]},
        keyTakeaways=kts, iq=iqs, flashcards=fcs, quickRevision=qr,
    )

# --- e9 eval topics ---
E9 = [
    ("e9-correctness", "Answer Correctness",
     "Answer correctness measures whether LLM output is factually and logically right vs reference — exact match, LLM-as-judge, human rubric, task-specific validators.",
     "Accuracy is core product metric. Need automated checks beyond vibes for regressions on prompt/model changes.",
     "Grade exam: compare answer to gold key or rubric criteria; partial credit via semantic similarity.",
     ["Define gold answer or rubric per test case", "Automated: EM, BLEU, ROUGE, semantic embedding sim", "LLM judge with structured score + rationale", "Human spot-check sample", "Track correctness by category"],
     "json", '{"query":"2+2?","gold":"4","model":"4","correct":true}',
     ["Objective regression signal", "Category breakdown"], ["LLM judge bias", "Gold answer maintenance"],
     ["Manual review only", "User thumbs only"],
     ["QA bots", "Math/code tasks with verifier"],
     ["Subjective creative writing"],
     ["Exact match on paraphrase false negative", "Judge prefers verbose wrong answer", "Stale gold after product change"],
     {"reliability": ["Version gold with prompt", "Calibrate judge vs human"]},
     ["Metrics for correctness", "Gold dataset link"],
     ["Gold or rubric per case", "Automate where possible", "LLM judge cautiously", "Category metrics", "Version with prompt"],
     [{"level": "basic", "q": "Measure answer correctness?", "h": "Compare to reference or rubric; task validators."}, {"level": "intermediate", "q": "LLM-as-judge risks?", "h": "Bias, position bias; calibrate vs humans."}, {"level": "advanced", "q": "Partial credit?", "h": "Semantic sim, rubric scores, structured JSON field match."}],
     [{"f": "Gold answer", "b": "Reference correct output for eval case"}, {"f": "LLM judge", "b": "Model scores another model output vs criteria"}],
     ["Gold/rubric", "EM vs semantic", "LLM judge calibrate", "By category", "Version gold", "Validators code/math"]),
    ("e9-golden-datasets", "Golden Datasets",
     "Golden datasets are curated fixed eval sets with input, expected output, metadata — regression suite run on every prompt/model/deploy change.",
     "Ad hoc eval not reproducible. Golden set is ground truth benchmark versioned with product.",
     "Unit test fixtures for LLM: 200 representative queries with expected behavior locked.",
     ["Curate from prod logs stratified by intent", "Annotate expected answer or rubric", "Store in git with semver", "CI runs full golden on PR", "Block deploy on regression threshold"],
     "json", '[{"id":"refund-1","input":"How refund?","expect_contains":["30 days"],"tags":["policy"]}]',
     ["Reproducible benchmarks", "CI gate"], ["Maintenance cost", "Overfit to golden set"],
     ["Live prod-only eval", "Random manual spot checks"],
     ["All production LLM teams"], ["Throwaway prototypes"],
     ["Golden stale vs product", "Too small false confidence", "Leaking PII in git"],
     {"maintainability": ["Quarterly refresh from prod failures", "PII scrub pipeline"]},
     ["Curate golden set", "CI regression"],
     ["Fixed curated eval set", "Version in git", "CI every change", "Stratify by intent", "Refresh periodically", "Scrub PII"],
     [{"level": "basic", "q": "Golden dataset purpose?", "h": "Fixed benchmark detect regressions on changes."}, {"level": "intermediate", "q": "Build from where?", "h": "Prod failures, support tickets, stratified sampling."}, {"level": "advanced", "q": "Avoid overfit?", "h": "Holdout set; rotate; monitor prod drift."}],
     [{"f": "Golden set", "b": "Versioned canonical eval examples"}, {"f": "Regression gate", "b": "Block release if golden metrics drop"}],
     ["Curated fixed cases", "Git versioned", "CI on PR", "Tags by intent", "Refresh quarterly", "PII scrub"]),
    ("e9-groundedness", "Groundedness",
     "Groundedness checks if LLM answer supported by retrieved context — no unsupported claims, citations match sources, faithfulness to provided documents.",
     "RAG fails when model hallucinates beyond context. Groundedness metrics catch unfaithful generation.",
     "Open-book exam: every claim must cite passage; grader flags invented facts.",
     ["Retrieve context → generate → check claims ⊆ context", "NLI entailment models detect unsupported sentences", "Citation link validation", "Human rubric faithful/partial/unfaithful", "Track groundedness vs retrieval recall jointly"],
     "text", "Context: Refund within 30 days.\nAnswer: Refund within 30 days. ✓\nAnswer: Refund within 90 days. ✗ ungrounded",
     ["Reduces hallucination in RAG", "User trust via citations"], ["NLI false positives", "Chunking misses support"],
     ["Hope prompt says cite sources", "User manual review only"],
     ["Enterprise RAG", "Legal/medical assist"],
     ["Creative writing no sources"],
     ["Citation to wrong chunk", "Partial grounding mixed facts", "Empty retrieval still answers"],
     {"reliability": ["Refuse if no context support", "Show citations UI"]},
     ["Faithfulness to context", "Citation validation"],
     ["Claims supported by context", "NLI faithfulness scores", "Validate citations", "Joint with retrieval recall", "Refuse if ungrounded"],
     [{"level": "basic", "q": "Groundedness meaning?", "h": "Answer faithful to retrieved/provided context."}, {"level": "intermediate", "q": "Measure how?", "h": "NLI entailment, claim decomposition, citation check."}, {"level": "advanced", "q": "Good retrieval bad groundedness?", "h": "Model ignores context; tune prompt; smaller creative temperature."}],
     [{"f": "Faithfulness", "b": "Generation only uses provided context claims"}, {"f": "NLI check", "b": "Entailment model verifies claim supported by chunk"}],
     ["Claims ⊆ context", "NLI faithfulness", "Citation verify", "With retrieval metrics", "Refuse empty context", "Decompose claims"]),
    ("e9-human-eval", "Human Evaluation",
     "Human evaluation uses trained raters or domain experts scoring outputs on rubrics — helpfulness, safety, accuracy — gold standard when automation insufficient.",
     "Automated metrics miss nuance, tone, safety. Humans calibrate judges and catch edge cases pre-release.",
     "Focus group scoring each response 1-5 on rubric dimensions with guidelines.",
     ["Write rater guideline with examples", "Sample stratified outputs blind A/B", "Inter-rater agreement Cohen kappa", "Use results to calibrate LLM judge", "Continuous eval pipeline weekly batch"],
     "text", "Rubric: Accuracy 1-5, Tone 1-5, Safety pass/fail\nBlind compare Model A vs B on same prompts",
     ["Captures nuance", "Calibrates automation"], ["Expensive slow", "Rater drift inconsistency"],
     ["LLM judge only", "User thumbs aggregate"],
     ["Launch gates", "Safety policy eval"],
     ["High volume regression CI only"],
     ["Rater guideline ambiguous", "Small sample wrong conclusion", "Rater sees model name bias"],
     {"cost": ["Sample size power analysis", "Offshore vs expert mix"]},
     ["When need humans", "Inter-rater agreement"],
     ["Rubric + guidelines", "Blind A/B", "Inter-rater kappa", "Calibrate LLM judge", "Stratified sampling", "Periodic batches"],
     [{"level": "basic", "q": "Why human eval?", "h": "Nuanced quality automation misses; gold standard."}, {"level": "intermediate", "q": "Inter-rater agreement?", "h": "Cohen kappa; resolve guideline gaps."}, {"level": "advanced", "q": "Humans + LLM judge?", "h": "Humans label subset; train/calibrate judge; scale."}],
     [{"f": "Rater rubric", "b": "Scoring criteria with anchored examples"}, {"f": "Cohen kappa", "b": "Inter-rater agreement statistic"}],
     ["Expert rubrics", "Blind scoring", "Kappa agreement", "Calibrate judges", "Stratified sample", "Launch gate"]),
    ("e9-offline-evals", "Offline Evaluations",
     "Offline evals run fixed datasets through pipeline without live traffic — measure quality/latency/cost before deploy; complement online A/B.",
     "Ship breaking changes safely. Offline catches regressions cheaply before users hit them.",
     "Staging dress rehearsal: run golden set against candidate model/prompt; compare metrics to baseline.",
     ["Pin baseline scores in dashboard", "Eval harness calls full RAG+agent stack", "Report latency tokens cost per case", "Statistical significance on metric deltas", "Run in CI and nightly"],
     "python", "scores = run_eval(dataset=golden, pipeline=candidate)\nassert scores.accuracy >= baseline - 0.02",
     ["Pre-deploy safety", "Cheap iteration"], ["Sim-to-real gap", "Offline set not prod distribution"],
     ["Online only eval", "Manual smoke test"],
     ["Every LLM release"], ["Realtime-only systems"],
     ["Eval mock tools not real APIs skew", "Ignore latency in offline", "Overfit hyperparams to golden"],
     {"reliability": ["Same infra as prod where possible", "Track eval env version"]},
     ["Offline vs online", "CI eval harness"],
     ["Fixed dataset pre-deploy", "Full stack harness", "Baseline comparison", "CI + nightly", "Metrics quality+cost+latency", "Sim-to-real aware"],
     [{"level": "basic", "q": "Offline eval?", "h": "Run benchmark pipeline without live users before ship."}, {"level": "intermediate", "q": "What to measure?", "h": "Correctness, groundedness, latency, token cost."}, {"level": "advanced", "q": "Offline-online gap?", "h": "Prod traffic distribution differs; monitor online too."}],
     [{"f": "Offline eval", "b": "Benchmark run before production deploy"}, {"f": "Baseline", "b": "Reference scores current prod must beat or match"}],
     ["Golden set harness", "Pre-deploy gate", "Quality+cost+latency", "CI nightly", "Vs baseline", "Sim-to-real gap"]),
    ("e9-regression", "Regression Testing",
     "LLM regression testing detects metric drops when prompts, models, or retrieval change — compare candidate vs baseline on golden set with statistical thresholds.",
     "Silent quality decay on upgrade. Regression suite blocks bad releases like unit tests.",
     "Before/after screenshot diff but for answers: same inputs must not get worse beyond tolerance.",
     ["Automate eval on every PR touching prompts/models", "Define fail thresholds per metric", "Track trend over time not single point", "Bisect which change caused drop", "Include edge cases from incident postmortems"],
     "yaml", "regression:\n  accuracy: { min: 0.92, delta_from_baseline: -0.01 }\n  groundedness: { min: 0.88 }",
     ["Release confidence", "Catch prompt typos"], ["Flaky LLM nondeterminism", "Threshold tuning fatigue"],
     ["Manual QA before ship", "Manual smoke test"],
     ["Production LLM CI"],
     ["Experimental notebooks"],
     ["Temperature>0 flaky CI", "Threshold too tight blocks good changes", "Only happy path golden"],
     {"reliability": ["temperature=0 for regression runs", "Multiple seeds if needed"]},
     ["Regression gate CI", "Threshold design"],
     ["Golden set every PR", "Fail thresholds", "temperature=0 stable", "Trend dashboards", "Add cases from incidents", "Bisect changes"],
     [{"level": "basic", "q": "LLM regression test?", "h": "Compare new vs baseline on fixed set; fail if worse."}, {"level": "intermediate", "q": "Flaky scores?", "h": "temperature=0; multiple runs; median score."}, {"level": "advanced", "q": "Set thresholds?", "h": "Business tolerance; stat sig; separate critical cases hard fail."}],
     [{"f": "Regression threshold", "b": "Min acceptable metric vs baseline"}, {"f": "temperature=0", "b": "Deterministic runs for stable CI"}],
     ["CI golden run", "Baseline delta", "Hard fail thresholds", "temp=0", "Incident cases added", "Trend monitor"]),
    ("e9-retrieval-metrics", "Retrieval Metrics",
     "Retrieval metrics evaluate search quality — recall@k, precision@k, MRR, nDCG — whether relevant documents appear in top-k retrieved chunks for RAG.",
     "Bad retrieval caps generation quality. Measure finder before blaming LLM.",
     "Library catalog search: did right book appear in first k results?",
     ["Label qrels query→relevant doc ids", "recall@k: fraction relevant in top k", "MRR: mean reciprocal rank of first hit", "nDCG: graded relevance position weighted", "Evaluate per query category"],
     "python", "# recall@5 = |relevant ∩ top5| / |relevant|\n# MRR = mean(1/rank_first_relevant)",
     ["Diagnose RAG bottlenecks", "Tune chunking and index"], ["Labeling cost", "Metrics ignore generation"],
     ["End-to-end answer only eval", "Manual spot check"],
     ["RAG pipeline tuning"], ["Non-retrieval tasks"],
     ["High recall wrong chunks noisy context", "Optimizing recall@1 only", "Test set leakage in chunk params"],
     {"observability": ["Log retrieval ids per query in prod sample"]},
     ["recall@k MRR nDCG", "Separate from generation"],
     ["recall@k precision@k", "MRR first relevant rank", "nDCG graded", "Label qrels", "Per-category", "Tune retrieval before LLM"],
     [{"level": "basic", "q": "recall@k?", "h": "Fraction of relevant docs found in top k retrieved."}, {"level": "intermediate", "q": "MRR?", "h": "Average 1/rank of first relevant result."}, {"level": "advanced", "q": "Good retrieval bad answers?", "h": "Groundedness/generation issue; chunk size; prompt."}],
     [{"f": "recall@k", "b": "Relevant retrieved in top k over all relevant"}, {"f": "nDCG", "b": "Discounted cumulative gain for graded relevance"}],
     ["recall@k", "precision@k", "MRR", "nDCG", "qrels labels", "Fix retrieval first"]),
    ("e9-tool-correctness", "Tool-Call Correctness",
     "Tool-call correctness evals whether agent picked right tool with valid args — exact match on name/params, schema validation pass rate, task success after execution.",
     "Wrong tool or args breaks agents silently. Need metrics beyond final answer text.",
     "Grade API call log: expected search_users(name=Alice) vs actual list_orders().",
     ["Gold trace: expected tool sequence and args", "Score tool name accuracy, arg F1, JSON schema valid", "End-to-end task success after real/mock tools", "Mock tools for deterministic CI", "Category errors: wrong tool vs wrong args vs skip"],
     "json", '{"expect":{"tool":"get_weather","args":{"city":"Paris"}},"actual":{"tool":"get_weather","args":{"city":"Paris"}},"pass":true}',
     ["Debug agent failures", "CI on tool-using agents"], ["Mock vs real tool gap", "Brittle exact arg match"],
     ["Final answer string match only", "Manual log reading"],
     ["Function-calling agents"],
     ["Pure chatbots"],
     ["Correct tool wrong arg still fails task", "Overfit to mock handlers", "Ignore optional arg defaults"],
     {"reliability": ["Mock tools mirror prod schemas", "Validate args with same JSON schema as prod"]},
     ["Tool name and args eval", "Mock for CI"],
     ["Gold expected tool+args", "Schema validation rate", "Mock tools CI", "Wrong tool vs wrong args", "End-to-end task success", "Trace logging"],
     [{"level": "basic", "q": "Tool correctness?", "h": "Right tool name and valid args for task."}, {"level": "intermediate", "q": "Eval in CI?", "h": "Mock tools; gold traces; schema validate."}, {"level": "advanced", "q": "Arg partial match?", "h": "Field-level F1; required vs optional; semantic arg match."}],
     [{"f": "Gold trace", "b": "Expected tool calls and arguments for eval case"}, {"f": "Schema pass rate", "b": "Fraction tool args validating JSON schema"}],
     ["Gold tool+args", "Name + arg metrics", "Mock CI tools", "Schema validate", "E2E task success", "Error taxonomy"]),
]

for row in E9:
    tid, title, what, why, model, items, ex_lang, ex_code, adv, dis, alt, use, nouse, fails, prod, exp, kts, iqs, fcs, qr = row
    TOPICS[tid] = T(
        whatIsIt=what, whyExists=why, mentalModel=model,
        howItWorks=[{"type": "list", "items": items}],
        example=[{"type": "code", "lang": ex_lang, "code": ex_code}],
        tradeoffs={"advantages": adv, "disadvantages": dis, "alternatives": alt, "whenToUse": use, "whenNotToUse": nouse},
        failureModes=fails,
        production=prod,
        interview={"expectations": exp, "commonQuestions": [f"Explain {title}"], "followUps": ["How in CI?"], "misconceptions": ["One metric enough"], "traps": ["Eval only happy path"], "strongSignals": kts[:3]},
        keyTakeaways=kts, iq=iqs, flashcards=fcs, quickRevision=qr,
    )

# Write all topics from part 2 (and any from part 1 already in TOPICS when merged)
WAVE09_IDS = [
    "d10-ad-aggregation", "d10-web-crawler", "b1-generators", "b1-iterators", "b1-proxy", "b1-reflect", "b1-symbols",
    "b2-conditional-types", "b2-infer", "b2-mapped-types", "b3-service-workers", "b3-sse", "b3-websockets",
    "b4-nextjs", "b5-css-architecture", "b5-design-systems", "e1-numpy", "e1-pandas", "e2-fine-tuning",
    "e2-gpu-inference", "e2-quantization", "e4-prompt-versioning", "e5-ann", "e5-vector-indexes",
    "e7-agent-loops", "e7-error-recovery", "e7-human-in-loop", "e7-memory", "e7-planning", "e7-sandboxing",
    "e7-state", "e7-tool-calling", "e7-tool-permissions", "e7-workflows",
    "e9-correctness", "e9-golden-datasets", "e9-groundedness", "e9-human-eval", "e9-offline-evals",
    "e9-regression", "e9-retrieval-metrics", "e9-tool-correctness",
]

written = []
for tid in WAVE09_IDS:
    if tid in TOPICS:
        written.append(write_topic(tid, TOPICS[tid]))

print(f"Written {len(written)} files")
for p in written:
    print(os.path.basename(p))
